### ISSUE TITLE
Question: Prefix/suffix per group

### ISSUE THREAD

**Issue by KohGeek** [sgtcaze/NametagEdit#1]
Right now, a group must have both prefix and suffix.
Last time I asked but apparently you decided to go from ground up, so the old issue is nowhere to be found.
So will it work if I only decide to list only AND only prefix/suffix for a group?
Thanks!

**Comment by sgtcaze** [comment]
You can have the prefix or suffix be &f or a space. This will work for the config. Is this what you meant?

**Comment by JustOneMoreBlock** [comment]
@KohGeek The group will work after you add the permission node to the plugin and then add it your permission plugin.

Sorry about that, we have removed older issues as this a new codebase.

You can only display one tag (prefix/suffix) to a group at the moment. Keep in mind, this is limited to 16 characters, a Minecraft limitation.

Cory

**Comment by KohGeek** [comment]
Yes, I know 1 tag of prefix or suffix per group.

My meaning is this:

```
Group Developer - Suffix [Developer]
Group Donator - Prefix [Donator]

A player will be given group donator and developer to be [Donator]xxx[Developer]
```

Is it possible?

**Comment by sgtcaze** [comment]
This _is_ possible, but not with our current functionality. @JustOneMoreBlock and I want to keep NametagEdit group and player specific. This goes out of scope of NametagEdit's functionality, in my opinion.

**Comment by KohGeek** [comment]
Ah okay, I do hope you might be able to implement it once you sort everything out because that will be very useful.
Anyway, thanks!
