### ISSUE TITLE
Tab not working

### ISSUE THREAD

**Issue by mark27205** [sgtcaze/NametagEdit#100]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

1.10
### What plugins are you using? Type /plugins

SCREEN:
http://www2.pic-upload.de/img/31899352/2016-10-14_15.14.10.png
### Please explain your issue?

I'm german!!!!!!
I use the plugin since March and since yesterday dosent works
### How do you reproduce the issue?

I use the plugin since March and since yesterday dosent works
### Is there an error(s) in the console? Please use: https://pastebin.com

No

**Comment by sgtcaze** [comment]
You said the plugin worked for a while then suddenly stopped.

Did you upgrade your server to a new MC version? Did you add any plugins recently? The only two plugins there that look like they might cause issues are Essentials and AdvanceTab.

**Comment by mark27205** [comment]
Yes since March.
No, Essentials and AdvanceTab is ok.
I disabled the plugin(essentials,AdvanceTab) and NTE not works.

**Comment by sgtcaze** [comment]
Do you have errors in your console? Try /ne debug and post the output of this.

Have you added any NEW plugins recently?

**Comment by mark27205** [comment]
http://hastebin.com/kesobuyiqi.md

**Comment by sgtcaze** [comment]
Whoops, just read I said "errors". NametagEdit may produce stack trace, but it can also produce an error to tell you if the plugin was unable to load (does NOT look like stacktrace).

Well, I see there were no errors or stacktrace.

Do the nametags show above the player's head?

**Comment by mark27205** [comment]
No.

**Comment by sgtcaze** [comment]
Try out our newest version on Jenkins.
http://ci.playmc.cc/job/NametagEdit/53/

**Comment by DavidCooll** [comment]
doesnt work still @sgtcaze
