### ISSUE TITLE
People who do not have a set prefix, have it + Sometimes not appearing

### ISSUE THREAD

**Issue by Germanode** [sgtcaze/NametagEdit#104]
**### What version/build of NametagEdit are you using? Type /ver NametagEdit**

4.1.2

**### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

git-Spigot-72c2605-33071ec (MC: 1.10.2)

**### What plugins are you using? Type /plugins**

`NTApi, SimpleBroadcast, RemoteToolkitPlugin, GroupManager, VoidWorld, donateinfo, NametagEdit, BetterGold, BanManager, Cookie, ChatReaction, SkinsRestorer, SuperTrails, MicroJump, CommandSync, ViaVersion, SimpleAPI, ViaBackwards, ElytraCraft, ServerFly, LightAPI, CoreProtect, PotionEffectsReloaded, Ram_Monitor, ClearLag, OpIronDoor, BuycraftX, Votifier, IronElevators, SimplePets, Multiverse-Core, ProtocolLib, AdCraft, FastAsyncWorldEdit, iDisguise, SolarFurnace, NoWeather, ApplyMc, mcMMO, Vault, GAListener, ColoredAnvils, LightSource, BlockParticles, BungeeChatBukkitSync, UltraCosmetics, ObsidianAuctions, Trading, HolographicDisplays, Marriage, PlayerPoints, CSkulls, SimpleAlias, Firework, Multiverse-NetherPortals, BossShop, KeepDeathDrop, BungeeTabListPlus, afkTerminator, Simple_Suffix, CratesPlus, WorldEdit, Orebfuscator4, Essentials, Jobs, mcMMOAction, WhatIsIt, Citizens, EssentialsChat, RedeemableMcMMO, WorldGuard, CSGO-CratesPlus, EssentialsGeoIP, CommandNPC, EssentialsSpawn, MobHunting, CompatNoCheatPlus, SilkSpawners, NoCheatPlus, GriefPrevention, WorldGuardFix, ChestShop, RankVouchers, AuthMe, GPRealEstate, NTAC, MelonCrack, AuthMeBridge`

**### Please explain your issue?**

The issue is that sometimes people with no set prefix get a random prefix of a player that is currently online. I can fix the issue with giving them a prefix &r but I cannot do that to every player ever. I tried with making a group that sets the prefix for everyone to &r but no luck. Problem still appears.

The other problem is that sometimes a prefix does not appear for me. But in 99% cases it appears for others. I just have to do /ne reload, to fix the issue. I have prefixes synced to MySQL.

**### How do you reproduce the issue?**

The random prefix: It happens randomly. but mostly when there are more players on the server and I use /v and /gmsp.

The gone prefix: I just join the server 💃 

### Is there an error(s) in the console? Please use: https://pastebin.com

Only plugins that generate any errors whatsoever are SolarFurnace and RemoteToolkitPlugin which do not interfere with the tablist or nametags.

Thank you!

**Comment by sgtcaze** [comment]
Sounds like the order is not properly setup. Have you used /ne order?

**Comment by Germanode** [comment]
Will try now. Will report back soon. Thanks for the tip 👍

**Comment by sgtcaze** [comment]
No update in 18 days. I hope your issue is solved. If it is not, please reopen the issue.
