### ISSUE TITLE
Prefix's not working when character is offline

### ISSUE THREAD

**Issue by marabb01** [sgtcaze/NametagEdit#105]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

4.1.2

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

1.10.2

### What plugins are you using? Type /plugins

Not Relevant

### Please explain your issue?

I mainly use NTE for staff members. I use another plugin called Citizens which creates a model of a player. However, when the player is not online, NTE does not keep the nametag. In the older version, I just used a redstone loop on command blocks with /ne prefix The_Darthonian '&4[Owner] &l', which worked, but it no longer works. I was wondering if there is a way I can make the prefixes work when the user is offline, so it will still apply to the NPC's. The prefix's work when the user is online

### How do you reproduce the issue?

Give a user a prefix, spawn an npc on citizens (/npc create {user}) then go offline.

### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
Hello sorry for the delay. This is intended behavior, as we only store the nametags of players whose UUIDs can be retrieved. Due to this issue and others, I am considering making a persistent option that will keep the nametag loaded for NPCs and scoreboard.
