### ISSUE TITLE
Invisible players with the NameTag

### ISSUE THREAD

**Issue by altrisi** [sgtcaze/NametagEdit#106]
### Issue:
When a player is invisible, the Nametag continue appearing.
### How do you reproduce the issue?
Be invisible. You can see the Nametag through another player.
### Console errors: None

**Comment by sgtcaze** [comment]
This is a Mojang bug with 1.8. We are unable to fix it, unfortunately.

**Comment by altrisi** [comment]
Ok, it's a Mojang bug.
But in vanilla Minecraft invisible players doesn't have a floating nametag. I think this can be fixed resetting the players nametag when player is invisible and reshowing it when they are visible again.
Thanks.

**Comment by sgtcaze** [comment]
This might work @altrisi. The issue is knowing when a potion of invisibility is applied to a player.

I do not a see an event to indicate when a potion effect is applied to a player (via a plugin). PlayerItemConsume or ProjectileLaunch might work for certain potions.

https://hub.spigotmc.org/javadocs/spigot/

**Comment by altrisi** [comment]
I think _getActivePotionEffects_ can be used (see 
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#getActivePotionEffects()
)

**Comment by sgtcaze** [comment]
Yes, but the issue is seeing *when* the effect is applied. There is no event for doing player.addPotionEffect.

I will look into it further, but I am not seeing a way to listen for that.

**Comment by ygtdmn** [comment]
@sgtcaze I think you can fix like that:
- Create a HashMap<Player,Boolean> named isTagVisible.
- On player move event check Player.getActivePotionEffects() and check isTagVisible for player. If player have invisibility potion and isTagVisible is true make isTagVisible false and setNameTagVisibility to never. And vice versa.
- Also check PotionSplashEvent and PlayerItemConsumeEvent.

**Comment by Joansitoh** [comment]
You can use this events: PotionSplashEvent and PlayerItemConsumeEvent.
