### ISSUE TITLE
NametagEdit invisibility issue

### ISSUE THREAD

**Issue by Tck13** [sgtcaze/NametagEdit#107]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
1.8.8-R0.1-SNAPSHOT
### What plugins are you using? Type /plugins
Dont matter in this cause, because without this plugin everything works without trouble also on a server with only this plugin gets same result.
### Please explain your issue?
When someone get invisibility potion nametag dont get hidden.
### How do you reproduce the issue?
Give someone invisibility potion and the nametag dont hide.
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
This is a Mojang bug that was fixed in 1.9. There is no fix available at the moment for 1.8 servers.

See
#106 #37 #15 #14 and #5
