### ISSUE TITLE
API Questions

### ISSUE THREAD

**Issue by stuntguy3000** [sgtcaze/NametagEdit#108]
Hi!

I have a client who is using this plugin, and I am making a game plugin. Involved with this game plugin is custom scoreboards/teams.

Is there a way to "refresh" a players custom name-tag so it re-appears after a match?

-Luke

**Comment by sgtcaze** [comment]
If I understand you correctly, the player has a custom nametag in the Players/Groups configurations, you are applying a new nametag during the game phase, and post game you want to retrieve the original tag?

At the moment that API does not have this behavior, but I can add it in if this is what you like!

**Comment by stuntguy3000** [comment]
My plugin generates its own Scoreboard/Objective entities and applies them to the players. I don't give the players any custom nametags or anything. I haven't checked out the source code for this plugin, but when I restore the scoreboard to what they had when they join the nametag remains white.

**Comment by sgtcaze** [comment]
With that in mind, you could call (from the API):
clearNametag(Player player) to prevent possible crashes from belong to different scoreboard teams

I can make a method
reloadNametag(Player player) to update it from flatfile/database. Would you like this?

**Comment by stuntguy3000** [comment]
That method seems like it will work exactly, thanks!

**Comment by sgtcaze** [comment]
Please see https://github.com/sgtcaze/NametagEdit/commit/745dab3bd2c5c540a93391f63a108ec88cd75772 with a development build available at http://ci.playmc.cc/job/NametagEdit/55/. Let me know if this works for you!

**Comment by stuntguy3000** [comment]
Thank you, I will test it tomorrow.
