### ISSUE TITLE
NameTagEdit issue with PremiumVanish / SuperVanish

### ISSUE THREAD

**Issue by Sikatsu** [sgtcaze/NametagEdit#109]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
Version 4.1.2 (devbuild)
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
1 version behind, Spigot 1.11
### What plugins are you using? Type /plugins
Not sure if needed, will wait until asked.
### Please explain your issue?
When I leave vanish, players are not able to see my [Owner] tag. Basically, the tag never shows up for players but only for staff. I really hope theres a possible fix for this.
### How do you reproduce the issue?
Hmm, explained above I guess.
### Is there an error(s) in the console? Please use: https://pastebin.com
There isn't any error.

**Comment by sgtcaze** [comment]
Unfortunately I will not be able to test with PremiumVanish - however, SuperVanish appears to have an API. I'll test it out and see if I can listen to the unvanish event and fix nametag visibility there.

**Comment by kcmartz** [comment]
I also use PremiumVanish. I was wondering why it shows red and will not enable. I'm on 4.1.2, but console thinks it's out of date.

**Comment by sgtcaze** [comment]
Ah, try our most recent dev build. The ones on spigot do not support 1.11. Then we'll try out the premium vanish thing @kcmartz and see how your issue overlaps.

**Comment by Sikatsu** [comment]
I use the devbuild, and this issue still occurs. That's why I reported it.

Also, nametagedit is being rather heavy in timings compared to
AnimatedNames. React also says it's a "Serious issue" in React his timings
book.

Op wo 30 nov. 2016 21:44 schreef sgtcaze <notifications@github.com>:

**Comment by sgtcaze** [comment]
@Sikatsu I am talking to @kcmartz who is using an out of date build. They are having the same issue as you. Also, please post timings. No one has reported issues regarding timings/lag.

Edit: timingsv2 information would be very helpful

**Comment by Sikatsu** [comment]
I'm sorry, thought it was about the issue I reported and wanted to inform you.

I reported the line on Spigot Discussions earlier, everytime I use timings it turns yellow/red. Timings v1 and React Timings.

I do not have timings v2 (PaperSpigot)

**Comment by sgtcaze** [comment]
Are you using flatfile or the database? Are you modifying the API in anyway, or calling any commands frequently? I found your post regarding the line:
```
0.05% 103.73% 0.16 s 51.87 ms 0.0 0.0k Task: NametagHandler$1(Single)
```

Unfortunately this does not tell me much. I have an idea of what could be producing the lag, just need to verify. I will also see if I can reproduce the vanishing-removing-nametag thing.

**Comment by Sikatsu** [comment]
Flatfile I suppose. Not using MySQL.

I'm not modifying the API or calling any commands frequently.

Any other information you need so we can try to solve this matter?

Thanks :)

**Comment by kcmartz** [comment]
Yea, I am already using the build from 3-4 days ago, same thing as @Sikatsu

**Comment by kcmartz** [comment]
Only thing I really use my mysql for is coreprotect and one or two other things. Not premiumvanish.
Oh yea, I'm using PaperSpigot.

**Comment by sgtcaze** [comment]
@kcmartz do you also experience lag/poor timings like @Sikatsu?

I'll try to get both of these issues handled by Friday. I have a pretty busy week, but I can get on top of this.

**Comment by Sikatsu** [comment]
@sgtcaze 

New timings: http://prntscr.com/de3j50

React timings (from spigot): http://prntscr.com/de3k0t

Note: No other plugins at all shows ''Problematic issue'' in the React timings.

**Comment by sgtcaze** [comment]
Hey again, regarding the timings - does this affect game play in any way? I looked at the code and the timings and arrived at the conclusion (without tinkering) that the slowest operations occurs:

From Line 55 - 61
https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/NametagHandler.java#L55-L61

Since you said you were using FlatFile, this operation is called
https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/storage/flatfile/FlatFileConfig.java#L40-L49

I believe the "issue" is several things:
- Loading the configuration on the main thread
- Initializing classes for reflection
- Applying tags/loading individual data

However, while this does disrupt timings, I do not believe it to be an issue actively affecting the lag on your server. I will take steps to stop this from appearing in timings, however.

**Comment by Sikatsu** [comment]
Well, there is lagg at the server, and it says NameTagEdit and LWC is the cause.. before on AnimatedNames, the performance was better :/

**Comment by sgtcaze** [comment]
I think that's correlation above causation. Regardless, please try this build:

http://ci.playmc.cc/job/NametagEdit/57/

I have a suspicion it will reflect very well in the timings.

Edit: Then we will move onto the vanish bug

**Comment by Sikatsu** [comment]
Can't seem to find timings issues anymore right now, will still have to test when more players are online :)

**Comment by kcmartz** [comment]
I couldn't even get it to work! Nothing shows, red name in **/pl**.

I can try the new build though.

EDIT: Plugin shows green with new build!

**Comment by sgtcaze** [comment]
Glad to hear @kcmartz 

Also if the timings are good now, then we can take a look at that Vanish plugin. Which do you prefer @Sikatsu?

**Comment by Sikatsu** [comment]
How do you mean exactly? :)

Op ma 12 dec. 2016 03:10 schreef sgtcaze <notifications@github.com>:

**Comment by JustOneMoreBlock** [comment]
Is this still an issue? If so, Which plugin are you using at the moment?
PremiumVanish or SuperVanish

**Comment by Sikatsu** [comment]
It's still an issue with PremiumVanish and the scoreboard of mcmmo.

**Comment by Sikatsu** [comment]
Any news about this issue?

**Comment by SwiftSwamp** [comment]
Has this issue been resolved? Would love to use it if it has as I want to use PremiumVanish.

**Comment by sgtcaze** [comment]
Haven't been able to test because I haven't purchased PremiumVanish. If anyone is willing, we can setup private tests on your servers and see if we can fix the issue.

**Comment by Sikatsu** [comment]
I would be more then glad to help.

**Comment by sgtcaze** [comment]
Upon further review and tinkering, I have come to the conclusion this is out of the scope of NametagEdit, and cannot be done cleanly.

There are countless plugins that have the potential to override NametagEdit nametags. In this case, a command overrides the nametag. A potential solution is to **refresh** the nametag after said command is executed. However, this does not take into consideration if the player had permission to execute the command in the first place and it poses an unnecessary risk with cooldowns and nametag refresh spamming.

The easiest, and most efficient way this can be accomplished is if the vanish plugin retrieved the Nametag for a player post /vanish, and if it exists, call a method to refresh the player's nametag.
