### ISSUE TITLE
IllegalArgumentException : Team ID 1 already exists in this scoreboard.

### ISSUE THREAD

**Issue by incrementing** [sgtcaze/NametagEdit#11]
Getting an IllegalArgumentException when a player joins the server,
It appears its happening randomly as i've yet to find a pattern.
But its always a player without a tag being kick when a player with a tag joins the server and doesn't happen all the time.

Kick Message:http://prnt.sc/a5xqwm.

Console Upon PlayerQuitEvent: (normal?... no stacktrace or odd kick reason in the console)
[Server thread/INFO]: Incrementing lost connection: Disconnected

**Comment by sgtcaze** [comment]
Are you making any API calls? How many players does the server get? (Does incidents peak with more players?)

**Comment by JustOneMoreBlock** [comment]
I did a lookup of this error and appears you likely have a scoreboard with the same team name.

Most notably a quick fix is to reset your scoreboard file in your <world>/data/ directory, just by removing it.

Please make sure you make a backup before doing anything.

**Comment by sgtcaze** [comment]
I would hazard a guess that a team packet was never cleared. Server version @Incrementing ? (Exact version, not 'latest' please)

**Comment by incrementing** [comment]
@sgtcaze git-Spigot-db6de12-e1-ebe52 (1.8.8-R01-SNAPSHOT)
And yes I'm making API calls, on player join prefix is cleared then set if their rank has changed since last join.

**Comment by sgtcaze** [comment]
Ah, try placing that on a 1 tick delay.
https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/NametagHandler.java#L149

As you can see here we send teams and clear the player on join. However, the priority is set to highest, so we are firing after every other PlayerJoinEvent. This is probably causing the issues.

**Comment by incrementing** [comment]
@sgtcaze Ohh I see, I'll put a delay in as you suggested and see what happens.

**Comment by JustOneMoreBlock** [comment]
Are you still have issues?
