### ISSUE TITLE
essentials /nick off removes tab prefix until updated manually

### ISSUE THREAD

**Issue by comfysquirrel** [sgtcaze/NametagEdit#110]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
`4.1.2`
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
`CraftBukkit version git-Spigot-f19bb2c-2b7808f (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
### What plugins are you using? Type /plugins
`PermissionsEx, PlugMan, NametagEdit, ServerListPlus, Vault, Essentials, EssentialsSpawn, PlaceholderAPI, EssentialsChat, EssentialsGeoIP`
### Please explain your issue?
When doing essentials **/nick**, the name in tab updates fine. (using setting `change-playerlist: true` in essentials config.) but when doing **/nick off**, the nte prefix in tab dissapears and only the username is there (in the right color though). It's fixed when doing **/nte reload**.
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
This sounds like essentials is setting the player list names to &fName.

I will check and see if Essentials has Custom nametag events we can listen to. However, I believe their functionality is intended to have this behavior.
