### ISSUE TITLE
NTE Perm issue

### ISSUE THREAD

**Issue by XlerPlays** [sgtcaze/NametagEdit#112]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
The current version 4.0.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
MC 1.11
### What plugins are you using? Type /plugins
World Edit
Open Inv
AntiCheatReloaded
Pex
ClearLag
BuycraftX
Vault
Lockette
WorldGuard
Essentials
EssentialsGeoIP
EssentialsChat
EssentialsAntiBuild
EssentialsSpawn
EnjinMinecraftPlugin
EssentialsProtect
### Please explain your issue?
So when I assign the * permission to 2 or more groups, they all have the same prefix in tab and above their head, but when I remove the * permission, they get the correct tag that was set to them. Is there a possibily to fix this? Or is there something Im missing. The ranks are: Owner, Co-Owner, Head-Admin, and Admin. They all end up having the tag that was set for Owner. I know you can revoke the perms by doing - -nte.owner but that still doesnt work.
### How do you reproduce the issue?
By assigning other ranks the * permission.
### Is there an error(s) in the console? Please use: https://pastebin.com
There are none.

**Comment by sgtcaze** [comment]
Assign an order to your groups by using the command:
/ne order

The order should be from highest to lowest, e.g.:
/ne order Owner Moderator Regular

**Comment by sgtcaze** [comment]
No response in 4 days. We are assuming this is a simple misconfiguration. Please reopen if you continue having issues.
