### ISSUE TITLE
disconnect error BUG

### ISSUE THREAD

**Issue by FlamestoN** [sgtcaze/NametagEdit#113]
My players randomly get dissconnect from server.
BungeeCord error:
http://pastebin.com/UdTL5C7y

NTE: 4.1.2
SPIGOT: git-Spigot-f950f8e-1d54397 (MC: 1.11)

**Comment by sgtcaze** [comment]
How many servers on your network use NametagEdit? I believe this error can safely be ignored. I will, however, look into ways of suppressing this.

Have you noticed any problems when this error occurs?

**Comment by FlamestoN** [comment]
Two servers used NameTagEdit.
No, I have not noticed problems when disconnect from the server with NameTagEdit, only the inscription in console: PLAYERNAME lost connection: Timed out. And error in BungeeCord console which I put above (pastebin).

**Comment by sgtcaze** [comment]
Closing this as the new issue is #131
