### ISSUE TITLE
LibsDisguises sliding

### ISSUE THREAD

**Issue by Sammo346** [sgtcaze/NametagEdit#115]
**### What version/build of NametagEdit are you using? Type /ver NametagEdit**
4.1.2 (also tried with dev build listed as 43+)

**### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
git-Spigot-f950f8e-1c07d5c (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

**### What plugins are you using? Type /plugins**
BlockParticles, BungeeSuiteWarps_1.9, BungeeSuiteHomes_1.9, WorldEdit, Questioner, PlaceholderAPI, MythicLib, BungeeSuiteTeleporter_1.9, NoSpawnerChange, WorldBorder, NametagEdit, McmmoBungeeCord, ProtocolLib, WorldGuard, LibsDisguises, Super_Elytra, PermissionsEx, EpicWorldGenerator, RandomTeleport, EffectLib, mcMMO, Vault, MagicSpells, BungeeTabListPlus, MysqlPlayerDataBridge, Essentials, MarriageMaster, Towny, KillerMoney, LiteBans, Brewery, MythicMobs, TownyNameUpdater, WorldGuardExtraFlags, VentureChat, EssentialsMysqlStorage, MyPet

**### Please explain your issue?**
When using NametagEdit with LibsDisguises (9.2.2), disguises slide around when you attempt to move.
The dev suggested pushing needs to be disabled for any plugins using custom scoreboards. The problem does not happen with NTE disabled.

**### How do you reproduce the issue?**
Install NTE. Install Libsdisguises (+ Protocollib dependancy).
Disguise as anything and move.

### Is there an error(s) in the console? Please use: https://pastebin.com
None

**Comment by sgtcaze** [comment]
Do you have a video of the nametags "sliding" around? 

I am skeptical of disabling the "push" variable as a valid solution, but we can do this, no problem. It's a feature I am sure others would like.

**Comment by Sammo346** [comment]
It is the disguise/player itself that slides around.

This is me tapping 'A' and 'W' once, as you can see I continue moving even with the chat up.
https://i.gyazo.com/b5b7e03ae394503f42ff39e1830785d9.gif
(it also occurs when flying)

When a player has no nametag prefix, this instantly stops happening.

The dev of LibsDisguises seemed to think of this as a known issue, and jumped to the conclusion that lead me here. https://www.spigotmc.org/threads/libs-disguises-paid.197401/page-2#post-2068132

**Comment by sgtcaze** [comment]
Cool, thanks. I'll try to get an update out soon to test this theory.

**Comment by Sammo346** [comment]
No rush at all for you, but do you have an eta? I'm waiting on this one fix to finally release my 1.8 to 1.11 update.

**Comment by sgtcaze** [comment]
Alright please see this commit: https://github.com/sgtcaze/NametagEdit/commit/9754e35c6d7def5811937064887def5080f08281

Build 58 on the Jenkins reflects these changes: http://ci.playmc.cc/job/NametagEdit/58/

I am unable to test at the moment with multiple accounts/test the reflection. It looks like it should work... so please test and let me know!

**Comment by Sammo346** [comment]
The problem still persists, unfortunately. (Even after I saw there's a new config option)
https://i.gyazo.com/87573fec4fb35fafcb3023cacce4352e.gif

**Comment by sgtcaze** [comment]
So you set disable pushing to true and it didn't work? Did you try to collide with another player to make sure the setting is being applied?

**Comment by Sammo346** [comment]
Colliding still occurs between two nametag'd players.

**Comment by sgtcaze** [comment]
Alright I will try to test this ASAP. Thanks for letting me know.

**Comment by Sammo346** [comment]
If you need an extra account, I'm around.

**Comment by sgtcaze** [comment]
Sorry for the delay. Will wrap this up today, now that I have a window of opportunity this weekend.

**Comment by sgtcaze** [comment]
Alright it was a small mistake. See this commit: https://github.com/sgtcaze/NametagEdit/commit/4e444f343b9bd3a2d82671e35719152c2cb9a12a

Build 59 on the Jenkins reflects these changes: http://ci.playmc.cc/job/NametagEdit/59/

Confirmed pushing has been disabled.

**Comment by Sammo346** [comment]
Confirmed LibsDisguise sliding issue is fixed.

Thanks for the work
