### ISSUE TITLE
Spaces

### ISSUE THREAD

**Issue by madsenbassen** [sgtcaze/NametagEdit#116]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.3
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
http://prntscr.com/dglprg
### What plugins are you using? Type /plugins
http://prntscr.com/dglpxk
### Please explain your issue?
Cant use spaces
### How do you reproduce the issue?
/nte player xMadz prefix    &7&lowner
### Is there an error(s) in the console? Please use: https://pastebin.com
No

**Comment by JustOneMoreBlock** [comment]
Put in double-quotes:
`/nte player xMadz prefix "&7&lowner "`
