### ISSUE TITLE
Inheritance Prob. with PEX

### ISSUE THREAD

**Issue by PortalBeast** [sgtcaze/NametagEdit#117]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-6016ac7-10c10b3 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
Projangtile, WorldEdit, MinePacks, Essentials, PlaceholderAPI, PacketListenerApi, MythicLib, ClearLag, CrackShot, CustomArmors, NametagEdit, MapManager, BelovedBlocks, CustomJoin, WorldGuard, ProtocolLib, WeatherVote, SimpleAutoRespawn, SuperTrails, HidePlugins_Reloaded, DiscordBotSP, EssentialsChat, BossBarAPI, PermissionsEx, MaintenanceMode, ActionAnnouncer, Tablist, Vault, ServerListPlus, EssentialsSpawn, TimeVote, HologramAPI, Realistic-Swimming, Autorank, AnimatedFrames, ResourcePackDownloader, HolographicDisplays, Citizens, MythicMobs, Quests, KingdomCraft, PickupMoney, Shop, ItemFrameShops, AdvancedKitsReloaded, CommandNPC
### Please explain your issue?
I use PEX and each group inherit the previous until all inherit the first group. Each group has its own permission which is nte.group. I think the problem is that because each group inherit the previous, then they all have the different tags at the same time which confuses the plugin.
### How do you reproduce the issue?
By creating a sh## ton of ranks and making them inherit the previous ones.
### Is there an error(s) in the console? Please use: https://pastebin.com
Nop

**Comment by sgtcaze** [comment]
Use /ne order and it will fix your issue.

**Comment by PortalBeast** [comment]
Works now.. Thanks for the help !
