### ISSUE TITLE
Tablist format still appears after disabling

### ISSUE THREAD

**Issue by PetKCH** [sgtcaze/NametagEdit#118]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.3
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
Paper version git-Paper-959 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
https://gyazo.com/cb85baea191cfcfdf5ab40cc14c628d9
### Please explain your issue?
Even after placing "TabListDisabled: true" the prefixes and suffixes will appear on Tab.
### How do you reproduce the issue?
//
### Is there an error(s) in the console? 
None

**Comment by sgtcaze** [comment]
Did you /reload or restart your server? Will look into this ASAP.
Edit: I think I have an idea what it is.

**Comment by PetKCH** [comment]
I've tried to restart in order to see if it will fix itself however nothing has changed.
