### ISSUE TITLE
Group not showing in TAB

### ISSUE THREAD

**Issue by Spencer7k** [sgtcaze/NametagEdit#119]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.3
### Please explain your issue?
one of my ranks is not showing the prefix in TAB or above play heads.  All of the other groups work just fine, and i tried turning on the debug and im getting no errors. http://pastebin.com/w21B1Hdw  Thats my groups, its the foreman group that is having issues, its showing any lower rank than it.
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by Darlelet** [comment]
Isn't it showing at all, or does it seem to be cutted down?

**Comment by Spencer7k** [comment]
It shows any other NTE tags the player also has, but if they have no other tags it shows nothing, all of the other tags work just fine, its only foreman that is having trouble..

**Comment by sgtcaze** [comment]
Nametags cannot have the same SortPriority. SortPriority should be unique.

**Comment by Spencer7k** [comment]
I tried making the sort priority unique and that did not fix it

**Comment by sgtcaze** [comment]
Is nte.f an explicit permission given to the group? 

Is the nametag order correct? e.g. the groups are ordered from highest to lowest priority?
Take a look at /ne order if this is the case: https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Commands.creole

**Comment by Spencer7k** [comment]
they are not listed in the groups file by priority, but i dont feel like that is the cause since all of my other tags work perfectly. also i cant use the /ne order command because i have like 16 groups and it is too long to actually type out....  nte.f was a test to see if the problem was the original perm of nte.foreman, i also tried test.test as the perm and that did not work either.

**Comment by sgtcaze** [comment]
Please post your updated groups.yml. If need be I will add more information to the debugger.
