### ISSUE TITLE
null error with the plugin on version 1.7.10 bukkit

### ISSUE THREAD

**Issue by junny2233** [sgtcaze/NametagEdit#12]
copy & paste the link in a new tap

http://pastebin.com/raw/AtZ4NETP

**Comment by JustOneMoreBlock** [comment]
- Can you confirm the CraftBukkit/Spigot version you're using?
- List of Plugins

Are you running the latest build #23?
http://ci.playmc.cc/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

http://ci.playmc.cc/job/NametagEdit/

I've tested 1.7.10 and appears to be working fine on my end.

**Comment by junny2233** [comment]
I think the issues is the bukkit version...

The server is running Cauldron-MCPC-Plus version git-Cauldron-Reloaded-1.7.10-1.1388.1.0 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by sgtcaze** [comment]
Oh... forgot that didn't exist in 1.7. Will have a fix soon.

**Comment by junny2233** [comment]
Ok awesome!! please let us know when this change is done... thanks you! for quick respond
