### ISSUE TITLE
There are spaces after each name (not in tab). How do I remove these? They make the names look unprofessional.

### ISSUE THREAD

**Issue by KnowItAllKing** [sgtcaze/NametagEdit#120]
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
Do you happen to have a lot of bold characters in the nametags, or really long nametags in general?

**Comment by KnowItAllKing** [comment]
Just one bold character before the name. '&4&lS &7'

**Comment by KnowItAllKing** [comment]
And no long nametags

**Comment by sgtcaze** [comment]
I see. Unfortunately there is nothing we can do to satisfy what you require.From the server side, all nametag functions in NametagEdit are tantamount to the vanilla scoreboard commands.

**Comment by KnowItAllKing** [comment]
Ok thanks. Why is Factions UUID interfering with NTE?

**Comment by sgtcaze** [comment]
In what way is it interfering? Are nametags not displaying, or is there some error generated by either plugin?

**Comment by KnowItAllKing** [comment]
It keeps changing tab. I want my NTE tab, but when a player is in a faction, it overrides NTE.

**Comment by sgtcaze** [comment]
Perhaps there is a setting in FactionsUUID that allows you to disable tab formatting? I have not used this plugin, but I will look into contacting the author if there is no setting.

**Comment by KnowItAllKing** [comment]
Ok thanks. I can send you the plugin if you want. I got the leaked one ^_^ and it's no different than the payed version. Also, could you join my server? nbs.serv.nu

**Comment by FlippantCactus** [comment]
Don't advertise you're using a leaked one... Also you can freely compile it here: https://github.com/drtshock/Factions

**Comment by sgtcaze** [comment]
Closing as the original issue is not something we can fix, and is the result of the bold character and later versions of minecraft.
