### ISSUE TITLE
I cant see see 

### ISSUE THREAD

**Issue by aleksandarbgbg** [sgtcaze/NametagEdit#121]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.3
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
1.10.2-R1
### What plugins are you using? Type /plugins
http://i.imgur.com/SE7D2OH.png
### Please explain your issue?
I cant see my nick prefix in TAB. This is my TAB and nametage configuration:
http://i.imgur.com/LpKjEmF.png
![image](https://cloud.githubusercontent.com/assets/19761618/21384484/70b55872-c773-11e6-8e4b-165d214ff642.png)
I have added the permissions but still not working :/
### Is there an error(s) in the console? Please use: https://pastebin.com
No

**Comment by sgtcaze** [comment]
Please post your config.yml, perhaps you have TabListDisabled?

Try /ne debug and see if a tag is being applied to you.

**Comment by aleksandarbgbg** [comment]
i fix it, thanks

2016-12-21 20:07 GMT+02:00 sgtcaze <notifications@github.com>:
