### ISSUE TITLE
NameTagEdit different Tag in tab when re logging 

### ISSUE THREAD

**Issue by callibbers** [sgtcaze/NametagEdit#123]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.3 
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
It is my localhost but it is running 1.8.8 https://gyazo.com/2eec68eb2ea66ec9fd061cb707aca539

### What plugins are you using? Type /plugins
PermissionsEx AdvancedBan NameTagEdit Essentials Vault EssentialsSpawn EssentialsChat
DeluxeChat Playervaults 

### Please explain your issue?
Hello I am using NameTagEdit I fully configured a few groups witch is Helper Moderator Admin config: http://pastebin.com/qA0vvUex I am also using DeluxeChat config:  http://pastebin.com/Pv7dnZSQ so when I went and saved and reloaded PermissionsEx and NameTagEdit and DeluxeChat and went and gave my self '*' in PermissionsEx It gave me the "Helper" Tag in tab when I relogged PermissionEx config: http://pastebin.com/Dexx4iwA my problem is that when I am default or in my pex config I am "Member" and it shows Helper in Tab when I am not Helper rank.

### How do you reproduce the issue?

Not sure.

### Is there an error(s) in the console? Please use: https://pastebin.com
There is not any errors in console when I reload all 3 plugins

**Comment by sgtcaze** [comment]
Organize your groups use /ne order

The highest priority group should be at the top, then it goes downward.
