### ISSUE TITLE
Weird Format Issues

### ISSUE THREAD

**Issue by PetKCH** [sgtcaze/NametagEdit#124]
TacoSpigot Latest 1.8.8
NTE 4.0.2

When i do this "/nte player Thronius prefix '&8.&cDemiGod&8.&c'"
I get https://gyazo.com/6d143bd9db0ca2506227108f6136659e

However when I add in few spaces "/nte player Thronius prefix '&8.&cDemiGod&8. &c'"
I get this https://gyazo.com/56ba92182129adff835bea38efc2b60f
Still didn't pick up &c on the end.

**Comment by sgtcaze** [comment]
I believe this is a minecraft bug. Please note: &8.&cDemiGod&8.&c is 17 characters, the max is 16. This is where that 'borrowed' character goes.

**Comment by PetKCH** [comment]
Would it be possible, if tag goes over 16 characters that is puts the actual area for username renaming in use? Like for example, if tag has &cBla which is over the 16 character limit, it would put it inside players username, so it would make it like '&cBla {Username}' inside that part?

Also, can I anyhow make it so it would show EssentialsX nicks while having prefixes/suffixes in use? :)

**Comment by sgtcaze** [comment]
The username is still limited to 16 characters, so if you take some or most and place it in the prefix, the overlap may still exceed the maximum name length. Plus I think it'll mess with your skin.
