### ISSUE TITLE
issue with placeholders from clip

### ISSUE THREAD

**Issue by downboy** [sgtcaze/NametagEdit#125]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.3
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
![Image of ver](http://image.prntscr.com/image/3774bc5e4eac4a5586ac5554bc40621b.png)
### What plugins are you using? Type /plugins
![Image of ver](http://image.prntscr.com/image/e1ceb3f2ff374f91b0b042d86bc01b02.png)
### Please explain your issue?
the normal placeholders from clips are not loaded!
### How do you reproduce the issue?
![Image of ver](http://image.prntscr.com/image/2a3d79c3bde04231bfc3647d66f7e791.png)
### Is there an error(s) in the console? Please use: https://pastebin.com
there is no error, but here is my debug in console: 
![Image of ver](http://image.prntscr.com/image/cf474059326a432288e2f7d504934689.png)

**Comment by downboy** [comment]
i fixt the issue: 

> If you were sent here from another plugin, simply download this plugin and install it in your plugins folder. After the first start of this plugin, you will need to download expansions from the placeholder cloud to be able to use placeholders. Example if you want Factions placeholders, use /papi ecloud list all <page> and click the Factions expansion to download it. After it is downloaded, use /papi reload to enable it. Now you can use %factions_faction% as a placeholder. This same method applies for every available expansion.

**Comment by sgtcaze** [comment]
Glad to hear you fixed!
