### ISSUE TITLE
How does NameTagEdit integrate with PermissionsEx?

### ISSUE THREAD

**Issue by dfinucane** [sgtcaze/NametagEdit#126]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.3
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
[11:16:18 INFO]: This server is running CraftBukkit version git-Spigot-7d78b81-f9e0440 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
Punishment, TTA, WorldEdit, Modifyworld, NametagEdit, RandomTP, ProtocolLib, WorldGuard, SkinsRestorer, VoxelSniper, PermissionsEx, Vault, Coupons, MassiveCore, Essentials, CTSNCPlus, EpicRename, HolographicDisplays, KitAdder, CreeperCraft, AuctionHouse, ChestCommands, EssentialsChat, PlayerVaults, EssentialsSpawn, CratesPlus, Factions, SilkSpawners, CrazyEnchantments
### Please explain your issue?
I want to know how the integration with PermissionsEx works.  I was hoping the NameTagEdit would see that I am using PermissionsEx and it would get the group list from that but it seems like I also have to maintain NameTagEdit groups.  How does NameTagEdit integrate with PermissionsEx?
### How do you reproduce the issue?
NameTagEdit is not asking PermissionsEx for my group list.
### Is there an error(s) in the console? Please use: https://pastebin.com
No errors.

Thanks

**Comment by sgtcaze** [comment]
You  must maintain your groups separately. NametagEdit listens for when a player's permission group changes, and applies the nametag of the group they have access to with the highest priority.
