### ISSUE TITLE
Nothing coming up in tab?

### ISSUE THREAD

**Issue by cprenaveau** [sgtcaze/NametagEdit#13]
I'm using the plugin just fine on my server in game the player see the tags but when they press tab nothing comes up? am I doing something wrong? Please help me with this problem will really appreciate it.
-PlanetMinecraft4

**Comment by sgtcaze** [comment]
Please post your config.yml. This sounds like you have TabListDisabled set to true, or are using server/client version < 1.8.3

**Comment by cprenaveau** [comment]
i am useing 1.7.10 bukkit server and my config is:
http://pastebin.com/VJbRRH70

**Comment by sgtcaze** [comment]
Are you receiving any errors in the console? Are you using a database or flatfile?

Edit: Try this version for me please http://ci.playmc.cc/job/NametagEdit/27/

**Comment by JustOneMoreBlock** [comment]
Tested on 1.7.10.
Used his config.
Flatfile or database doesn't matter.
Tabs work fine.

Closing issue
