### ISSUE TITLE
Issue with tags disappearing with mcmmo + paperspigot

### ISSUE THREAD

**Issue by PhanaticD** [sgtcaze/NametagEdit#130]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
i am using build 59
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
git-Paper-1029 (MC: 1.11.2)
### What plugins are you using? Type /plugins
mcmmo (dev build 179), nametagedit, and paperspigots anti-pushing feature are the only relevant ones
### Please explain your issue?
when you gain a point in a skill in mcmmo it pops up with a scoreboard on the side showing your skill levels, this causes the tablist to change to all white. or when using /mctop
### How do you reproduce the issue?
gain a mcmmo level, or type /mctop and wait for the scoreboard on the side to disappear
### Is there an error(s) in the console? Please use: https://pastebin.com
not that I can see

**Comment by sgtcaze** [comment]
We use mcMMO and NametagEdit on a server I work for. Players level up all the time without issues.

We're using 4.0.3 of NametagEdit and v1.5.05-SNAPSHOT-b133 of mcMMO. Not sure how out of date we are with mcMMO, but we'll probably update soon. My best guess is a change to the scoreboard code in mcMMO or as you mentioned, PaperSpigot.

I'll be able to test this soon with 1.11.2.

**Comment by PhanaticD** [comment]
I did not notice anything until enabling paperspigots anti-pushing, it might be interfering somehow

**Comment by sgtcaze** [comment]
It is worth noting NametagEdit has an AntiPush feature available in 4.0.3. This only applies to players that have nametagedit-nametags, however.

**Comment by Sikatsu** [comment]
Using normal spigot and mcmmo, I have the same issue when using /mcscoreboard or /mctop.

**Comment by andris155** [comment]
Same problem. :(

**Comment by 0-x-2-2** [comment]
hmm you could give every player a nametag-edit tag then turn on the nametagedit antipush instead of the paper one

**Comment by sgtcaze** [comment]
Are you still experiencing this issue?

**Comment by Sikatsu** [comment]
Yes I am. Nametags dissapear way to often. Seems to be buggy with mcmmo.

**Comment by JustOneMoreBlock** [comment]
@PhanaticD @andris155 @Sikatsu Can you try the latest build and let us know if this issue is still occurring?

**Comment by Sikatsu** [comment]
It is.

**Comment by andris155** [comment]
I tested and this bug not fixed.
Paper build 1167
```
settings:
  enable-player-collisions: false
```
mcMMO: 1.5.0.8 build 196
NametagEdit: 4.1.7 build 20

**Comment by andris155** [comment]
mcMMO level up remove NameTag.

**Comment by Leomelonseeds** [comment]
Still not working...

**Comment by JustOneMoreBlock** [comment]
Is this still an issue? Please use the latest build and re-open.
