### ISSUE TITLE
Nametags not disappearing when F1 is enabled

### ISSUE THREAD

**Issue by 0x1x2** [sgtcaze/NametagEdit#132]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
version 4.1.3
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
git-Spigot-de459a2-51263e9 (1.10.2 latest)
### What plugins are you using? Type /plugins
ScoreboardHotfix, SimpleBroadcast, Languages, MythicLib, PlugMan, CustomPolls, Spartan, DeluxeTags, DupePatch, TabListEdit, VKAutoPickup, ChatControl, FastAsyncWorldEdit, Vouchers, PermissionsEx, FeatherBoard, mcMMO, Lores, PlaceholderAPI, VoidWorld, VKBackPack, NametagEdit, Lockette, MyItems, OldCombatMechanics, TitleAPI, MultiSkyWars, VoxelSniper, LightAPI, WorldEdit, OpenInv, PacketListenerApi, BuycraftX, Votifier, VPNGuard, FastAsyncRedstone, SQLibrary, CustomVillageTrades, Vault, PlayerPoints, ChestCommands, StaffPlus, MyWarp, MessageAnnouncer, Citizens, ProtocolSupport, ObsidianAuctions, PerWorldInventory, WorldGuard, AuctionHouse, ASkyBlock, Essentials, Autorank, SafeTrade, KitAdder, CS-CoreLib, EnjinMinecraftPlugin, RPGItems, NoFlyZone, ViaVersion, CommandNPC, QuickSell, BlockVersion, CompatNoCheatPlus, SilkSpawners, Multiverse-Core, ProtocolLib, Shopkeepers, ServerListPlus, MiniaturePets, ChestShop, EssentialsSpawn, HeadsPlugin, NoCheatPlus, LibsDisguises, eZProtector, HeavySpleef, Signs, CraftBook, Item2Chat, HolographicDisplays, PhatLoots, ServerSigns, ShopGUIPlus, pvparena, mcMMOAction, CrateReloaded, UltraCosmetics, HeadsInventory, ProtectionLib, PvPManager, MythicMobs, FurnitureLib, FurnitureMaker, MobStacker2, DiceFurniture, ProVotes, TokenEnchant, DeluxeChat, PrisonMines, EnchantmentBook, EBChance, Skript, SkStuff, skUtilities, skRayFall, SkQuery, Skellett, Umbaska, DailyBonus, LeaderHeads, ProQuests, ProQuests-Packages, BossShopPro, TrickyShops, ThirdCurrency, MysteryBoxes
### Please explain your issue?
When F1 is turned on, name tags don't disappear.
### How do you reproduce the issue?
Turn on F1. 
### Is there an error(s) in the console? Please use: https://pastebin.com
Nope

**Comment by sgtcaze** [comment]
This is not an inherent issue with the plugin, but rather an issue with the client. I believe they changed how nametags were displayed (even in F1) in later versions of Minecraft.
