### ISSUE TITLE
java.sql.SQLTransientConnectionException (PlayerLoader.java:33)

### ISSUE THREAD

**Issue by helptiger** [sgtcaze/NametagEdit#134]
NametagEdit version 4.1.3 (dev b59) with MySQL (nitrado hosting)
with paperspigot 1.11.2 

plugin is working but I have Console Errors
http://pastebin.com/menhWNa7

**Comment by sgtcaze** [comment]
Your database details are incorrect, the database is not online, or the firewall is preventing you from connecting.

**Comment by helptiger** [comment]
could be also a not closed connection
I have another plugin (MinePacks) with HikariCP without that error
