### ISSUE TITLE
PlayerName [VANISH]  in the Tablist

### ISSUE THREAD

**Issue by TKwSni** [sgtcaze/NametagEdit#135]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.3    http://ci.playmc.cc/job/NametagEdit/59/

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
CraftBukkit version git-Spigot-6de2fbc-16b5116 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
AntiCapsLock, HideStream, Skript, Multiverse-Core, PermissionsEx, DisableSpectator, PlaceholderAPI, NametagEdit, WorldEdit, Yamler, iDisguise, SQLibrary, Vault, LWC, Citizens, LogBlock, WorldGuard, Essentials, UltimateChat, Scavenger, EssentialsGeoIP, TitleManager, ProtocolLib, EssentialsSpawn, NoCheatPlus, LiteBans....

(all those plugins updated as of today)

### Please explain your issue?
Sometimes for unknown reasons, players see my nick in the tablist like MyName **[VANISH]** (the nick in white color and vanish in green) even when i'm not even vanished but, only they see me like that, If I check my tablist I see it normally. Sometimes its just 1 player others see it normally, and the way to fix it is to reload the plugin.... 

### How do you reproduce the issue?
I think its triggered when I go into spectator mode, but it never happens when I try to replicate it...
maybe its because i have all permissions with * in pex.

### Is there an error(s) in the console? Please use: https://pastebin.com
No.

**Comment by sgtcaze** [comment]
Do you belong to any scoreboard teams? Either a plugin has you added to a scoreboard (such as McMMO) or a plugin is unvanishing you.

If you are an entry in a scoreboard, despite if you are vanished, you will still show as an entry in that scoreboard (e.g. Sidebar).
