### ISSUE TITLE
My NameTagEdit Is Bugged.

### ISSUE THREAD

**Issue by Guicraft006** [sgtcaze/NametagEdit#136]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
2.4

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

1.8.6, 
### What plugins are you using? Type /plugins
I know that plugin is not working, along with NameTagEdit. Is MineResetLite.

### Please explain your issue?
It simply does not work the TAB nor the name above

### How do you reproduce the issue?
With MinerResetLite

### Is there an error(s) in the console? Please use: https://pastebin.com
No.
![screenshot_1](https://cloud.githubusercontent.com/assets/25644777/22751498/c0aa9e7c-ee1b-11e6-84b8-16eb1d09d388.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25644777/22751505/c63511a6-ee1b-11e6-9fa0-c4717277a5c4.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25644777/22751510/cafef5ee-ee1b-11e6-8ad5-95c7d7572ef2.png)

**Comment by sgtcaze** [comment]
Likely because you're using a scoreboard altering plugin. Have you tried without it? Also, the version of NametagEdit you are using is obsolete, and we no longer support it.
