### ISSUE TITLE
Tablist

### ISSUE THREAD

**Issue by Zooominq** [sgtcaze/NametagEdit#142]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.4

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
1.11.2-R0.1-Snapshot

### What plugins are you using? Type /plugins
CratesPlus,Worldedit,HubThat,ObbyBreaker,FactionFly,OldPVP,PermissionsEX,NametagEdit,Vault,StaffPlus,Coupons,LaggRemover,ProtocolLib,WorldGuard,NoCheatPlus,EssentialsSpawn,Kitadder,SilkSpawners
### Please explain your issue?
When ever i open tab it doesn't show the prefix. I do /nte reload and it shows for a split second and its gone.
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
This is clash seen when using NPC plugins and NametagEdit. Do you use human NPCs on your server?
