### ISSUE TITLE
Prefixes not working

### ISSUE THREAD

**Issue by GraphicsCard** [sgtcaze/NametagEdit#143]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
2.4
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
Spigot
### What plugins are you using? Type /plugins
NameTagEdit
### Please explain your issue?
It wont work  at all I try to do the ./nte prefix GraphicsDesign &4&lOwner It wont show anything But the config  says it is set for my name but just don't show
### How do you reproduce the issue?
No idea
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
Apologies, we do not support v2.4 anymore as this is a few years old. Please upgrade to 4.0+.
