### ISSUE TITLE
Unable to import latest version of NameTagEdit into workspace

### ISSUE THREAD

**Issue by Developer0fTruth** [sgtcaze/NametagEdit#144]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
Latest
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins
custom, vault
### Please explain your issue?
Unable to import into eclipse, There are methods missing an example, [The method getPrefix() is undefined for the type FakeTeam] I'm Assuming on a normal import that the plugin would work fine
### How do you reproduce the issue?
?? try importing with maven into eclipse
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
You need Lombok: https://projectlombok.org/download.html
We use this to simplify getters/setters/constructors
