### ISSUE TITLE
Multi-prefix/suffix Support?

### ISSUE THREAD

**Issue by birkhofflee** [sgtcaze/NametagEdit#145]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.14

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-6f7aabf-c8ff651 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Plugins (21): WorldEdit, HungerKeeperPlus, ClearLag, PermissionsEx, NametagEdit, BuycraftX, Vault, SilkSpawners, ProtocolLib, NoCheatPlus, ASkyBlock, ChestShop, LockettePro, ChestCommands, Essentials, EssentialsProtect, EssentialsAntiBuild, ChatEx, HolographicDisplays, ServerListPlus, EssentialsSpawn

### Please explain your issue?
Do you have or have a plan to implement the multi prefix/suffix feature? Like if a player is in both "Owner" and "Developer" group, ChatEx will have his chat prefix [Owner] [Developer].

### How do you reproduce the issue?
![2017-03-13_18 07 04](https://cloud.githubusercontent.com/assets/8148095/23849830/ff94a5b8-0817-11e7-9e76-290bae6d887e.png)

### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by JustOneMoreBlock** [comment]
Not at this time, we don't have any plans for it. However, sgtcaze can make the decision if wants to implement something like this.

**Comment by sgtcaze** [comment]
As Cory said we do not have plans for this. This should be done via API calls.
