### ISSUE TITLE
The first character of the player's name will disappear

### ISSUE THREAD

**Issue by birkhofflee** [sgtcaze/NametagEdit#146]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.14

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-6f7aabf-c8ff651 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Plugins (21): WorldEdit, HungerKeeperPlus, ClearLag, PermissionsEx, NametagEdit, BuycraftX, Vault, SilkSpawners, ProtocolLib, NoCheatPlus, ASkyBlock, ChestShop, LockettePro, ChestCommands, Essentials, EssentialsProtect, EssentialsAntiBuild, ChatEx, HolographicDisplays, ServerListPlus, EssentialsSpawn

### Please explain your issue?
For example, when I set a group's prefix to this(note that there's a space after the last `&7`): 
```
Prefix: '&8[&7Player&8]&7 '
```
Then the first character of the player's name will disappear.

### How do you reproduce the issue?
Said above.

### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by JustOneMoreBlock** [comment]
Hello,

With the color codes, text and space. This makes `prefix` 17 characters long.

```
Prefix: '&8[&7Player&8]&7 '
```

The Minecraft limitation is 16 characters and something we cannot change.

**Comment by birkhofflee** [comment]
Okay thanks
