### ISSUE TITLE
Help with NameTagEdit Prefix Commands & Menu.

### ISSUE THREAD

**Issue by BelleGoBelle** [sgtcaze/NametagEdit#147]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
Newest Version.
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
Spigot 1.11.2
### What plugins are you using? Type /plugins
ChairStairs,  GroupManager, StaffRanks, FatPort, WorldEdit, ElsweyrsHeads, Vault, Questioner, StopTnT, WorldGuard, SmartSpawn, ClearChat, Tablist, Broadcaster, MyMenu, SimplePets, PlaceHolderAPI, SimpleAPI, MarriageMaster, FirstJoinPlus, ProtocolLib, HolographicDisplays, Brewery, **NameTagEdit**, MobMoney, Essentials, Citizens, Towny, LibsDisguises, Morphy, ServerListPlus, CS-CoreLib, EnjinMinecraftPlugin, Magic, TownyNameUpdater, CommandNPC, TownyChat, and QuickMarket.
### Please explain your issue?
This is a Question. I am making a roleplay server, But I need my NPCs (Citizens) to be able to open the menu from my menu plugin. (MyMenu). When I put the command (/nte player <player> prefix <MyPrefix)  into the menu and if a player clicks the object, They cannot receive any of the Prefix. I have tried several other ways for the player name, Like '%player% and @p, But nothing seems to work. Is there some way I can fix this?
### How do you reproduce the issue?
Meaning, Is there a way I can make the command '/nte player <player> prefix <Prefix> be clicked on in the MyMenu plugin and the players be able to receive the Prefix?
### Is there an error(s) in the console? Please use: https://pastebin.com
No errors. Just confusion.

**Comment by JustOneMoreBlock** [comment]
Are you using `Essentials` at all? If so, you can try:

```
/sudo @p nte player prefix <MyPrefix>
```

Although, they might need the prefix permission, and this could make it vulnerable where if anyone knows they have that permission. They could make it anyway prefix.

**Comment by BelleGoBelle** [comment]
I tried the command, And I am Opped, it does not work.

Any other solutions...?

**Comment by sgtcaze** [comment]
Hmm, sounds like the menu you are working with should be the thing to parse out the proper command. I thought about implementing this just now, but it still won't work in the way you'd like. Plus it'd be inefficient to do this to every tag. Thoughts?
