### ISSUE TITLE
Question about groups of NameTagEdit

### ISSUE THREAD

**Issue by PulPac** [sgtcaze/NametagEdit#148]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
Last
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
1.8
### What plugins are you using? Type /plugins
Skript and addons of skript
### Please explain your issue?
So.. 
I would to do a group for order my tablist so..
How ????
And for op's ?
For order ?
Thanks for your attention.

**Comment by sgtcaze** [comment]
Apologies for the delay in response. Check this out for information on SortPriority vs Group Ordering: https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Configuration.creole
