### ISSUE TITLE
White nametags when sorting the Tablist

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#150]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.4 (Dev Build from Jenkins) #2)
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
Spigot (Hose), 1.10.2
### What plugins are you using? Type /plugins
https://www.dropbox.com/s/nvgkj0z06re23z2/Screenshot%202017-04-02%2020.04.38.png?dl=0
### Please explain your issue?
We are using a script, that looks up, which group, which prefixes and suffixes a player has to have.
At the end, it executes these commands:
```
if {-oldPrefix::%{_p}%} isn't {_Prefix}:
        execute console command "/ne player %{_p}% prefix %{_Prefix}%"
        wait 1 tick
        if {grouporder::%{group::%{_p}%}%} is set:
            execute console command "/ne player %{_p}% priority %{grouporder::%{group::%{_p}%}%}%"
            wait 1 tick
    if {-oldSuffix::%{_p}%} isn't {_Suffix}:
        execute console command "/ne player %{_p}% suffix %{_Suffix}%"
```
After it, most of the names in the tab list are white.
If I disable the sorting / priority function and delete everything from NametagEdit in the Database, it is working fine. Some months ago (with the official release) we tested sorting, but sometimes all players were kicked because of a string length error.
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by ghost** [comment]
Additional information:
Reproduce:

- Set Prio of player's Nametag
- /nte reload
- Set Prefix or Suffix of Player

**Comment by ghost** [comment]
Think it's only occurring with many players. Really weird.

**Comment by sgtcaze** [comment]
Peculiar! SortPriority has some issues at the moment with Groups - definitely. For players, each player should have a unique sort priority otherwise the plugin will try to repeatedly send the same team name for multiple players (this weird issues like this arise).

**Comment by ghost** [comment]
Ok, I understood, what you mean. Is the Bug fixed, that everyone gets kicked because of a string length error?

Von meinem iPhone gesendet

Am 09.04.2017 um 07:29 schrieb sgtcaze <notifications@github.com<mailto:notifications@github.com>>:


Peculiar! SortPriority has some issues at the moment with Groups - definitely. For players, each player should have a unique sort priority otherwise the plugin will try to repeatedly send the same team name for multiple players (this weird issues like this arise).

**Comment by ghost** [comment]
Hi,
I just tested the following now:

- give every server group a number between 1 and 16)
- give every player a unique priority number calculated by something like "random integer between GROUPNUMBER*1000 and (GROUPNUMBER*1000)+999 - so there is space for enough players
- then looping the players and send the command to NTE plugin.

Issues:
- Most of group's players are in A order, but not in the right.
- When changing the nametag, the regular issue with white name tags occurs.

**Comment by sgtcaze** [comment]
Super late on reply, but for anyone who reads this in the future: SortPriority was problematic in versions prior to 4.1.5/6. This issue should now be resolved. If it is not, and if anyone, including GermanMinerDE, want to reopen - please do so.
