### ISSUE TITLE
Nametag showing with invis effect

### ISSUE THREAD

**Issue by bybilly** [sgtcaze/NametagEdit#154]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.4
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
CraftBukkit version git-Spigot-d276ab1-d219213, Spigot 1.11.2 with protocalsupport
### What plugins are you using? Type /plugins
Not that important apart from kitbattle and pex 
### Please explain your issue?
Ghost kit, when invisible, nametag shows
### How do you reproduce the issue?
^
### Is there an error(s) in the console? Please use: https://pastebin.com
No errors

**Comment by sgtcaze** [comment]
Notice you're using ProtocolSupport. Is it the 1.8 clients that see the nametags? How about 1.9 vs 1.10 vs 1.11 clients? Last I saw this was an issue with 1.8 and below.

**Comment by bybilly** [comment]
Looks like all versions, after testing. We're only supporting 1.8 and above right now. :/

**Comment by sgtcaze** [comment]
I did several tests a few months back, forgot to follow up here. I was unable to combat this issue as this is a well known Minecraft caveat. There is a work around with ProtocolLib, but to keep NametagEdit standalone and minimize dependency, we didn't follow through with it.

Going to close this issue.
