### ISSUE TITLE
placeholders not updating automatically

### ISSUE THREAD

**Issue by comfysquirrel** [sgtcaze/NametagEdit#155]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
`4.1.2`
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
`git-Spigot-54ec0b8-7b044de (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`
### What plugins are you using? Type /plugins
`Plugins (49): PlaceholderAPI, PlugMan, NametagEdit, Voxelight-Place, LongCommands, BiomeTP, SimpleAPI, CoreProtect, dynmap, StaffPunch, Skript, Essentials, WorldBorder, AntiHackedPotions, SimplePets, ProtocolLib, FastAsyncWorldEdit, ImageOnMap, PermissionsEx, ATrailer, ServerListPlus, Vault, ChairStairs, Dynmap-Essentials, FastAsyncVoxelSniper, SimpleRename, PerWorldInventory, VoxelSniper, EssentialsSpawn, MyCommand, TitleManager, WorldEdit, BooksWithoutBorders, BannerMaker, Plan, PlotSquared, Marriage, WorldGuard, SimpleArmorStandEdit, WeatherMan, goBrush, Multiverse-Core, DiscordSRV, StayPut, Plot2Dynmap, goPaint, HeadsPlugin, HeadsInventory, EssentialsChat`
### Please explain your issue?

I am using the `%multiverse_world_alias%` placeholder in tab to show the player's current world.
![2017-04-26_19 07 24](https://cloud.githubusercontent.com/assets/6022168/25464936/13ad3baa-2ab4-11e7-9232-1446b548af71.png)

___
The issue is the world alias placeholder does not update when they change worlds, unless I do `/nte reload`. I wonder if this problem applies to all placeholders? (when they change, NTE doesn't show the change in tab)
___

I am using a Skript script as a workaround to run `/nte reload` each time a player changes worlds:
```
on teleport:
  wait 10 seconds
  execute console command "/nte reload"
```

### How do you reproduce the issue?
- Make sure [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) is installed and download the Multiverse extension (`/papi ecloud download Multiverse`)
- Use `%multiverse_world_alias%` somewhere in a prefix or suffix in the NTE groups.yml or players.yml file

### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
NametagEdit doesn't know when the placeholder plugins update the nametags.

Perhaps we could listen to this event, but it seems it might recur infinitely
https://github.com/Maximvdw/MVdWPlaceholderAPI/blob/master/src/main/java/be/maximvdw/placeholderapi/PlaceholderReplaceEvent.java

However I do not see one for ExtendedClip's API
https://www.spigotmc.org/wiki/hooking-into-placeholderapi/
