### ISSUE TITLE
Nametag Refresh

### ISSUE THREAD

**Issue by pinoylifecraft** [sgtcaze/NametagEdit#158]
NametagEdit 4.0.2
Spigot 1.11.2
Hello Guys ,

How to set the ticks of the nametags because example in "hub" world that has "nte.hub" permission then if that player go to "faction" world with the permission of "nte.faction" the nametags won't refresh still the "HUB" prefix and suffix in the "Faction" world :(

**Comment by sgtcaze** [comment]
Which Permissions plugin are you using?

I am thinking a "CheckPermissionOnWorldChange" config value or something along those lines as a *dirty* fix.

**Comment by pinoylifecraft** [comment]
Hello there @sgtcaze ,

I am currently using PermissionEX cuz it has a high performance and I'd never encounter any problem to this PermissionPlugin

Best Regards,
GM : MinecraftJohn
Pinoy LifeCraft GameMaster
