### ISSUE TITLE
Priority of ranks in tablist - Error

### ISSUE THREAD

**Issue by jona031q** [sgtcaze/NametagEdit#159]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
Im using 4.1.4
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
version 1.8.8-R0.1-SNAPSHOT
### What plugins are you using? Type /plugins
Lots of different plugins
### Please explain your issue?
The priority thing doesnt work. Iv'e set the rank owner to priority 1 and admin to priority 3, but i still shows the admin prefix in the tablist and yes, i have made a prefix for the Owner rank, and yes, i gave the Admin group the right permissions and the Owner group the right permissions.
### How do you reproduce the issue?
IDK
### Is there an error(s) in the console? Please use: https://pastebin.com
No errors

**Comment by sgtcaze** [comment]
Did you use the documentation here?
https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Configuration.creole

Also, MySQL or flatfile? Please post your config/database structure if possible. Also, make sure in your Players config/database you do not have conflicting Sort Priorities.

**Comment by sgtcaze** [comment]
No update in 15 days. Closing for now. If you continue to experience this please reopen.
