### ISSUE TITLE
Can't store "long" prefixes when using MySQL

### ISSUE THREAD

**Issue by birkhofflee** [sgtcaze/NametagEdit#160]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.4

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
git-Paper-1091 (MC: 1.11.2) 1.11.2-R0.1-SNAPSHOT

### What plugins are you using? Type /plugins
This shouldn't be affecting the problem.

### Please explain your issue?
I can't store "long" prefixes like `%luckperms_prefix ` when using MySQL support. It says:

```
UPDATE `nte_groups` SET `prefix` = '%luckperms_prefix% ' WHERE `nte_groups`.`name` = 'nametag'

#1406 - Data too long for column 'prefix' at row 1
```

### How do you reproduce the issue?
Go enable the SQL support, use `%luckperms_prefix ` as a group's prefix and you can see the problem.

### Is there an error(s) in the console? Please use: https://pastebin.com
https://pastebin.com/FsK8rNxH

**Comment by birkhofflee** [comment]
Dude you didn't even reply to the thread.

**Comment by sgtcaze** [comment]
Hi
