### ISSUE TITLE
nametag hook from PEX data.

### ISSUE THREAD

**Issue by WillPowerCraft** [sgtcaze/NametagEdit#162]
hello i searching very simple plugin what just hook and show players nametags from PEX database.

no tablist no custom cnfigurations. only hook and show nametags from PEX data.

how about that?

**Comment by sgtcaze** [comment]
You can try using the Placeholder code in NametagEdit if you don't want to use our plugin.

Then again the PlaceholderAPI would have to support PEX.

I am unaware of any other Nametag plugins that do this, I only work on NametagEdit with Cory.

**Comment by WillPowerCraft** [comment]
if ure put placeholder about prefix/suffix on players' nametag - that will be show YOUR prefix/suffix above ALL players haeds ahah.

**Comment by ghost** [comment]
how would one do such a thing?
