### ISSUE TITLE
PLEASE HOTFIX THAT players suffix/prefix override group suffix AND prefix

### ISSUE THREAD

**Issue by WillPowerCraft** [sgtcaze/NametagEdit#163]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.4
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
spigot 1.11.2 latest
### What plugins are you using? Type /plugins
do not metter
### Please explain your issue?
feature

what plugin do now:
0. setup groups and nte permissions
1. by default player have nametag: {group_prefix}{name}{group_suffix}
2. if change only player's suffix that break group_prefix.

example:
group: vip
perm: nte.vip
group prefix: '&9[VIP] '
group suffix: ''

player named Harune with perm: nte.vip will looks like: &9[VIP] Harune
## {group_prefix}{name}{group_suffix}

![image](https://cloud.githubusercontent.com/assets/23665302/26259179/6b42dcde-3cd0-11e7-80f2-59631c4d3390.png)

if put /nte player Harune suffix ' &2Funny'
## {name}{custom_suffix}

that change suffix AND PREFIX of player Harune and he will looks like: Harune &2Funny
![image](https://cloud.githubusercontent.com/assets/23665302/26259190/81847822-3cd0-11e7-8920-f8dae726d87f.png)

that not what ure waiting when doing that changes.

what i waiting after put group and put custom suffix to player:

## {group_prefix}{name}{custom_suffix}

![image](https://cloud.githubusercontent.com/assets/23665302/26259214/a4913bd4-3cd0-11e7-995f-55aea87f67b3.png)

so i want that changes of plugin:

if player have custom prefix - that override ONLY group prefix
if player have custom suffix - that override ONLY group suffix

### How do you reproduce the issue?
look above
### Is there an error(s) in the console? Please use: https://pastebin.com
nope. that is issue about change plugin mechanic

**Comment by sgtcaze** [comment]
What you're describing is a feature, not a bug. NametagEdit does not support pulling tags from groups AND player tags and combining them. 

To achieve what you want, the easiest thing you can do is:
1) Create a placeholder for either of the PlaceholderAPIs we support
2) Use the placeholder in the player nametag

We said a while back we wouldn't support cross nametags in this way, so placeholders are the way to go.

**Comment by WillPowerCraft** [comment]
im already using your plugin with runch mathod.
