### ISSUE TITLE
FIXED

### ISSUE THREAD

**Issue by TheKillHDmc** [sgtcaze/NametagEdit#164]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.4

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
PaperSpigot 1.8.8

### What plugins are you using? Type /plugins
https://i.gyazo.com/a0f406b676c1e13f64d7c4fa3487d783.png

### Please explain your issue?
I have issue with priority, it's random on my TAB ( sorry for yme english i speak french )
https://i.gyazo.com/e453fe3d0de43d3942a239edfa33153a.png
config : https://hastebin.com/itavofawuv.pas

### How do you reproduce the issue?
Any time

### Is there an error(s) in the console? Please use: https://pastebin.com
Nope

**Comment by sgtcaze** [comment]
Couldn't load the hastebin link. You must change the **SortPriority** in order to change the display in TAB. Make sure that no SortPriorities overlap! Players.yml and Groups.yml MUST have different SortPriorities otherwise they will clash.

**Comment by TheKillHDmc** [comment]
i know, the order is correct in groups.yml

I dont use player.yml

https://pastebin.com/LTHEFqBF

https://i.gyazo.com/3cefc675065eb08f1ada9f1144caeb91.png
