### ISSUE TITLE
Prefix is bugged

### ISSUE THREAD

**Issue by xHori** [sgtcaze/NametagEdit#165]
### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by xHori** [comment]
Version 4.1.4
Version 1.8 Spigot
http://imgur.com/a/CmAcu here is my plugins
When i make 2 groups ex Helper Player and set the prefixses.The prefix from player remains on helper in tab also above the player.I made a perm for each.idk why its happening

**Comment by sgtcaze** [comment]
Post your groups.yml please. This is likely a permission hierarchy issue.

**Comment by xHori** [comment]
http://imgur.com/a/QBYQf

**Comment by sgtcaze** [comment]
I apologize for not following up sooner. If you are still experiencing issues with our plugin, please reopen this issue or open a new one.
