### ISSUE TITLE
NameTagEdit and PermissionsEx

### ISSUE THREAD

**Issue by moogion** [sgtcaze/NametagEdit#166]
Help me with the rights.

After setting the rights when receiving the group above User then the prefix

http://prntscr.com/ffanvt

**Comment by moogion** [comment]
- [Pex:
`groups:
  User:
    permissions:
      - chatex.chat.global
      - chatex.allowchat
      - essentials.kit
      - essentials.kits.start
      - essentials.kits.bonus
      - essentials.balance
      - essentials.pay
      - essentials.book
      - essentials.book.author
      - essentials.book.title
      - essentials.compass
      - essentials.depth
      - essentials.getpos
      - essentials.helpop
      - essentials.ignore
      - essentials.info
      - essentials.motd
      - essentials.msg
      - essentials.recipe
      - essentials.rules
      - essentials.suicide
      - essentials.ping
      - essentials.spawn
      - essentials.delhome
      - essentials.home
      - essentials.home.bed
      - essentials.sethome
      - essentials.sethome.bed
      - essentials.tpa
      - essentials.tpdeny
      - essentials.tphere
      - essentials.warp
      - essentials.warp.list
      - headdb.allowBuy.*
      - headdb.open
      - essentials.gamemode.Survival
      - essentials.gamemode
      - nte.user
    options:
      default: true
      suffix: ''
      prefix: '&eИгрок'
  Fly:
    inheritance:
    - User
    permissions:
      - chatex.chat.color
      - chatex.chat.reset
      - essentials.fly
      - essentials.kits.fly
      - essentials.balance.others
      - essentials.msg.color
      - essentials.near
      - essentials.sethome.multiple.2
      - essentials.sethome.multiple
      - nte.fly
    options:
      suffix: ''
      prefix: '&aФлай'
  Vip:
    inheritance:
    - User
    - Fly
    permissions:
      - chatex.chat.magic
      - chatex.chat.strikethrough
      - chatex.chat.italic
      - essentials.feed
      - essentials.hat
      - essentials.kits.vip
      - essentials.workbench
      - essentials.book.others
      - essentials.msg.format
      - essentials.msg.magic
      - essentials.spawn.others
      - essentials.sethome.multiple.5
      - nte.vip
    options:
      suffix: ''
      prefix: '&bВип'
  VipPlus:
    inheritance:
    - User
    - Fly
    - Vip
    permissions:
    - essentials.enchant
    - essentials.god
    - essentials.repair
    - essentials.repair.armor
    - essentials.getpos.others
    - essentials.enderchest
    - essentials.back
    - essentials.keepxp
    - essentials.sethome.multiple.10
    - nte.vipplus
    options:
      suffix: ''
      prefix: '&bВип &a+'` ] 

- [Group:
`Groups:
  User:
    Permission: nte.User
    Prefix: '&7[&e&l✰&7]&9'
    Suffix: ''
    SortPriority: 16
  Fly:
    Permission: nte.Fly
    Prefix: '&7[&aФ&7]&9'
    Suffix: ''
    SortPriority: 15
  Vip:
    Permission: nte.Vip
    Prefix: '&7[&bВ&7]&9'
    Suffix: ''
    SortPriority: 14
  VipPlus:
    Permission: nte.VipPlus
    Prefix: '&7[&bВ &a+&7]&9'
    Suffix: ''
    SortPriority: 13
  Premium:
    Permission: nte.Premium
    Prefix: '&7[&6П&7]&9'
    Suffix: ''
    SortPriority: 12
  Creative:
    Permission: nte.Creative
    Prefix: '&7[&dК&7]&9'
    Suffix: ''
    SortPriority: 11
  Admin:
    Permission: nte.Admin
    Prefix: '&7[&eА&7]&9'
    Suffix: ''
    SortPriority: 10
  AdminPlus:
    Permission: nte.AdminPlus
    Prefix: '&7[&eА &a+&7]&9'
    Suffix: ''
    SortPriority: 9
  Moder:
    Permission: nte.Moder
    Prefix: '&7[&bМ&7]&9'
    Suffix: ''
    SortPriority: 8
  Lord:
    Permission: nte.Lord
    Prefix: '&7[&6Л&7]&9'
    Suffix: ''
    SortPriority: 7
  King:
    Permission: nte.King
    Prefix: '&7[&aЦ&7]&9'
    Suffix: ''
    SortPriority: 6
  YouTuber:
    Permission: nte.YouTuber
    Prefix: '&7[&fY&cT&7]&9'
    Suffix: ''
    SortPriority: 5
  AntiGrifer:
    Permission: nte.AntiGrifer
    Prefix: '&7[&aА&7-&bГ&7]&9'
    Suffix: ''
    SortPriority: 4
  Consel:
    Permission: nte.Consel
    Prefix: '&7[&cК&7]&9'
    Suffix: ''
    SortPriority: 3
  Personal:
    Permission: nte.Personal
    Prefix: '&7[&cП&7]&9'
    Suffix: ''
    SortPriority: 2
  Owner:
    Permission: nte.Owner
    Prefix: '&7[&cO&7]&9'
    Suffix: ''
    SortPriority: 1` ]

**Comment by MrSkoper** [comment]
Group:
`Groups:
  User:
    Permission: nte.User
    Prefix: '&7[&e&l✰&7]&9'
    Suffix: ''
    SortPriority: 16
  Fly:
    Permission: nte.Fly
    Prefix: '&7[&aФ&7]&9'
    Suffix: ''
    SortPriority: 15
  Vip:
    Permission: nte.Vip
    Prefix: '&7[&bВ&7]&9'
    Suffix: ''
    SortPriority: 14
  VipPlus:
    Permission: nte.VipPlus
    Prefix: '&7[&bВ &a+&7]&9'
    Suffix: ''
    SortPriority: 13
  Premium:
    Permission: nte.Premium
    Prefix: '&7[&6П&7]&9'
    Suffix: ''
    SortPriority: 12
  Creative:
    Permission: nte.Creative
    Prefix: '&7[&dК&7]&9'
    Suffix: ''
    SortPriority: 11
  Admin:
    Permission: nte.Admin
    Prefix: '&7[&eА&7]&9'
    Suffix: ''
    SortPriority: 10
  AdminPlus:
    Permission: nte.AdminPlus
    Prefix: '&7[&eА &a+&7]&9'
    Suffix: ''
    SortPriority: 9
  Moder:
    Permission: nte.Moder
    Prefix: '&7[&bМ&7]&9'
    Suffix: ''
    SortPriority: 8
  Lord:
    Permission: nte.Lord
    Prefix: '&7[&6Л&7]&9'
    Suffix: ''
    SortPriority: 7
  King:
    Permission: nte.King
    Prefix: '&7[&aЦ&7]&9'
    Suffix: ''
    SortPriority: 6
  YouTuber:
    Permission: nte.YouTuber
    Prefix: '&7[&fY&cT&7]&9'
    Suffix: ''
    SortPriority: 5
  AntiGrifer:
    Permission: nte.AntiGrifer
    Prefix: '&7[&aА&7-&bГ&7]&9'
    Suffix: ''
    SortPriority: 4
  Consel:
    Permission: nte.Consel
    Prefix: '&7[&cК&7]&9'
    Suffix: ''
    SortPriority: 3
  Personal:
    Permission: nte.Personal
    Prefix: '&7[&cП&7]&9'
    Suffix: ''
    SortPriority: 2
  Owner:
    Permission: nte.Owner
    Prefix: '&7[&cO&7]&9'
    Suffix: ''
    SortPriority: 1`

**Comment by sgtcaze** [comment]
Apologies for the late reply, are you still experiencing this issue?

**Comment by sgtcaze** [comment]
No reply in 17 days. If you still require help we are ready to help. Just let us know when.
