### ISSUE TITLE
Prefixes assigned to wrong groups.

### ISSUE THREAD

**Issue by HeyItsBluee** [sgtcaze/NametagEdit#167]
### What version/build of NametagEdit are you using? Type /ver NametagEdit 
4.0.2

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver 
1.8

### What plugins are you using? Type /plugins 
AdvancedBan, ArchonCrates, ChatEx, ClearLagg, CustomPermissionMessages, EssentialsX, EssentialsChat, Essentials, Factions, MassiveCore, Multiverse-Core, PermissionsEx, PlugMan, ProtocolLib, PunishmentGUI, Vault, VoidGenerator, WorldEdit, WorldGuard

### Please explain your issue? 
If a player is set to either the Developer, Manager, or Staff group, they receive the Owner prefix. If a player is set to the YouTuber group, they receive the Admin prefix. If a player is set to the Builder group, they receive the Moderator prefix. I feel that this must be an issue with PermissionsEx.

### How do you reproduce the issue? 
I set my "test subject" to a certain group and the issue will continue.

### Is there an error(s) in the console? Please use: https://pastebin.com 
Not that I'm seeing.

**Comment by sgtcaze** [comment]
Make sure you set group hierarchy with /nte order. This is either a permission inheritance issue, or a group order issue.

**Comment by HeyItsBluee** [comment]
How does that feature work? I've been trying to use it by typing "/nte group order Owner Manager CManager Admin SrMod Mod Staff Developer Builder Helper YouTuber" but it isn't working. When I type that nothing happens. No errors, no messages, nothing. I'm most likely doing something wrong, I just don't know what it is.

**Comment by sgtcaze** [comment]
Order and Priority are a little confusing at first, but here's what they do:

**Order** deals with the permission hierarchy. You should order these from top permission to lowest permission (e.g. Owner -> Admin -> Donor -> Default). This helps make sure players get the right nametag for their group.

**Priority** indicates the position in the tab list for any given nametag. So Owner could always display as 1st in the tab list (top left) and you can guarantee a "less important" rank will display in the lower right hand side.

You are correct that you do not get a confirmation message. I've just checked the code, and the FlatFileConfig does not have a confirmation. I will add this.

**Comment by sgtcaze** [comment]
No update in 13 days. If you still require help, let us know. Hope your issue is resolved.
