### ISSUE TITLE
database groups not working

### ISSUE THREAD

**Issue by PhanaticD** [sgtcaze/NametagEdit#17]
Nametags do not work at all with mysql mode for groups, no output or errors or nametags

I also got this error when trying to import groups to database
http://pastebin.com/FvELcPMQ

**Comment by JustOneMoreBlock** [comment]
Did you configure your config.yml in NametagEdit?

@sgtcaze Might need to add in a check or something to see if it's filled out or test the connection.

**Comment by PhanaticD** [comment]
yes the database was configured correctly and I did check the tables were made and data was put in but no nametags in game when I used the commands to make a group

works perfectly fine without mysql though

**Comment by JustOneMoreBlock** [comment]
Can you post your config.yml with your username/database/password removed?
Provide your groups.yml, players.yml
- Minecraft Version (CraftBukkit 1.8.x, Spigot 1.8.x, and so on...)
- What NametagEdit Build? (Don't say latest, need to know the actual build.)
- List of plugins?

**Comment by PhanaticD** [comment]
CraftBukkit version git-PaperSpigot-440 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

nametagedit 23

Plugins (33): AsyncWorldEditInjector, CleanroomGenerator, dynmap, DoubleJump4NCP, WorldEdit, CommandHelper, NametagEdit, ProtocolLib, WorldGuard, BungeePortals, FilterPwned, AsyncWorldEdit, EnderBlack, VoxelSniper, Cookbook, PermissionsEx, Microblocks, BlockAlias, HideStream, FixDoubleLogins, ChestShop, Essentials, EssentialsSpawn, ArmorStandTools, PwnFilter, PlotSquared, Multiverse-Core, Shopkeepers, CodelanxLib, Vault, AreaShop, SignShop, Shop

groups.yml http://pastebin.com/je65dbw2

players.yml Players: {}

config.yml http://pastebin.com/E2ecYicy

**Comment by sgtcaze** [comment]
Fixed in the commit above. See builds #27 and above @PhanaticD 
http://ci.playmc.cc/job/NametagEdit/27/
