### ISSUE TITLE
A way to define Table names

### ISSUE THREAD

**Issue by ShezzUr** [sgtcaze/NametagEdit#170]
I would like to request that you can name your tables for a Database OR at least define what server the Name Tags are allowed on, For if you have a Towny or a SkyBlock Server I would like to use different Prefix/suffix.

So at the moment this is what the Config has
# If enabled, NametagEdit will use database support
MySQL:
  Enabled: true
  Hostname: 192.168.0.3
  Port: 3306
  Username: ***
  Password: ***
  Database: ***

What I would like is to define table names like nte_towny & nte_skyblock so it's server specific or make it so we can use one table and in the config you can set the server like Server = 'Towny' or Server = 'SkyBlock' so in the Database it's got a column called Server.

and if the database is enabled,
Would it be possible to add when the command to set a prefix/sufix for a user, it sets the Time/Date in the table so we can monitor when people's prefix/sufix was last updated? Thanks in advance

**Comment by sgtcaze** [comment]
Cool idea. Added in the newest commit.
