### ISSUE TITLE
Prefixes not working at all in Tab List

### ISSUE THREAD

**Issue by Aubble** [sgtcaze/NametagEdit#172]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.4
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) Checking version, please wait... You are 56 version(s) behind
### What plugins are you using? Type /plugins
CoreProtect, PermissionsEx, WorldEdit, iDisguise, NametagEdit, Essentials, EssentialsSpawn, Worldguard
### Please explain your issue?
I can't get any prefixes to appear in the tab list. It may have something to do with PEX but I'm not sure what. Debug doesn't show anything wrong.
### How do you reproduce the issue?
PEX group called "Owner" with the prefix "&c&lO&6&lW&e&lN&a&lE&9&lR &r" (Rainbow letters OWNER)

NTE Group called "Owner" with the same prefix, permission called "nte.owner".

/reload
/nte reload

It just shows my red admin-colored username.
### Is there an error(s) in the console? Please use: https://pastebin.com
There aren't any errors. This is what it says when I reload:
[21:37:25 INFO]: ╗ Successfully reloaded plugin data
[21:37:26 INFO]: ╗ Empty teams: 0. Purge: true.
[21:37:26 INFO]: [NametagEdit] [DEBUG] Created FakeTeam CCABE4. Size: 1
[21:37:26 INFO]: [NametagEdit] [DEBUG] Aubble has been added to team CCABE4
[21:37:26 INFO]: [NametagEdit] [DEBUG] Applying GroupTag 'Owner' to Aubble
[21:37:26 INFO]: [NametagEdit] [DEBUG] Applied tags to all online players.

**Comment by Aubble** [comment]
Since I'm the only one on my private server I used a hack client to freecam to see my own usertag above my head, and the prefix was kinda messed up, probably due to the excessive color codes. I changed it to just a red "OWNER" prefix and it works for the usertag but still not for the tab list.

**Comment by Aubble** [comment]
Update: I have solved my own problem. I needed to change a few global settings in Essentials.

**Comment by sgtcaze** [comment]
Glad you solved your problem.
