### ISSUE TITLE
Suffix bug

### ISSUE THREAD

**Issue by AnonymousPerson103** [sgtcaze/NametagEdit#173]
### Is there an error(s) in the console? Please use: https://pastebin.com Nope

**Comment by AnonymousPerson103** [comment]
Anyone

**Comment by sgtcaze** [comment]
Player tags and Group tags are different. If you set a prefix for a player using
/nte player <name> prefix [Tag]

Then NametagEdit will create a unique nametag just for that player, and not consider any other groups. If you require more complex functionality, we added PlaceHolderAPI support from 2 plugins.

Basically, you must edit either the group or player tag separately, but not both. They are kept separate on purpose.

**Comment by AnonymousPerson103** [comment]
So how would I make this work for a prison server if I want their donor rank as a prefix and the rankup as the suffix?

**Comment by sgtcaze** [comment]
For each of your Prison ranks, is there a permission group specifically for it? If so, if your permissions plugin supports placeholders, you can place that in the Prefix/Suffix, and it will work as you need (need to have 1 or both of the APIs we support).

You can also create your own Placeholder for either plugin if one doesn't exist already.

If that doesn't work, you can use NametagEdit's API to accomplish this.

**Comment by AnonymousPerson103** [comment]
Alright; thanks :)
