### ISSUE TITLE
Bug sql

### ISSUE THREAD

**Issue by mathis-kdio** [sgtcaze/NametagEdit#175]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.1.6

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

1.12

**What plugins are you using? Type /plugins**

PermissionsEx, Multiworld, ViaVersion, NametagEdit, EssentialsSpawn, GriefPrevention, Essentials, EssentialsSpawn, EssentialsChat

**Please explain your issue. How do you trigger it?**

I can't use Sql with Nametagedit. When I do / nte convert file db true I get an error message and I have an error in the logs.

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/V3aJAPTj

**Comment by sgtcaze** [comment]
Ah, it appears you tried to import the data multiple times. I will make the query handle one at a time, and make it notify you of duplicates.

**Comment by sgtcaze** [comment]
Never mind, this was a failure in the query structure. An update is being pushed now.

See commit: https://github.com/sgtcaze/NametagEdit/commit/7a8f78ae61d8b505fb4173c8843f1e6c1a290475
