### ISSUE TITLE
Error typing command  /nte reload 

### ISSUE THREAD

**Issue by DarkFort** [sgtcaze/NametagEdit#176]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.1.6

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
git-Paper-1134 (MC: 1.12)

**Please explain your issue. How do you trigger it?**
Error typing command /nte reload

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/Wj2yF6yL

**Comment by sgtcaze** [comment]
Looks like the first instance of a concurrency issue as a direct result of https://github.com/sgtcaze/NametagEdit/commit/dc7cb721f241070662651d5f02b426f03a60a6d7

There will be an update soon.

**Comment by sgtcaze** [comment]
Please try version 4.1.7 available on the Jenkins build server. This should resolve the issue. If not, please reopen this issue.
