### ISSUE TITLE
Unlimited prefixes and suffixes

### ISSUE THREAD

**Issue by DarkFort** [sgtcaze/NametagEdit#180]
Please add the ability to set unlimited prefixes and suffixes, this is in the plugin BungeeTabListPlus. Setting prefixes and suffixes occurs in nickname, and nicknames have unlimited number of characters in the tab.

**Comment by sgtcaze** [comment]
I haven't found any feature described in BungeeTabListPlus that permits unlimited Prefix/Suffix length. 48 characters is the max amount of characters a nametag can be. I believe the client crashes in all cases where the length is longer than expected.

Could you provide an example screenshot/link?

**Comment by DarkFort** [comment]
http://i.imgur.com/WCYvrHr.jpg

**Comment by dieterblancke** [comment]
That is Player#setPlayerListName(String name), which can be longer then a team prefix/suffix.
This can be closed I think :p

**Comment by sgtcaze** [comment]
Super late, but thanks @didjee2 for clarifying. I want to add that this feature cannot be implemented due to NametagEdit using the PacketPlayOutScoreboardTeam directly, rather than using the PlayerListName.
