### ISSUE TITLE
Invisibility

### ISSUE THREAD

**Issue by R3dThunderr** [sgtcaze/NametagEdit#182]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
CraftBukkit version git-Spigot-db6de12-18fbb24 <MC: 1.8.8> <Implementing API version 1.8.8-R0.1-SNAPSHOT>

**What plugins are you using? Type /plugins**
NoCheatPlus, LuckPerms, AdvancedBan, WorldEdit, NametagEdit, SidebarAPI, and a custom one by myself (does not touch nametags)

**Please explain your issue. How do you trigger it?**
When the player has invisibility, the nametag doesn't disappear.

**Are there any errors in the console? Please use: https://pastebin.com**
No

**Comment by sgtcaze** [comment]
Not fixable on our end. It's a minecraft bug. See:

https://github.com/sgtcaze/NametagEdit/issues/107
https://github.com/sgtcaze/NametagEdit/issues/106
https://github.com/sgtcaze/NametagEdit/issues/61
https://github.com/sgtcaze/NametagEdit/issues/37
https://github.com/sgtcaze/NametagEdit/issues/14
https://github.com/sgtcaze/NametagEdit/issues/5

**Comment by R3dThunderr** [comment]
Ok, my apologies for repeating the same thing as you've already seen.

Thanks :)
