### ISSUE TITLE
Issue when using name tags on parrots

### ISSUE THREAD

**Issue by dRoseMirakel** [sgtcaze/NametagEdit#189]
# Bug Report

NametagEdit V 4.1.7

CB version git-Spigot-99c2a37-4670a84

ItemInfo, GroupManager, TuxTwoLib, NameTagEdit, CoreProtect, Dynmap, Wild, WorldEdit, Essentials_warpGUI,  ClearLag, WorldBorder, Votifier, Multiverse-Core, ProtocolLib, Tools, mcMMO, McMMORewards, enchantmenu, Vault, BKCommonLib, SignLink, EpicRename, HolographicDisplays, WorldGuard, Vote, PhatLoots, CratesPlus, Oreobfuscator4, Essentials, HeadsPlugin, HeadsSweeper, SilkSpawners, McMMOExtras, NoCheatPlus, ChopTree4, SilkSpawnersEcoAddon, Train_Carts, EssentialsChat, BuyRegion, EnjinMinecraftPlugin, ChestShop, QuickShop, HeadsInventory, Essentials_KitHUI, MythicMobs, EssentialsProtect, Dynmap-Towny, EssentialsSpawn, Statz, Autorank, Jobs. Towny, ItemInfo. Dynmap

**Please explain your issue. How do you trigger it?**
When a player comes near parrot, the prefix of a parrot wil have the same as player prefix above the name

**Are there any errors in the console? Please use: https://pastebin.com**

there are no errors in the console nor chat

**Comment by sgtcaze** [comment]
Sorry for the late reply, was on vacation. This sounds like a Minecraft bug. Is it still happening?
