### ISSUE TITLE
Lag on my server whit player Join Event

### ISSUE THREAD

**Issue by ImMarvolo** [sgtcaze/NametagEdit#192]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running CraftBukkit version git-Spigot-f94fe8f-d27e6d0 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
Lobbies, NoHunger, WorldEdit, PlaceholderAPI, SpawnJoin, WorldBorder, Chat, NametagEdit, Multiverse-Core, WorldGuard, SkinsRestorer, MuteChat, IPWhitelist, PermissionsEx, NoWeather, FeatherBoard, MicroJump, ViaVersion, Vault, TitleManager, ArmorStandTools, MenuLobbies, Fe, ProtocolLib, Citizens, ChestCommands, CommandNPC, MessageFilter, HolographicDisplays

**Please explain your issue. How do you trigger it?**
On join tree players ping elevate to 999 and lag for players online on the servr.

**Are there any errors in the console? Please use: https://pastebin.com**

Nop

**Comment by sgtcaze** [comment]
http://ci.nametagedit.com/job/NametagEdit/21/

That build should fix this issue.
