### ISSUE TITLE
Tags!

### ISSUE THREAD

**Issue by Gaeta** [sgtcaze/NametagEdit#193]
# Bug Report

**Latest**

**spigot**

**I Do not want to tell**

**So i make it So The Tag For Default is [Starter] it has a perm nte.default and everything up ex: Trainee Helper Mod Owner Dev M-Owner And ETC.. and it shows Default For everyone!**

** https://pastebin.com/BwEX5cwc **
Please Tell me how to fix **ASAP**!!

**Comment by sgtcaze** [comment]
See the README for this issue: https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Configuration.creole

Your issue is one of misconfiguration and not an inherent flaw of the plugin.
