### ISSUE TITLE
Permission doenst work for '*' permission

### ISSUE THREAD

**Issue by JayTheLordOfTheFishes** [sgtcaze/NametagEdit#194]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.1.7
Authors sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Spigot 1.8.8

**What plugins are you using? Type /plugins**
Sorry but this is private

**Please explain your issue. How do you trigger it?**
Every Group i created  works perfect and as expected, but the ONLY group that doesnt work is the "Owner" group because it got '*'
I gave that permission to another group and it worked perfect, so the TRIGGER is the '*'
How do i fix this?

**Are there any errors in the console? Please use: https://pastebin.com**
No Erros for this PLugin spotted

**Comment by sgtcaze** [comment]
The plugin must have a permission assigned to a user, otherwise we get weird behavior. This is intended, and only requires that you keep a permission structure (see: "Order" in our configuration)
