### ISSUE TITLE
PlaceholderAPI Support

### ISSUE THREAD

**Issue by NyanMeow** [sgtcaze/NametagEdit#198]
This is a suggestion:
PlaceholderAPI is a good API on the server, but your plugin does not support it, so I hope to support PlaceholderAPI, so get a lot of convenience can be used in PlaceholderAPI plugin.
Thanks

**Comment by sgtcaze** [comment]
NametagEdit supports 2 popular placeholder plugins. [See the code here](https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/NametagHandler.java#L278-L299). It'll work via the API or configuration (either mySQL/flatfile).

**Comment by NyanMeow** [comment]
Please tell me the placeholders,thanks

**Comment by EvilPVP** [comment]
This plugin does indeed support PlaceholderAPI as it states in the code (“PlaceholderAPI”)
