### ISSUE TITLE
Problem with tags

### ISSUE THREAD

**Issue by m0uka** [sgtcaze/NametagEdit#199]
# Bug Report

**Type /ver NametagEdit and post the output.**

[Sat, 30. Sep 2017 10:28:24 CEST INFO] NametagEdit version 4.1.7
[Sat, 30. Sep 2017 10:28:24 CEST INFO] Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

[Sat, 30. Sep 2017 10:28:12 CEST INFO] This server is running CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
[Sat, 30. Sep 2017 10:28:12 CEST INFO] You are 5 version(s) behind

**What plugins are you using? Type /plugins**

AttackSpeedRemover, PerWorldPlugins, PlugMan, BetterChairs, NametagEdit, ConsoleSpamFix, asCMD, DeluxeTags, SuperTrails, ChatColor, TopLite, CoreProtect, LuckPerms, WorldEdit, PacketListenerApi, ClearLag, AutoMessage, BuycraftX, MapManager, Votifier, DeathMessagesPrime, Reports, SuperbVote, CS-CoreLib, CustomHelp, AntiBotAttack, Vault, FakaHedaMinequery, ColoredAnvils, MassiveCore, AnimatedFrames, PerWorldInventory, CreativeGates, LWC, WorldGuard, AuctionHouse, ASkyBlock, ChestCommands, Slimefun, ViaVersion, ViaBackwards, Essentials, Jobs, SilkSpawners, ProtocolLib, Multiverse-Core, NoCheatPlus, Citizens, DiscordSRV, Residence, EssentialsChat, ExoticGarden, CraftBook, MineResetLite, AntiSwear, ServerListPlus, SavageDeathChest, ChestShop, ArmorStandTools, MobArena, HolographicDisplays, CitizensCMD, SkinsRestorer, EssentialsSpawn, ShopGUIPlus, TitleManager, CrateReloaded, AuthMe, ProtectionLib, LimitedCreative, LiteBans, FurnitureLib, DiceFurniture

**Please explain your issue. How do you trigger it?**

Sometimes when someone joins, the tab prefix isnt visible. It is just white name without prefix, anything. But when i type /nte reload, its visible.

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/ndXBaee5

**Comment by sgtcaze** [comment]
This is a known incompatibility between NametagEdit and Essentials. We haven't been able to implement a proper fix yet (mainly due to it being messy).

Seems related to: https://github.com/sgtcaze/NametagEdit/issues/187

**Comment by JustOneMoreBlock** [comment]
Because of #187 this will be a dupe and closed.
