### ISSUE TITLE
[Feature] Optional prefix/suffix from Vault

### ISSUE THREAD

**Issue by Wundero** [sgtcaze/NametagEdit#20]
Vault offers support for getting the chat prefix and suffix for a player with their API, and adding this would make it easier for servers to maintain a consistent design for their prefixes and suffixes. This could be toggleable in the config file, and would work with any Vault supported permission plugins.

I would fork this repo and code it myself, but I don't have enough time or knowledge in Java (Getting there, but dealing with NMS code and reflection is a bit of a pain) to make it. 

Just a suggestion, however, but it would be nice to have this as to make permissions plugins work with nametags.

**Comment by sgtcaze** [comment]
Added to the list that can be found here

https://github.com/sgtcaze/NametagEdit/blob/master/ToDo.creole
