### ISSUE TITLE
Tab-list problem

### ISSUE THREAD

**Issue by NyanMeow** [sgtcaze/NametagEdit#200]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running Paper version git-TacoSpigot-"1a0d11cc" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
Plugins (39): ActionAnnouncer, AntiWither, AT, AuctionHouse, BetterChairs, ChestCommands, Citizens, CoreProtect, DeathMessagesPrime, EpicWorldGenerator, Essentials, EssentialsChat, EssentialsSpawn, GrItemTags, GroupManager, HolographicDisplays, ImageOnMap, IronElevators, LockettePro, MarriageMaster, MoreFish, Multiverse-Core, NametagEdit, NoBoom, NoMine, Orebfuscator4, PlaceholderAPI, PlayerHeads, ProtocolLib, QuickBoard, QuickShop, Residence, ScriptBlock, Thirst, Vault, ViaBackwards, ViaVersion, VoxelSniper, WorldEdit

**Please explain your issue. How do you trigger it?**
I closed the Tab-list display in the config file, but in fact it was not closed

https://miao.su/images/2017/10/14/QQ201710140748459aaf1.png
https://miao.su/images/2017/10/14/QQ2017101407510030035.png

**Are there any errors in the console? Please use: https://pastebin.com**
None

**Comment by sgtcaze** [comment]
NametagEdit appears to be overriding the TabList, even with formatting disabled.

Do you want the nametags in the TabList to be white? Or will another plugin handle the TabList?

**Comment by NyanMeow** [comment]
Show the white name in Tab-list

**Comment by sgtcaze** [comment]
A new config option has been added: OverrideColor. You have a choice how to format the TabList, either with a solid color &f or with a space " ", or whichever you like. Is this what you wanted?

[This is the link to build.](http://ci.nametagedit.com/job/NametagEdit/22/)

**Comment by NyanMeow** [comment]
I just tried, and Tab-list didn't change and if it works, I like it very much

**Comment by sgtcaze** [comment]
Hi, just testing a few things at the moment. You want white names in the tab. Does your config have the new setting? Make sure it looks something like this:

```
TabListDisabled: true

OverrideColor: "&f"
```

If it still doesn't work, maybe another plugin is overriding. We will fix this :D

**Comment by NyanMeow** [comment]
yes and in Tab-list, don't show the prefix / suffix only display name
