### ISSUE TITLE
Would be more than one prefix or suffix feature added?

### ISSUE THREAD

**Issue by KIKONUTINO** [sgtcaze/NametagEdit#204]
# Bug Report

**Type /ver NametagEdit and post the output.**

 NametagEdit version 4.1.3

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
(Implementing API version 1.8.8-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**

Plugins (36): AsyncWorldEditInjector, CoreProtect, WorldEdit, Essentials, ClearLag, TuxTwoLib, SurvivalGames, WorldBorder, NametagEdit, BuycraftX, WorldGuard, NoCheatPlus, SkinsRestorer, AsyncWorldEdit, CustomServerMessages, AntiBotUltra, TopTenHeads, PermissionsEx, TreeAssist, ViaVersion, Vault, EssentialsSpawn, PvPManager, Eggwars, MultiInv, Skywars, PlotMe, ASkyBlock, ChatEx, Statz, PlotMe-DefaultGenerator, Autorank, Multiverse-Core, MineResetLite, Multiverse-Portals, AuthMe

**Please explain your issue. How do you trigger it?**

Okay So I was searching for a plugin that had it all (various prefixes support, tab priority support and tag support) But didn't find one that matched my requeriments. So I started searching for various plugins that combining them would make the task. So I went for ChatEx and NameTagEdit, so now I can combine various prefixes like [TopKiller][Vip][Veteran]Kikonutino:. But the problem now is that on the tab there appears sometimes TopKiller and other times Vip and other times Veteran... Never the three at the same time. Is there some way to do that? And also to have priority on prefixes so my players always get the same order and to make the chat more structurated something like: [PrefixesForKills][PrefixesForRanks][PrefixesForTimePlayed] NameOfThePlayer:. Is there any possibility to get on the tab all the prefixes and on the tag too? Would you be able to do something to fix it? I'm sure you can, that's an awesome plugin and I don't want to start using another ones, if you are not going to make that, just keep it in mind for future versions please!.

Thanks for your time!! :D

**Are there any errors in the console? Please use: https://pastebin.com**

Nope. 0 Errors.

**Comment by sgtcaze** [comment]
Apologies for the late reply. Unfortunately multiple prefixes combined with NametagEdit's default functionality will very quickly reach the max allowed string length for the fake scoreboard teams. PlayerListName does not have this restriction in later versions of MC, but if I recall correctly, it had a different effect on the NamePlate vs TabList name. I've added this to the TODO, and if my tests work I will use that to replace the current functionality (version dependent).
