### ISSUE TITLE
Name getting cut off

### ISSUE THREAD

**Issue by Wereld** [sgtcaze/NametagEdit#205]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.1.7 NametagEdit

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.10.2 Spigot

**What plugins are you using? Type /plugins**
NoCheatPlus, TitleAPI, IPWhitelist, VanishNoPacket, PlaceholderAPI,
DeluxeMenus, PermissionsEx, ConditionalCommands, Swipeo (Custom), ViaVersion, NametagEdit, ViaBackwards, EzQueueSpigot, Multiverse-core

**Please explain your issue. How do you trigger it?**
If i want to make like a tab prefix MT Staff | NAME it cuts it off!
Its very annoying since other big servers can do this!
So its like MT Staff | lapen and it must me Slapen and not lapen

**Are there any errors in the console? Please use: https://pastebin.com**
No there are no errors.

**Comment by sgtcaze** [comment]
This is not a bug. NametagEdit's default functionality utilizes the ScoreboardTeamObjective packets which limit the character length to 16. You are referring to the functionality of PlayerListName, which to my knowledge in 1.8 is permitted to be much longer. This current functionality is actually a remnant of NametagEdits days prior to 1.7, where altering the PlayerListName wouldn't allow for 48 character names (prefix + username + suffix), and result in the name being cut off.

Edit: I'll add this to the TODO in-case to see if we should switch to PlayerListName instead for later versions of MC.
