### ISSUE TITLE
Problem timings when the event PlayerJoin is called

### ISSUE THREAD

**Issue by Kalorte** [sgtcaze/NametagEdit#21]
Hi !

When a made a timings of my server, I have a high value of the JoinEvent:

http://puu.sh/dvzUX/fc1c455d7f.png

My server:
http://puu.sh/dvzYA/f71fd4becf.png

If you want, I send you all my timings in MP

**Comment by sgtcaze** [comment]
Server looks like it's lagging for a lot of resons. Please respond if you still need help.
