### ISSUE TITLE
LuckPerms

### ISSUE THREAD

**Issue by DarkFort** [sgtcaze/NametagEdit#210]
I was at the PermissionEx plugin, when changing the group, the prefix in the tab was updated at once. Delivered by LuckPerms, when changing a group the prefix is ​​updated only after entering the command /nte reload

**Comment by DarkFort** [comment]
After updating NTE did not support LuckPerms

**Comment by sgtcaze** [comment]
Alright I'll test today and update with a new commit soon.

**Comment by DarkFort** [comment]
Nothing changed(

**Comment by sgtcaze** [comment]
Mm sorry about that earlier tried to edit on notepad++ without testing. See the Jenkins for a working build.
