### ISSUE TITLE
Player's passengers

### ISSUE THREAD

**Issue by Feerko** [sgtcaze/NametagEdit#212]
# Bug Report

**Type /ver NametagEdit and post the output.**
newest

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Newet PaperSpigot

**Please explain your issue. How do you trigger it?**
I want to hide player's nick above player and I make ride armor stand at player but there is still visible nametag. It's works without NTE.

**Comment by sgtcaze** [comment]
Apologies for the very late reply. I forgot to update this issue with my original thoughts -- basically, I do not think this is something we can fix. It sounds like a glitch on Mojang's end with hiding the nametag when riding or being ridden by another entity.

At a cursory glance, my thoughts were perhaps we can modify the tag visibility or data watchers, but this might introduce a host of other issues. This was 1.12 right?
