### ISSUE TITLE
Problem tab-list

### ISSUE THREAD

**Issue by Sony270** [sgtcaze/NametagEdit#213]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Spigot 1.7.10

**What plugins are you using? Type /plugins**
Trading, GroupManager, WorldEdit, ServerMotd, MassiveCore, Fireworks, Vault, War, PlayerHeads, Multiverse-Core, ModeraChat, CookieMonster, WorldGuard, AdventCalendar, MineResetLite, Lottery, iConomy, CoreProtect, MasterPromote, SimpleAutoMessage, TreasureChest, ChestShop, ProtocolLib, NametagEdit, HolographicDisplays, ToughAnvils, AreaShop, Essentials, EssentialsProtect, ServerSigns, EssentialsSpawn, LibsDisguises, BattleTracker, CreativeGates, EssentialsAntiBuild, AntiAura, AuthMe, HideAndSeek, EssentialsChat, BattleArena, ArenaPaintball, ArenaSpleef, MinigamesLib, MGSkyWars

**Please explain your issue. How do you trigger it?**
I try to join any mini-games who works with BattleArena, having joined one left my pen name becomes again of a white color and if a player leaves the waiter with a pen name in white, my launcher crash ! ^^

**Are there any errors in the console? Please use: https://pastebin.com**
no error.

**Comment by sgtcaze** [comment]
I am guessing the BattleArena plugin formats the nametag of the user when they're in game. After the game ends, it resets their nametag -- but NametagEdit is unaware of this change. I'll take a look at the BattleArena API and update this issue soon.

**Comment by Sony270** [comment]
Thank you, but you think that the plugin will be up to date when ?
