### ISSUE TITLE
[BUG] PAPI & MCore factions relational placeholders. 

### ISSUE THREAD

**Issue by Flavourized** [sgtcaze/NametagEdit#214]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.1.7, latest version from jenkins. 

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Paper 1.11.2 b1104

**What plugins are you using? Type /plugins**

NameTagEdit 4.1.7
EssentialsX (Core, Chat, and Spawn)
Worldedit 6.1.3
Worldguard 6.1.2
ProtocolLib 4.2.1
MCore 2.11.0
Factions 2.11.0
MassiveCombat 2.11.0
PEX 1.23.4
PAPI 2.8.2 (Yes, i downloaded the latest expansion for Factions and other plugins)
PAPI Factions placeholders: https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-1/#factions-mcore
PAPI Expansion: http://prntscr.com/hmazf3

**Please explain your issue. How do you trigger it?**
I am trying to change the nametag to reflect the color of the relation between 2 users (Ally, truce, neutral, enemy). I have used groups.yml in NTE to add the factions placeholders in the prefix, and given my 2 accounts the necessary permissions. 

So in this test, I have 3 accounts. 
Account1 - Flavour - OP with all permissions
Account2 - Auem - Normal Player permissions, not OP - In a faction called test1
Account3 - ruovalF - Normal Player permissions, not OP - in a faction called test2

Faction Test1 is enemy to Faction Test2 (See here http://prntscr.com/hmawsj)

config.yml - https://hastebin.com/ufapacuraq.bash
groups.yml - https://hastebin.com/ogocafitil.pl

Picture 1: http://prntscr.com/hmaw3s
- I have set Wicked & Test prefix in groups.yml to '&f' 
- Everything normal here.

Picture 2: http://prntscr.com/hmaxaw
- Changed Wicked group prefix to '&5%factions_title% &c' 
- Changed Test group prefix to '&b%factions_title% &d'
- Everything normal here.

Picture 3:
My view: http://prntscr.com/hmaxug 
Auem view: http://prntscr.com/hmay17
ruovalf view: http://prntscr.com/hmay8j
- I have kept Wicked group prefix as '&5%factions_title% &c' 
- I have changed Test group prefix to '%rel_factions_relation% &f'

Picture 4: 
My view: http://prntscr.com/hmaysi
Auem view: http://prntscr.com/hmayyl
ruo view: http://prntscr.com/hmaywe
- I have changed Wicked group prefix to '&a%factions_power%&8/&a%factions_powermax% &f'
- I have changed Test group prefix to '%rel_factions_relation_color%'

I'm not sure what else i can provide to help solve this issue. Please let me know, as i would love to use the relational placeholders. 

**Are there any errors in the console? Please use: https://pastebin.com**
No errors in console.

**Comment by airoons** [comment]
Isn't it placeholderapi problem? I think it is...

**Comment by Flavourized** [comment]
Nope. This placeholder works perfectly in every other plugin. It is just this plugin which the relational placeholders don't work.

The relational placeholders work in AdvancedTags and AnimatedNames as well, but not in NTE

**Comment by sgtcaze** [comment]
Two things come to mind (I will verify these soon):
1. The nametag w/ placeholders is not being formatted at all
2. The nametag string length is reduced before the placeholders can format the nametag

Both instances result in the above formatting (it's probably not both). This issue is confusing because the only the Placeholder code is a simple one-line solution. 

Pre-Edit-Edit: This looks a bit inconsistent
Edit: I checked the dependencies and noticed they were **super** out of date. I have updated both, and perhaps it is worth trying again without further changes to the code base.

**Comment by Flavourized** [comment]
Not sure if you have this info already, but this issue still persists on NTE v4.2.0

http://prntscr.com/htq60h

**Comment by Flavourized** [comment]
Forgot to mention the result is the same when /nte longtags is enabled or disabled

**Comment by Flavourized** [comment]
Any luck with fixing this?

**Comment by JustOneMoreBlock** [comment]
This still an issue? Use the latest build and re-open.

**Comment by Sharquisha** [comment]
Issue still persists on  latest version of Papi, and NTE.

**Comment by Flavourized** [comment]
Yep, issue still exists. Been over a year so i'm pretty confident this won't get fixed. I've moved to a better plugin now, so not really important to me anymore. 


@La-Boba If you need a plugin that can do this, take a look at [TAB](https://www.spigotmc.org/resources/tab-1-8-x-1-13-2-reborn.57806/) 

It handles tab list as well as nametags above head, and has some crazy customization options.
