### ISSUE TITLE
Nametagedit Exception!

### ISSUE THREAD

**Issue by NixalBlaze** [sgtcaze/NametagEdit#215]
# Bug Report

**Type /ver NametagEdit and post the output.**
**Nametagedit 4.1.7**

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
_server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)_

**What plugins are you using? Type /plugins**
_Vault, ProtocolLib, PlaceholderAPI, EssentialsX, ViaVersion, WorldGuard, Worldedit & PEX_

**Please explain your issue. How do you trigger it?**
When i join my server , it generates an exception.
Also, If i try to add prefix on myself , it do not work + there are errors in server console.

**Are there any errors in the console? Please use: https://pastebin.com**

**_https://pastebin.com/DwR04r76_**

**Comment by sgtcaze** [comment]
> [06:37:40 WARN]: [MVdWPlaceholderAPI] There is no MVdW placeholder plugin installed!
> [06:37:40 WARN]: [MVdWPlaceholderAPI] Put on of Maximvdw's premium placeholder plugins in the server!

Edit: It appears when the Nametag was formatted it returned a null string. I will incorporate a fix to gracefully notify you of this rather than erroring out.
