### ISSUE TITLE
LuckPerms support

### ISSUE THREAD

**Issue by Sikatsu** [sgtcaze/NametagEdit#216]
Are you able to provide support for LuckPerms?

If I upgrade someones rank, the nametag doesn't refresh until I use /nte reload

**Comment by Sikatsu** [comment]
@sgtcaze I can't seem to reach you on discord anymore

**Comment by DarkFort** [comment]
https://github.com/sgtcaze/NametagEdit/issues/210

**Comment by sgtcaze** [comment]
Closing #216 as @DarkFort reported it in #210 already. I'll checkout LuckPerms tonight.
