### ISSUE TITLE
Duplicate column name 'priority'

### ISSUE THREAD

**Issue by CandiMiiS** [sgtcaze/NametagEdit#218]
# Bug Report

NametagEdit version 4.1.7
Authors: sgtcaze and Cory

This server is running CraftBukkit version git-Spigot-549c1fa-45c8386 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Plugins (14): LuckPerms, AnimationLib, HubBasics, WorldEdit, DisableJoinMessage, NametagEdit, Vault, BungeeTabListPlus, WorldGuard, ProtocolLib, BungeePortals, AnimatedMenu, VaultChatFormatter, Essentials

This is the error i get when starting the server:
[NametagEdit] NametagEdit Query Failed - Reason: Duplicate column name 'priority'
[NametagEdit] If this is not a connection error, please enable debug with /nte debug and post the error on our GitHub Issue Tracker.
[NametagEdit] NametagEdit Query Failed - Reason: Duplicate column name 'priority'
[NametagEdit] If this is not a connection error, please enable debug with /nte debug and post the error on our GitHub Issue Tracker.

/nte debug result - https://pastebin.com/CL1DKAzz

**Comment by sgtcaze** [comment]
If the plugin functions normally, this shouldn't be an issue. Do you repeatedly see this error, even on fresh reboots? It's likely the database tag in the config.yml is off.


Edit; Please post your DATABASE VERSION from your config.

**Comment by sgtcaze** [comment]
Fixed. See Jenkins for the update.

You will only see this error 1 more time. After one restart, it will update the databse with the correct information.
