### ISSUE TITLE
Cannot get to Distrobution Website

### ISSUE THREAD

**Issue by jacksoneshbaugh** [sgtcaze/NametagEdit#220]
# Bug Report

**Type /ver NametagEdit and post the output.**

N/A. Cannot download the plugin

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

N/A. Cannot Download the plugin

**What plugins are you using? Type /plugins**
N/A The error is on SpigotMC when clicking download

**Please explain your issue. How do you trigger it?**

Go to NameTagEdit on SpigotMC.org. Click Download. You'll get an error on the server that you are trying to download from.

**Are there any errors in the console? Please use: https://pastebin.com**

N/A. Cannot Download the plugin

**Comment by JustOneMoreBlock** [comment]
- Fixed
