### ISSUE TITLE
Error NametagEdit Query Failed

### ISSUE THREAD

**Issue by DrejkBR** [sgtcaze/NametagEdit#221]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paperspigot 1.8.8

**What plugins are you using? Type /plugins**
AntiCrash, UnioAntiCrash, Terraincontrol, ClearLag, AutoMessage, WorldBorder, WorldGuard, WorldEdit, NameTagEdit, AutoLapiz, Protocolib, NoCheatPlus, SkinsRestorer, OldCombatMechanics, ShopKeepers, PermissionsE, Essesntials (spawn/chat), vault, funnyguilds, ChestCommands, TitleManager, VanishNoPacket

**Please explain your issue. How do you trigger it?**
I'm sorry, I'm sorry for my English.
This error pops up when connecting to mysql, without a database (mysql) it works normally.

[19:06:52 ERROR]: [NametagEdit] NametagEdit Query Failed - Reason: Duplicate column name 'priority'
[19:06:52 ERROR]: [NametagEdit] If this is not a connection error, please enable debug with /nte debug and post the error on our GitHub Issue Tracker.
[19:06:52 ERROR]: [NametagEdit] NametagEdit Query Failed - Reason: Duplicate column name 'priority'
[19:06:52 ERROR]: [NametagEdit] If this is not a connection error, please enable debug with /nte debug and post the error on our GitHub Issue Tracker.

The tags do not show.

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/cjpRChx0

**Comment by sgtcaze** [comment]
Please post your `DatabaseVersion:` from your **config.yml**. Since you are using MySQL, are you able to display your table format for the database?

**Comment by DrejkBR** [comment]
That's what you mean?
@sgtcaze

**Comment by DrejkBR** [comment]
?

**Comment by sgtcaze** [comment]
Oh no I was asking for your database version [which you can see here](https://github.com/sgtcaze/NametagEdit/blob/master/src/main/resources/config.yml#L9). Also, it appears you posted your database details in a paste, I strongly recommend you change your password.

Edit; I was also asking for the "schema" structure. I will look into why this issue persists.

**Comment by DrejkBR** [comment]
@sgtcaze 
That password was fake.
I do not understand to get rid of you but give you a whole cfg (password mysql fake)
https://pastebin.com/YQnjFdVt
If I gave you the wrong, please write it simpler because my translator does not translate very well.

**Comment by sgtcaze** [comment]
You will only see this error 1 more time. After one restart, it will update the databse with the correct information.
