### ISSUE TITLE
 Error NametagEdit Query Failed  (tags)

### ISSUE THREAD

**Issue by DrejkBR** [sgtcaze/NametagEdit#224]
I'm Polish (sorry for my English)
You closed my topic named: Error NametagEdit Query Failed # 221
The problem disappeared in the console
But the tags are still not working ...

**Comment by sgtcaze** [comment]
Ah, your github issue was 2 issues. I did not realize. Well, the first issue was fixed, so now about the tags not displaying.

Are you using the GROUP or PLAYER option? Do /nte debug to see if the nametag is being applied.

**Comment by DrejkBR** [comment]
I do not know exactly what you mean when you use / net debug, tags do not work anymore
@sgtcaze

**Comment by sgtcaze** [comment]
Test:
1) **/nte debug**
2) **/nte player YOUR_NAME prefix &b**

When you join the game, do you see something like this?
![example](https://user-images.githubusercontent.com/4266612/34425568-dccc5e3c-ebe1-11e7-94d5-28b29145ac24.PNG)

Does it apply the nametag or show any output?

**Comment by sgtcaze** [comment]
As there has been no update in over a month, I will close this issue. If you still experience issues, or if anyone experiences this issue moving forward -- **please create a new issue**. There is a chance I will not check this old issue.
