### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Pabsb** [sgtcaze/NametagEdit#225]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.2.0
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.8.3-R0.1-SNAPSHOT

**What plugins are you using? Type /plugins**
WordEdit, killStats, NametagEdit, Holograms, WorldGuard, MVdWPlaceHolderAPI, PermissionsEx, FeatherBoard, ViaVersion, mcMMO, KeepTheWeather, Vault, HideStream, InfiniteBlocks, CombatTagPlus, EssentialsX, EssentialsXChat, EssentialsXSpawn, EssentialsXGeoIP, Protocollib, NoCheatPlus, CompactNoCheatPlus, PNCP

**Please explain your issue. How do you trigger it?**
https://imgur.com/a/c5yS4
People with longer than 16 Characters name tags in tab are fine but when you look at the player it isn't. Is there a way to fix and or option to disable it showing on the player and just showing on the tab

**Are there any errors in the console? Please use: https://pastebin.com**
None

**Comment by sgtcaze** [comment]
Not a bug, please see the explanation here: https://github.com/sgtcaze/NametagEdit/issues/222#issuecomment-354376652

**Comment by Pabsb** [comment]
But how do I make the player names show all of the name tag? The other post doesn't explain how to.
