### ISSUE TITLE
Problems with the Tag in Head

### ISSUE THREAD

**Issue by Vitauum** [sgtcaze/NametagEdit#226]
# Bug Report

**Type /ver NametagEdit and post the output.**

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Spigot 1.8.3

**What plugins are you using? Type /plugins**
group manager, nametagedit, tablist, essentials and others

------------------------------------------------
(sorry my english im not american)
i dont have errors in my console, but i have in game

i'm using the option long tags for the TAB, but i have a problem with the tag in players head, up the head.
When i put a tag in a player, if this tag if very long with diferent colors (example the tag challenger on my server : &8&l[&D&LC&6&LH&C&LA&B&LL&7&LL&9&LE&E&LN&5&LG&A&LE&3&LR&8&l])
this tag Bug on the player's head and cut the tag and your name. On tab is ok, but on head this tag is cut  :(.

Please i dont know what to do, i need help!!

**Comment by sgtcaze** [comment]
The exact same thing was reported here, and it is not a bug. https://github.com/sgtcaze/NametagEdit/issues/225

**Comment by Vitauum** [comment]
men, do you know any plugin to modify this name template on minecraft
server ?

**Comment by sgtcaze** [comment]
There is no way to get around the limitation of 48 characters total. I do not know of any plugins that have attempted work-arounds.

**Comment by Vitauum** [comment]
on this server they dont have problems with the limit, the limit for me is
16, i dont understand why, if other servers can use more ://

**Comment by Vitauum** [comment]
on tab is ok and up the head is ok on other servers
