### ISSUE TITLE
[Bug] Nickname

### ISSUE THREAD

**Issue by Typheonn** [sgtcaze/NametagEdit#227]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.12.1

**What plugins are you using? Type /plugins**
Essentials

**Please explain your issue. How do you trigger it?**
When someone (op or player) execute the command /nickname XXX , we can see ~XXX in the scoreboard less the colour.

**Comment by sgtcaze** [comment]
We do not have a /nickname command. Are you sure you're not using another plugin that has this command?

**Comment by Typheonn** [comment]
Hi.

The command /nickname is from "essentials". But i thought that it should works with essential's command.

Then saddened for the disturbance.
