### ISSUE TITLE
Unicode and Special Characters for Tags

### ISSUE THREAD

**Issue by MrDiggi** [sgtcaze/NametagEdit#228]
# Bug Report (Suggestion for more characters support or any API to do that) :)

**Type /ver NametagEdit and post the output.**
- 4.0.2

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
- Spigot 1.8.8

**What plugins are you using? Type /plugins**
- PermissionsEx, NameTagEdit, Essentials, PlaceholderAPI and ProtocolLib

**Please explain your issue. How do you trigger it?**
Just trying to use special characters like "ñ", it's a spanish server, just to write Owner, but in spanish (Dueño).

**Are there any errors in the console? Please use: https://pastebin.com**
No, it's just that thing (\u00F1 means "ñ" in unicode, some things support that unicode codes)

![tab](https://user-images.githubusercontent.com/35002631/34468249-9b10a46e-eeb9-11e7-96dd-6470aab8f9f3.png)

**Comment by sgtcaze** [comment]
Are you using MySQL or FlatFile?
