### ISSUE TITLE
Team specific sidebar compatibility for 3rd party plugins

### ISSUE THREAD

**Issue by Maximvdw** [sgtcaze/NametagEdit#231]
With 1.13 (or NMS with the current versions of Spigot) the sidebar scoreboard will be able to be assigned based on the team color. 

Basically: You are in a team as a player -> the color of the team changes and it changes the scoreboard on the side based on the color.

Plugins will have to hook into NTE if they want to utilize this. Currently what I do is "getFakeTeam(String player)" for that player and use that team name for everything I do instead of creating my own (since a player can only be in one team). But this has an issue:
- With your "RefreshInterval" you basically reset the color resulting in the changes done by 3rd party plugins that try to make this plugin compatible to be lost.

Proposed change:
Allow 3rd party plugins to set the color of a team the player is in, without it affecting other players. 
This will add a few changes:
1) Currently teams are not unique, only based on their prefix/suffix. My proposal is to have an unique 'FakeTeam' per player
2) Add "setColor" and "getColor" to those teams that will be used when sending a new "Refresh" packet. That way a 3rd party plugin can set the color when they change it as well - so when NTE updates the team it also updates the color

**Comment by Maximvdw** [comment]
Seeing team prefix/suffix are removed in 1.13 in the latest snapshot, I think you better hold off with these changes

**Comment by sgtcaze** [comment]
Thank you for the insight, Maxim. Cory and I are keeping an extra close eye on these changes, and we're hoping to start a dialogue with Mojang.

**Comment by Maximvdw** [comment]
Did you manage to start a dialogue?

**Comment by sgtcaze** [comment]
Hello Maxim. No, unfortunately Mojang seems to have ignored us. Or maybe they just didn't see our messages.

**Comment by JustOneMoreBlock** [comment]
This was my dialog:
https://twitter.com/JustPlayHere/status/948638297634549763

Might have to take it to Reddit.

**Comment by Maximvdw** [comment]
Spigot will leave a legacy option that basically edits the name. For my AnimatedNames and your NTE this means we have to use custom playerlist packets (or go the vanilla way without player to player specific prefix)

**Comment by sgtcaze** [comment]
Thank you for the update, Cory and Maxim. We'll adjust when the time comes. I'll also keep an eye on your plugin AnimatedNames.
