### ISSUE TITLE
HOW TO SETUP DEFAULT NAMETTAG

### ISSUE THREAD

**Issue by uzmanshafi** [sgtcaze/NametagEdit#235]
# Bug Report

**Type /ver NametagEdit and post the output.**
latest

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
latest

**What plugins are you using? Type /plugins**
essentials x ,clear lag and grief prevention and permission x

**Please explain your issue. How do you trigger it?**
i want set the default nametag when a player joins is it possible
like i have group called default and the prefix is [neebie] how can i auto add this prefix
to a new player or current player that is a default player in my permmision x plugin group

thank you

**Comment by JustOneMoreBlock** [comment]
Hello,

Make sure you set up a permission node like `nte.default` and give your default rank that permission.

Kind Regards,
Cory

**Comment by uzmanshafi** [comment]
does this plugin work on sponge

**Comment by sgtcaze** [comment]
This plugin does not work with sponge. If your issue is not resolved, please re-open or make a new issue.
