### ISSUE TITLE
Support multiple lines

### ISSUE THREAD

**Issue by BoomEaro** [sgtcaze/NametagEdit#236]
Feature request:

Can you add support for second lines?
Now it looks like this:
https://imgur.com/a/Fa7NT

https://imgur.com/a/wk9aJ

**Comment by sgtcaze** [comment]
I like this idea but we would require multiple holograms stacked on the player or some similar effect. Last time I checked though the nametag jitters a lot when you move around, which is why we didn't add it before.

**Comment by JustOneMoreBlock** [comment]
Unfortunately, we may have to go that route anyway if there is no substitute for Prefix and Suffix in 1.13. On the plus side, we can have really long prefixes and suffixes and possibly add Multi stuff. Who knows.

**Comment by SeruhioX** [comment]
I hope it can be added and it not move so much, since in other plugins it moves too much and it is bad.
