### ISSUE TITLE
world issue

### ISSUE THREAD

**Issue by Feerko** [sgtcaze/NametagEdit#237]
Hello, there is an issue, i have few worlds.

player1 is in world1, player2 is in world2

and if i type 'nte player player1 prefix blabla'
player2 go to player1's world
and player2 see player1's default tag
but players in player1's world see new tag

i'm using the newest version

**Comment by sgtcaze** [comment]
Are you using 1.12?

**Comment by Feerko** [comment]
yes

**Comment by JustOneMoreBlock** [comment]
Still an issue?
