### ISSUE TITLE
Bug with LongTags

### ISSUE THREAD

**Issue by CryLegende** [sgtcaze/NametagEdit#238]
# Bug Report

PL Version: 4.2.0 (latest)

Server Version: PaperSpigot 1.8.8 (git-PaperSpigot-"4c764d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins: Not important

Enable LongTags in the config =
Placeholders not working in the tablist and LongTags not working in tag.

The plugin try to use Placeholders/MVDWPlaceholders but not work.

**Comment by sgtcaze** [comment]
Placeholders work with LongTags disabled?

Please use **/nte debug** and show the output when a player's nametag should be applied.

**Comment by CryLegende** [comment]
LongTags: false
![2018-02-04_10 18 24](https://user-images.githubusercontent.com/25080946/35776026-069ae4a6-0995-11e8-814d-c37ff0b40614.png)


LongTags: true
![2018-02-04_10 18 48](https://user-images.githubusercontent.com/25080946/35776030-1d29b8aa-0995-11e8-9722-7f7cada644d5.png)


https://hastebin.com/odasikemux.md
