### ISSUE TITLE
NameTags not hidden when KitBattle players use the ghost kit? 

### ISSUE THREAD

**Issue by wattywatty14** [sgtcaze/NametagEdit#239]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.1.4

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

CraftBukkit version git-Spigot-21fe707-elebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT

**What plugins are you using? Type /plugins**

Not important. 
**Please explain your issue. How do you trigger it?**

It's a KitBattle thing. We went to use a "ghost" kit which makes the player invis, but yet the nametag still shows up. It doesn't make them invis.

**Are there any errors in the console? Please use: https://pastebin.com**

No.

**Comment by sgtcaze** [comment]
Unfortunately this is a long standing minecraft bug present prior to 1.9 or 1.10 (I forget). We are unable to fix it, please see these issues for reference: https://github.com/sgtcaze/NametagEdit/issues?utf8=%E2%9C%93&q=is%3Aissue+invisibility
