### ISSUE TITLE
placeholders

### ISSUE THREAD

**Issue by comfysquirrel** [sgtcaze/NametagEdit#24]
Is it possible to have placeholders (maybe [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) integration) in prefixes and suffixes? Among other things, this would allow the player's Vault prefix to be used.

**Comment by TheBrambleShark** [comment]
As an addition to this, I think having placeholders for the user's display name and real name would be beneficial, assuming we get the ability to decide whether or not to [show the user's nickname](https://github.com/sgtcaze/NametagEdit/issues/23) in future releases.

**Comment by comfysquirrel** [comment]
Yep! PlaceholderAPI has `%player_name%` and `%player_displayname%` placeholders - https://www.spigotmc.org/wiki/placeholderapi-placeholders/

**Comment by JustOneMoreBlock** [comment]
I've discussed this briefly with @sgtcaze - I'm not opposed to this idea.

Might even get them to add in NametagEdit into PlaceholderAPI. :)

**Comment by sgtcaze** [comment]
This has been added to v4.1.2 of NametagEdit. Commit soon.
