### ISSUE TITLE
NTE teams show up in spectator mode

### ISSUE THREAD

**Issue by Spirit55555** [sgtcaze/NametagEdit#24]
As you can see on the pictures below, the NTE teams show up in spectator mode.

NametagEdit version 3.0
CraftBukkit version git-Spigot-081dfa5-7658819 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

![2015-01-14_23 02 27](https://cloud.githubusercontent.com/assets/2357565/5748890/dac7eeb2-9c43-11e4-9630-d780d1cfb09c.png)
![2015-01-14_23 02 30](https://cloud.githubusercontent.com/assets/2357565/5748891/daffbef0-9c43-11e4-9852-0b9b64701664.png)

**Comment by morpig** [comment]
Maybe the same issue with #23?

**Comment by sgtcaze** [comment]
Something we cannot resolve with the plugin. Perhaps related to:
https://bugs.mojang.com/browse/MC-48730

Will keep an eye on it, however. The repo will be updated with that information when it becomes available.
