### ISSUE TITLE
Bug Long Tags

### ISSUE THREAD

**Issue by xMaZax** [sgtcaze/NametagEdit#241]
Bug long name tags!!
![screenshot_2](https://user-images.githubusercontent.com/29258529/35703523-efa54d4e-07ce-11e8-887a-e12d8a285940.jpg)

**Comment by sgtcaze** [comment]
This is not a bug. Nametag prefix and suffixes are limited to 16 characters for the nameplate (nametag above your head.) LongTags simply allows more characters in the tab.
