### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DIMC09** [sgtcaze/NametagEdit#243]
I need help, when a user dies it loses the prefix and in the tag it is bug with the name of some users

**Comment by sgtcaze** [comment]
What version of minecraft? It's probably another plugin that is resetting the player's metadata/scoreboard etc.

**Comment by DIMC09** [comment]
1.8

**Comment by sgtcaze** [comment]
Do you have a plugin that changes the player's scoreboard when they die? Perhaps a KitPVP plugin, mcMMO, factions etc.

**Comment by DIMC09** [comment]
no

**Comment by sgtcaze** [comment]
This is likely another plugin or the server software itself. Try removing plugins one by one, and see if it affects the nametag on death.

**Comment by DIMC09** [comment]
i have 60 plugins....

**Comment by JustOneMoreBlock** [comment]
If you have access to the console. You can type `pl` and copy and paste a list here.

**Comment by DIMC09** [comment]
PlaceholderAPI, Announcer, SpawnJoin, SetLobby, NametagEdit, TopTenHeads, AntiJoinBot, ViaVersion, Tablist, KitsCreator, AntiCrash, WorldEdit, EmptyWorldGenerator, HealthBar, Essentials, VipSlot, ClearLag, BuycraftX, Reputation, ProtocolLib, NoCheatPlus, EssentialsChat, PermissionsEx, Vault, ServerListPlus, MassiveCore, CrashFix, PerWorldInventory, CreativeGates, LWC, KillerMoney, WorldGuard, ChestCommands, EssentialsProtect, EssentialsAntiBuild, ServerSigns, PlayerHeads, ShopGUIPlus, FrameProtect, CommandBlocker, PlotMe, HeadDatabase, 1vs1, Citizens, ChestShop, PlotMe-DefaultGenerator, Multiverse-Core, MineResetLite, SkyWarsReloaded, AuthMe, Jail, HolographicDisplays, SkinsRestorer, IslandWorld, Multiverse-NetherPortals, MultiWorldMoney, CombatLog

**Comment by nuchoman** [comment]
How is this closed??
