### ISSUE TITLE
Not working with MVDWPlacewoldersAPI.

### ISSUE THREAD

**Issue by CryLegende** [sgtcaze/NametagEdit#244]
# Bug Report

Version of NameTagEdit: 4.2.0 (latest build)

Server Version: PaperSpigot 1.8.8 (git-PaperSpigot-"4c764d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins: PlaceholdersAPI, MVDWPlaceholdersAPI, NameTagEdit

The plugin does not work and causes a lot of bug if MVDWPlaceholdersAPI is download.

https://hastebin.com/novuliseqi.vbs

Any plugin that uses MVDWPlaceholdersAPI causes errors in the console

**Comment by sgtcaze** [comment]
Not a bug. See the commit here: https://github.com/sgtcaze/NametagEdit/commit/cea0bf94785e818a09915956477a3fdb454459cf

And the new FAQ entry here: https://github.com/sgtcaze/NametagEdit
