### ISSUE TITLE
Long Tags are Truncated

### ISSUE THREAD

**Issue by henrikbg** [sgtcaze/NametagEdit#245]
# Long Tags are Truncated

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
CraftBukkit version git-Spigot-550ebac-7019900 (MC: 1.8)(Implementing API version 1.8-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
WorldEdit, Essentials, EssentialsChat, PermissionsEx, ClearLag, AutoMessage, NametagEdit, Vault, StaffPlus, EssentialsSpawn, WorldGuard, Multiverse-Core, MassiveCore, Factions

**Please explain your issue. How do you trigger it?**
When a player name becomes longer than around 16 characters or so, the name above the player's character is truncated. This only occurs above said player's head, not in the tab list or chat. I have long tags enabled, so is this a bug?

<img width="1138" alt="screen shot 2018-02-06 at 10 19 07 pm" src="https://user-images.githubusercontent.com/14116830/35898349-c72ad1b6-0b8b-11e8-9bf1-74cdb6744305.png">

The correct tag is supposed to look like: &8[&eHelper&8] &e{player}
({player} is PhilipBerg in this case)

**Are there any errors in the console? Please use: https://pastebin.com**
No errors outputted to the console.

**Comment by sgtcaze** [comment]
This is not a bug. I added a new entry to the FAQ to explain why this happens.
