### ISSUE TITLE
NTE wont work without MVdWPlaceholderAPI  premium plugin

### ISSUE THREAD

**Issue by Someone-NEW** [sgtcaze/NametagEdit#246]
@sgtcaze and @Cory I had some problem i dont know why NameTagEdit wont work without MVdWPlaceholderAPI when there is no installed one of their plugins??? You can add PlaceholderAPI too and somehow fix this with him "MVdW" to be NameTagsEdit work

`[22:35:06 INFO]: NametagEdit was unable to format nametag for NameUser2
[22:35:06 INFO]: Are your PlaceHolder plugins properly installed?
[22:35:06 WARN]: [MVdWPlaceholderAPI] There is no MVdW placeholder plugin installed!
[22:35:06 WARN]: [MVdWPlaceholderAPI] Put on of Maximvdw's premium placeholder plugins in the server!
[22:35:06 INFO]: NametagEdit was unable to format nametag for NameUser1
[22:35:06 INFO]: Are your PlaceHolder plugins properly installed?`

**Comment by sgtcaze** [comment]
Hi, this is not a nametagedit issue. There is an FAQ entry about this specifically. You can see the error we output in newer versions of the plugin [here](https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/NametagHandler.java#L300-L302)

Basically, for MVdW and PAPI to work - you need external plugins or addons to format the nametags. These plugins do not actually contain/do any placeholder actions, they interface functionality for other plugins to do this.

**Comment by Flavourized** [comment]
To specify, mvdwPlaceholder plugin doesn't have any placeholders in the plugin itself. 

You need to own one of Maxim's premium plugins. His premium plugins are where the placeholders are kept. If you don't own one of his premium plugins which uses placeholders, you won't be able to use mvdwPAPI at all. 


You have 2 options:
1. Purchase & use one of Maxim's premium plugins: Featherboard, tab, animatedNames, dynamicSigns, etc

2. Remove mvdwPAPI so it does not cause issues. Make sure to switch your placeholders to %% for clip's PAPI if you choose to use his placeholders.


There is nothing else beyond those 2 options. NameTagEdit currently works perfectly. NameTagEdit will work perfectly for you AFTER you pick 1 of the 2 options i listed above

**Comment by Someone-NEW** [comment]
Ok i am already do the same before i see this message and now work great only i miss more options and maybe 2 lines and maybe some animated features. Another that refresh is too much visible, too much blining and seems ugly. Than refresh need only refresh underplayer heads tags when is TAB feature disbled i see once that is all refreshed i use CMI for TAB feature so its disabled.
