### ISSUE TITLE
The prefixes and suffixes in the tab are reset

### ISSUE THREAD

**Issue by DarkFort** [sgtcaze/NametagEdit#249]
At the death or change of the world, the prefixes and suffixes in the taba are discarded and become white. Configuring RefreshTagOnWorldChange: true does not help
Latest version NameTagEdit
PaperSpigot 1.12.2
LuckPerms Permission System

**Comment by sgtcaze** [comment]
Probably because when the player dies, LuckPerms refreshes their permissions, triggering the nametag listener. Applying the same nametag twice has (in the past) caused the player to have no visible nametag (still technically applied, just not view-able.)

**Comment by JustOneMoreBlock** [comment]
Is this still an issue? Please use the latest build and re-open.
