### ISSUE TITLE
Titles unload upon world switch

### ISSUE THREAD

**Issue by Jechto** [sgtcaze/NametagEdit#25]
here is a bug i found
If you switch world, the tablist and name overlay changes to default (only for that user). However a plugin reload will fix it. The server doesn't seem to output an error. (maybe client side IDK)

Using Verson 4.0.2

**Comment by sgtcaze** [comment]
Perhaps you are using a permissions plugin that does per-world permissions?

I use NametagEdit on BIG servers where users are constantly changing worlds, and this is not an issue.

**Comment by Jechto** [comment]
i dont use per-world permission, however i use Multiverse, Groupmanager, and Multiinv (perhaps conflict).
I'm going to test on a server with multiinv installed

**Comment by JustOneMoreBlock** [comment]
@Jechto Are you using Flatfile or MySQL?

**Comment by Jechto** [comment]
I'm using flatfile

**Comment by JustOneMoreBlock** [comment]
Unable to reproduce using flat file or MySQL.

Tested with:
- Multiverse
- GroupManager
- EssentialsX
- Multiverse

Build #: 28

Please re-open or open a new issue with any more information to contribute.

**Comment by ghost** [comment]
I am having the same problem my self, I don't know how to fix it. 
If I know how to fix it, I'll tell you guys ASAP!
