### ISSUE TITLE
LibsDisguises not showing nametag

### ISSUE THREAD

**Issue by sjoerdtim** [sgtcaze/NametagEdit#250]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.2.0
(Latest dev build)

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running Paper version git-Paper-1283 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) 

**What plugins are you using? Type /plugins**
Plugins (29): ArmorStandEditor, AutoKiller, EnjinMinecraftPlugin, Essentials, FastAsyncWorldEdit, LibsDisguises, MundoSK, NametagEdit, NoCheatPlus, OldCombatMechanics, PermissionsEx, Plan, ProtocolLib, Reqn, Skellett, SkQuery, skRayFall, Skript, skript-db, skript-mirror, skript-votifier-hook, SkStuff, skUtilities, Vault, ViaBackwards, ViaVersion, Votifier, WorldEdit, WorldGuard

**Please explain your issue. How do you trigger it?**
Once a player gets a disguise using LibsDisguises, they no longer have a custom tag/colour. Once the disguise ends, their tag/colour returns.
I'm using the latest dev build of LibsDisguises.

**Comment by JustOneMoreBlock** [comment]
Hello,

- Currently, I have `OWNER` tag.
- Ran: `/disguise p Cory_`
- I still have the `OWNER` tag.

Not able to re-create this issue.
