### ISSUE TITLE
Nametag not showing full size

### ISSUE THREAD

**Issue by MrPinguino** [sgtcaze/NametagEdit#253]
# Bug Report

**Type /ver NametagEdit and post the output.**
20.03 19:48:22 [Server] INFO NametagEdit version 4.2.0
20.03 19:48:22 [Server] INFO Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
http://prntscr.com/itxs7q

**What plugins are you using? Type /plugins**
http://prntscr.com/itxsfi

**Please explain your issue. How do you trigger it?**
http://prntscr.com/itxplb
Above you see a screenshot of the problem and here is the config
  Owner:
    Permission: nte.owner
    Prefix: "&8&l[&2&lOwner&8&l]&3 "
    Suffix: " &c[Staff]"
    SortPriority: 1

Its not showing the full prefix i have   LongTags: true mabby you can help me a bit more

**EDIT:**
The problem is that the plugins sees the color codes also as characters so thats the problem mabby you can filter the color codes.

**Are there any errors in the console? Please use: https://pastebin.com**
No there are Zero errors

**Comment by JustOneMoreBlock** [comment]
The character count is 22.
```
Prefix: "&8&l[&2&lOwner&8&l]&3 "
```
_The max character count is 16._

You would need to remove brackets or the all the caps to make it fit.
