### ISSUE TITLE
fix for invisibility potions

### ISSUE THREAD

**Issue by PhanaticD** [sgtcaze/NametagEdit#256]
hi, so a long time bug has been invisibility potions dont hid your nametag, why not just hide the tag in the potion effect and potion drink event for the duration of the effect?

**Comment by JustOneMoreBlock** [comment]
Every player that uses 1.8.9 has this bug and it's something we cannot fix.

**Comment by PhanaticD** [comment]
would not just removing the tag while a player has the invisibility effect would fix this bug, thats what other nametag plugins do?

**Comment by JustOneMoreBlock** [comment]
I can't say for sure this would fix the issue as it's a visual bug with the client itself. Thinking about this a bit we would have to have the nametag stored, but then add some `if vanished` to remove the tag. However, keep in mind by doing so. If you and other staff are vanished and can see each other, you will not see any tags.

Some users want the feature you're requesting.
Some users want the feature where you can keep the tag(s) and be in vanish and visible by other staff.
