### ISSUE TITLE
NTE Groups

### ISSUE THREAD

**Issue by Jonnie2** [sgtcaze/NametagEdit#257]
# Bug Report

**Type /ver NametagEdit and post the output.**

NametagEdit version 4.1.7
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

1.8.8 Spigot

**What plugins are you using? Type /plugins**

https://ibb.co/e8MMaS

**Please explain your issue. How do you trigger it?**

I have given each group the permission for each nametag (each group has a different coloured nametag) and it always shows up as the first groups nametag. I have tried it with priorities and without priorities. When I do /nte group list, it displays all of the groups in the correct colours with the correct permissions. I can change the nametags manually for each player and it works fine that way.

**Are there any errors in the console? Please use: https://pastebin.com**

none.

**Comment by JustOneMoreBlock** [comment]
@Jonnie2 Are you still having this issue? Could you update to our latest version?

**Comment by Jonnie2** [comment]
Yes, I have updated the plugin and I am still having these issues.

**Comment by JustOneMoreBlock** [comment]
Hello,

Are you using `MySQL`? If so, then make sure you use the `order` command.

```
/nte group order <groups>
```

Example:
```
/nte group order Owner Admin Sr_Mod Mod VIP Guest
```
_Sort it by highest rank to lowest rank._

If that still doesn't work. You may need to negate the permissions from within your permissions plugin.

priorities and order are similar but accomplish two different things.

Kind Regards,
Cory
