### ISSUE TITLE
Problem with Tablist Plugin

### ISSUE THREAD

**Issue by Greenman1805** [sgtcaze/NametagEdit#26]
I set the PlayerListName for a player with:
p.setPlayerListName(prefix + group + " §f> " + prefix + p.getName());

but it is only like this for some milliseconds and then the name of the player in the tablist changes to white.

I have also set this in the config:
TabListDisabled: true

**Comment by JustOneMoreBlock** [comment]
@Greenman1805 Based on your post. Are you using our API?

**Comment by Greenman1805** [comment]
No, I've set up the nametags via the groups file and gave permissions. All works fine :)
*Edit: Some players get a white name in the tablist and others get the name set with the code above.

**Comment by Greenman1805** [comment]
Of course I tested it without NametagEdit on my server and my code worked fine. Only that you know there is nothing wrong with my plugin.

**Comment by JustOneMoreBlock** [comment]
Unable to reproduce using flat file or MySQL.

Build #: 28

Please re-open or open a new issue with any more information to contribute.
