### ISSUE TITLE
Name over the head of player

### ISSUE THREAD

**Issue by fatdog66** [sgtcaze/NametagEdit#26]
Hi,
i have found an little bug on the name over the head of player. When he drink an vanish potion, the name persist. Please, update this.
THX dude !

sorry for my english, i'm french

**Comment by Spirit55555** [comment]
This is a known bug in Minecraft: https://bugs.mojang.com/browse/MC-48730

**Comment by sgtcaze** [comment]
Thanks @Spirit55555 for linking this. Unfortunately Minecraft 1.8 has a few rendering bugs (such as hitting F5 and seeing nametags)

**Comment by fatdog66** [comment]
thx Spirit55555
