### ISSUE TITLE
Relation color placeholders not working

### ISSUE THREAD

**Issue by WizzleBear** [sgtcaze/NametagEdit#260]
# Bug Report

**Type /ver NametagEdit and post the output.** 4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver** git-Paper-1384 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins** ChatControl, Essentials, EssentialsChat, EssentialsSpawn, Factions, LuckPerms, mcMMO, Multiverse-Core, NametagEdit, PlaceholderAPI, PlayerVaults, PrefixManager, ProtocolLib, TitleManager, Vault (Some have been removed because they are not relevant.)

**Please explain your issue. How do you trigger it?** I have the [FactionsUUID placeholders](https://github.com/drtshock/Factions/wiki/Placeholders) installed with PAPI, restarted the server, and all the other placeholders work except the relation color ones.

**Are there any errors in the console? Please use: https://pastebin.com** None

**Comment by WizzleBear** [comment]
On second thought, might be a problem with FUUID and PAPI, and not NTE. Imma leave this open until further notice.

**Comment by JustOneMoreBlock** [comment]
Well, I tried installing the eCloud and seems to offline or I have an outdated version. However, the command should be something like:
```
/papi ecloud download Factions
```

Re-open your issue if the issue persists.

**Comment by WizzleBear** [comment]
Clip has added the placeholders into FactionsUUID, so no need to download it now. It is definitely a problem with the integration since others are having the same problem. Thanks for the response anyway!
