### ISSUE TITLE
No Tags showing up

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#261]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
![image](https://user-images.githubusercontent.com/29896129/38559353-adbace96-3cca-11e8-9214-884f6b2f0ac5.png)

**Please explain your issue. How do you trigger it?**
I am not sure, I just installed the plugin setup all the groups and found that its not showing up /nte player doesn't work either, which lead me to think it might be permissions, but they look alright to me.

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/raw/Erv0zkaX

**Comment by ghost** [comment]
Bump

**Comment by JustOneMoreBlock** [comment]
Hello,

The `/nte player` is used to define a specific player. If you want to use permissions and groups, you need to use `/nte groups`

https://github.com/sgtcaze/NametagEdit/wiki/Commands#creatingediting-group-properties

Then do:
https://github.com/sgtcaze/NametagEdit/wiki/Commands#ordering-group-priority

Re-open issue if your issue persists.
