### ISSUE TITLE
NameTag update 

### ISSUE THREAD

**Issue by SkyAcer009** [sgtcaze/NametagEdit#263]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

PaperSpigot version git-Paper-1381 MC: 1.12.2 
Implements API version 1.12.2-R0.1-SNAPSHOT

**What plugins are you using? Type /plugins**

I don't believe any are affecting but I have Featherboard which is a major plugin that interferes with NameTagEdit scoreboard. So I think the issue is that it is manipulating the NameTagEdit TAB displayslot board. 
But here
Plugins (20): BlockVersion, ChatManager, Citizens, CommandNPC, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FeatherBoard, HiveJumpPads, HolographicDisplays, IPWhitelist, LuckPerms, MVdWPlaceholderAPI, NametagEdit, NoVoidFall, PlugMan, ProtocolSupport, Vault, WorldEdit, WorldGuard

**Please explain your issue. How do you trigger it?**

I used NameTagEdit before, and I know how to setup the plugin groups and configuration correctly.
But the issue is, when I used to change the group of a user to a complete different inheritance, the nametag used to update as per the permission set in groups.yml and in LuckPerms, automatically, without needing to set any refresh interval. But now the tag does not update at all, I don't know if I'm doing something wrong, the only difference is that this time we use the Featherboard plugin. 
I have disableTabList now set to false in config.yml and still no result, and I don't want to setup a refresh interval since I made a plugin that uses the API to get the name tag and set it in the player's chat, and a refresh interval will make the chat sometimes glitchy and throw up some NullPointerExceptions in console. (Which I believe the issue is when the name tag refreshes and a player sends a chat message at the same time, the nametag will flicker in tab, hence the plugin fails to get the name tag and throws a NPE) 

**Are there any errors in the console? Please use: https://pastebin.com**

The only error I had with this plugin so far is the NPE when my chat plugin fails to get the name tag of a player. 

https://hastebin.com/dasorexevu.vbs 

Hastebin is easier to read ;)
Goodluck and thanks in advance
-Sky

**Comment by SkyAcer009** [comment]
bump

**Comment by JustOneMoreBlock** [comment]
The error appears to be coming from:
```
com.sasoftwares.chatmanager.ChatRankListener.onPlayerChat(ChatRankListener.java:25) ~[?:?]
```
Which is the `ChatManager`.

Could you try removing this plugin and see if everything is working as usual? If not, please post your configurations.
