### ISSUE TITLE
REQUEST: Using ASkyBlock Variables with prefixes 

### ISSUE THREAD

**Issue by devkapa** [sgtcaze/NametagEdit#265]
Hey, just a quick request. Not sure if this is entirely possible, but if you could, add support for the ASkyBlock Variables (such as {ISLAND_LEVEL}, {ISLAND_CHALLENGE_LEVEL}, and {ISLAND_PLAYER}) for tablist and nametags?

Thanks for your time, 
kapacraft

**Comment by JustOneMoreBlock** [comment]
You should be able to do this. Install Placeholder API.

```
/papi ecloud download ASkyBlock
```

**Comment by devkapa** [comment]
Oh okay. Thanks ^-^

**Comment by devkapa** [comment]
@JustOneMoreBlock Hmm... I did what you said, still not working even after a restart. I tried removing the brackets and colors too. Also, the square brackets around the {ISLAND_LEVEL} are there on purpose, its for design and even after removing them it made no difference
![2018-04-19_19 22 23](https://user-images.githubusercontent.com/38523331/38983215-2a39ac4c-4407-11e8-894e-c6fd61dd0bdc.png)

**Comment by jsuarezl** [comment]
You must use this placeholders https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-1/#askyblock @kapacraft
