### ISSUE TITLE
Can't see colored names in tablist (all white(

### ISSUE THREAD

**Issue by Golicraft** [sgtcaze/NametagEdit#268]
# Bug Report

**Type /ver NametagEdit and post the output.**
nametagedit 4.2.0 

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
https://gyazo.com/d5a1b09b3a6c4ef9e87c07fbfaa9064f

**What plugins are you using? Type /plugins**
https://gyazo.com/921cbc553f580951b15e74051c164eff

**Please explain your issue. How do you trigger it?**
I can't let the tablist work. I have all plugins installed but it is only showing white names even i edited groups.yml and have set multiplie permissions. 

The plugins that also use the tablist that i use is
- TitleManager
- Featherboard version 3.22.0

I have:
- PlaceholderAPI
- MvDW PlaceholderAPI
- Nametagedit 4.2.0
- Featherboard 3.22.0

**Are there any errors in the console? Please use: https://pastebin.com**
No it is not.

Groups.yml >
Groups:
  Admin:
    Permission: nte.admin
    Prefix: '&c'
    Suffix: '&f'
    SortPriority: 1
  Moderator:
    Permission: nte.moderator
    Prefix: '&2'
    Suffix: '&f'
    SortPriority: 2

Config.yml >
https://pastebin.com/cDMwgaYB

**Comment by JustOneMoreBlock** [comment]
Are you still having this issue? If so, please re-open this issue.
