### ISSUE TITLE
Permission node: *

### ISSUE THREAD

**Issue by ItsJepser** [sgtcaze/NametagEdit#269]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.2.0
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
You are 80 version(s) behind

**What plugins are you using? Type /plugins**
Luckyperms and NametagEdit

**Please explain your issue. How do you trigger it?**
When I give the developer rank the permission * he gets the owner tag in tab, while he should keep his developer tag in tab.

**Are there any errors in the console? Please use: https://pastebin.com**
No

**Comment by ItsJepser** [comment]
@sgtcaze

**Comment by WizzleBear** [comment]
Make the other tags false and only the Developer tag true.

**Comment by JustOneMoreBlock** [comment]
Hello,

@WizzleBear is correct. Just negate all the permissions for that specific rank.
