### ISSUE TITLE
Luckperms & group tags

### ISSUE THREAD

**Issue by TomLewis** [sgtcaze/NametagEdit#270]
Is there Luckperms support to show custom tags based on the users group they are in?

**Comment by kuzbear** [comment]
Since you haven't received an answer, I am using luckperms, once you have made your groups you do /nte group [groupname] permission [your desired permission, suggested "nte.groupname"] then add said permission to your luckperms group permissions and it works.

**Comment by TomLewis** [comment]
oh so it creates a permission per group. Sweet.

**Comment by JustOneMoreBlock** [comment]
That's correct. You setup your permission name in NametagEdit and then use your permission plugin to define those permissions.

If you have wildcard permissions, simply negate those permissions on that rank to get the desired tag you want.

If you're using MySQL, make sure you use the priority command in NTE.
