### ISSUE TITLE
MVdWPlaceholderAPI Error after installing NametagEdit.

### ISSUE THREAD

**Issue by Phyther** [sgtcaze/NametagEdit#273]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

paper 1.12.2 (git-paper-1421)

**What plugins are you using? Type /plugins**

AdvancedHelp.jar
  |   | AnimationLib.jar | JAR File | 325.13 KB | Mar 27 15:06 | Edit
  |   | AntiLaby.jar | JAR File | 148.69 KB | May 13 01:26 | Edit
  |   | AutoBroadcast.jar | JAR File | 9.34 KB | Mar 27 15:06 | Edit
  |   | Banknotes V2.jar | JAR File | 14.03 KB | May 01 01:40 | Edit
  |   | BetterChairs.jar | JAR File | 75.45 KB | Mar 27 15:06 | Edit
  |   | BossShopPro.jar | JAR File | 355.96 KB | May 26 17:43 | Edit
  |   | CalendarEvents.jar | JAR File | 97.86 KB | May 13 17:15 | Edit
  |   | ChestCleaner.jar | JAR File | 26.49 KB | Mar 27 15:06 | Edit
  |   | Clearlag.jar | JAR File | 112.77 KB | Mar 27 15:06 | Edit
  |   | CombatTagPlus.jar | JAR File | 204.81 KB | Mar 27 15:06 | Edit
  |   | CommandNPC-1.9.1.jar | JAR File | 80.58 KB | Mar 27 15:06 | Edit
  |   | CommandSpy.jar | JAR File | 2.72 KB | Mar 27 15:06 | Edit
  |   | CoreProtect_2.14.2.jar | JAR File | 268.97 KB | Mar 27 15:06 | Edit
  |   | Crazy Auctions[v1.2.4].jar | JAR File | 57.16 KB | May 08 00:37 | Edit
  |   | CrazyCrates[v1.7.4.6].jar | JAR File | 265.39 KB | Apr 30 03:31 | Edit
  |   | CrazyEnchantments[v1.7.9.3.7].jar | JAR File | 358.67 KB | Mar 27 15:06 | Edit
  |   | CustomCommands_v2.4.0.jar | JAR File | 45.53 KB | May 06 00:24 | Edit
  |   | DailyRewards.jar | JAR File | 41.09 KB | Mar 27 15:06 | Edit
  |   | DeluxeChat-1.12.3.jar | JAR File | 105.91 KB | Mar 27 15:06 | Edit
  |   | DeluxeTags.jar | JAR File | 69.01 KB | Mar 27 15:06 | Edit
  |   | DiscordSRV-Build-1.16.3.jar | JAR File | 9.77 MB | Jun 02 13:15 |  
  |   | EnjinMinecraftPlugin.jar | JAR File | 1.75 MB | Mar 30 00:23 |  
  |   | EpicRename v3.3.1.jar | JAR File | 95.85 KB | Apr 30 19:15 | Edit
  |   | EssentialsX-2.15.0.2.jar | JAR File | 1.16 MB | May 04 00:21 |  
  |   | EssentialsXSpawn-2.15.0.2.jar | JAR File | 17.82 KB | May 04 00:21 | Edit
  |   | ExperienceBottle.jar | JAR File | 28.02 KB | Mar 27 15:06 | Edit
  |   | GhostBlockKiller_Limited.jar | JAR File | 8.7 KB | Apr 30 19:27 | Edit
  |   | GuiRedeemMcmmo.jar | JAR File | 17.15 KB | Apr 27 21:29 | Edit
  |   | Heads.jar | JAR File | 1.42 MB | Apr 23 19:04 |  
  |   | HolographicDisplays (2).jar | JAR File | 506.46 KB | Mar 27 15:06 | Edit
  |   | Item-NBT-API.jar | JAR File | 34.94 KB | Apr 12 14:50 | Edit
  |   | ItemTags.jar | JAR File | 12.93 KB | Mar 27 15:06 | Edit
  |   | Jobs4.5.3.jar | JAR File | 776.21 KB | Apr 10 17:07 |  
  |   | Lottery.jar | JAR File | 92.46 KB | Apr 30 19:41 | Edit
  |   | LuckPerms-Bukkit-4.2.2.jar | JAR File | 1.27 MB | May 08 04:43 |  
  |   | MVdWPlaceholderAPI.jar | JAR File | 6.93 KB | Mar 27 15:06 | Edit
  |   | MoreFish.jar | JAR File | 103.17 KB | May 11 02:45 | Edit
  |   | Multiverse-Core-2.5.0.jar | JAR File | 1.65 MB | Mar 27 15:06 |  
  |   | Multiverse-Portals-2.5.0.jar | JAR File | 103.84 KB | Mar 27 15:06 | Edit
  |   | MythicMobs-4.3.2-SNAPSHOT.jar | JAR File | 6.43 MB | Apr 30 19:49 |  
  |   | NametagEdit.jar | JAR File | 276.47 KB | May 19 18:48 | Edit
  |   | PlaceholderAPI-2.8.2.jar | JAR File | 103.22 KB | Mar 27 15:06 | Edit
  |   | PlayerParticles+v5.1.jar | JAR File | 322.49 KB | Apr 23 19:08 | Edit
  |   | PlayerVaultsX.jar | JAR File | 64.66 KB | Apr 15 03:45 | Edit
  |   | PluginHider+ 2.5.jar | JAR File | 9.46 KB | Apr 29 16:26 | Edit
  |   | ProtocolLib.jar | JAR File | 1.37 MB | Mar 27 15:06 |  
  |   | PyrCore_v3.3.2.jar | JAR File | 570.83 KB | May 17 15:34 |  
  |   | Rankup (1).jar | JAR File | 100.89 KB | Mar 27 15:06 | Edit
  |   | ShopChest.jar | JAR File | 319.81 KB | Mar 27 15:06 | Edit
  |   | SilkSpawners.jar | JAR File | 240.78 KB | May 21 05:13 | Edit
  |   | SimpleUnname.jar | JAR File | 38.88 KB | Mar 27 15:06 | Edit
  |   | SpawnerShop.jar | JAR File | 15.51 KB | Mar 27 15:06 | Edit
  |   | SponsoredSlots.jar | JAR File | 133.09 KB | May 21 19:34 | Edit
  |   | Staff+.jar | JAR File | 480.05 KB | Apr 29 17:09 | Edit
  |   | StickyLocks-0.11.jar | JAR File | 28.18 KB | Mar 29 17:50 | Edit
  |   | TAB1.7.0.jar | JAR File | 74.24 KB | Apr 08 09:32 | Edit
  |   | TokenManager-3.1.0.jar | JAR File | 1.93 MB | Jun 02 13:15 |  
  |   | Towny.jar | JAR File | 899.34 KB | May 22 05:00 |  
  |   | TownyChat.jar | JAR File | 91.6 KB | Apr 03 18:04 | Edit
  |   | TownyFix.jar | JAR File | 1.93 KB | May 03 15:44 | Edit
  |   | TownyNameUpdater.jar | JAR File | 3.87 KB | Mar 27 15:06 | Edit
  |   | Trading_v3.2.jar | JAR File | 26.37 KB | May 08 01:58 | Edit
  |   | TrailGUI-5.15-SNAPSHOT.jar | JAR File | 57.75 KB | Mar 27 15:06 | Edit
  |   | TrollCommandsPlusPlus-Bukkit-6.28.53.jar | JAR File | 2.73 MB | Apr 30 06:05 |  
  |   | UltimateBossBar.jar | JAR File | 43.61 KB | Mar 27 15:06 | Edit
  |   | UltimateCasino.jar | JAR File | 49.87 KB | Mar 27 15:06 | Edit
  |   | UltimateFireworks 1.9.9.jar | JAR File | 160.41 KB | Apr 30 20:21 | Edit
  |   | Vault (1).jar | JAR File | 289.95 KB | Mar 27 15:06 | Edit
  |   | Vouchers[v1.6.5.3].jar | JAR File | 70.56 KB | Mar 27 15:06 | Edit
  |   | VoxelSniper-5.171.0-SNAPSHOT.jar | JAR File | 3.46 MB | Mar 27 15:06 |  
  |   | WildTp.jar | JAR File | 155.38 KB | Jun 02 13:15 | Edit
  |   | WordGames+ V1.1.2.jar | JAR File | 36.31 KB | Apr 12 23:34 | Edit
  |   | backpacksplus.jar | JAR File | 75.5 KB | Apr 17 02:18 | Edit
  |   | citizens-2.0.22-SNAPSHOT.jar | JAR File | 2.28 MB | May 18 03:05 |  
  |   | iDisguise (1).jar | JAR File | 265.64 KB | Mar 27 15:06 | Edit
  |   | mcMMO.jar | JAR File | 1.24 MB | Apr 07 13:19 |  
  |   | multiverse-inventories_1.9.jar | JAR File | 1.17 MB | Mar 27 15:06 |  
  |   | nuvotifier.jar | JAR File | 5.09 MB | Apr 10 17:07 |  
  |   | worldedit-bukkit-6.1.7.3.jar | JAR File | 1.65 MB | Mar 27 15:06 |  
  |   | worldguard-6.2.1 (1).jar

**Please explain your issue. How do you trigger it?**
Everytime a player logsin I get the MVdWPlaceholderAPI error. This started after installing NametagEdit.

**Are there any errors in the console? Please use: https://pastebin.com**
03.06 01:31:15 [Server] ERROR [MVdWPlaceholderAPI] Unable to replace placeholders. No MVdW Placeholder plugin found!

**Comment by JustOneMoreBlock** [comment]
Hello,

You probably need to install the `PlaceHolderAPI` version.
https://www.spigotmc.org/resources/placeholderapi.6245/

https://www.spigotmc.org/wiki/placeholderapi-placeholders/#mvdw-placeholders

```
/papi ecloud download MVdW
```

Restart the server once this has been installed.
