### ISSUE TITLE
tab doesnt work

### ISSUE THREAD

**Issue by xXBlazeCraftXx** [sgtcaze/NametagEdit#274]
the plugin works fine but tab wont display anything?

**Comment by JustOneMoreBlock** [comment]
Hello,

Please check your config file.

```
Tablist:
  # If Enabled, NametagEdit will format the Tab menu
  Enabled: true
```

It possibly could be out of date.
https://github.com/sgtcaze/NametagEdit/blob/master/src/main/resources/config.yml

Make sure you make the necessary changes to ensure your plugin fully works.

If the issue persists, please re-open.

Kind Regards,
Cory

**Comment by xXBlazeCraftXx** [comment]
For some reason my players are getting the owner tag on tab which is #1 in priorities. WHen they have the permission for something else which is around #13. Yeah that's on in config. But when they join they get the "Owner" tag unless if I manually add the permission for the other one.
