### ISSUE TITLE
Not working with LuckPerms

### ISSUE THREAD

**Issue by BrettPlays** [sgtcaze/NametagEdit#277]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.8.8-R0.1-SNAPSHOT

**What plugins are you using? Type /plugins**
FeatherBoard, Vault. LuckPerms

**Please explain your issue. How do you trigger it?**
I got LuckPerms installed and no matter what I try, the tab does not update when I change my group in LuckPerms.  It worked fine in Pex but refuses to work now.

**Are there any errors in the console? Please use: https://pastebin.com**
No but there is this: `> [01:54:18 INFO]: [NametagEdit] [DEBUG] Trying to use MVdWPlaceholderAPI for placeholders
> [01:54:18 INFO]: [NametagEdit] [DEBUG] Trying to use PlaceholderAPI for placeholders
> [01:54:18 INFO]: [NametagEdit] [DEBUG] Trying to use MVdWPlaceholderAPI for placeholders
> [01:54:18 INFO]: [NametagEdit] [DEBUG] Trying to use PlaceholderAPI for placeholders
> [01:54:18 INFO]: [NametagEdit] [DEBUG] BrettPlayMC already belongs to a similar team (IJKJO_A3)`

**Comment by JustOneMoreBlock** [comment]
You probably need to make these are installed using PlaceHolderAPI:
```
/papi ecloud download LuckPerms
/papi ecloud download MVdW
```

**Comment by BrettPlays** [comment]
nope still nothing

**Comment by MagiskSec** [comment]
Could you give a full console dump (redacting anything sensitive) + run /plugins in this dump.

**Comment by danjono** [comment]
@BrettplayMC I've tried to replicate this with LuckPerms and my team changes correctly when I set a new group.

Try the latest dev build at https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by BrettPlays** [comment]
This ticket is no longer relevant to me. :P
