### ISSUE TITLE
Dissapears after a few seconds

### ISSUE THREAD

**Issue by UnlimitedNinjas** [sgtcaze/NametagEdit#278]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.2.3

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.12.2
just incase you need something else and not that version:
https://gyazo.com/4039e0484df9cf31e664ea2457d5a783

**What plugins are you using? Type /plugins**
sorry they are private
permission plugin is PEX.
Also i have tablist plugin

**Please explain your issue. How do you trigger it?**
Whenever i reload the plugin it shows the tag for a few seconds (5-10 seconds). But then dissapears
for tab and from the nametag

**Are there any errors in the console? Please use: https://pastebin.com**
this is the only thing that comes up in console, with debug enabled
https://pastebin.com/yKynYtXj

**Comment by JustOneMoreBlock** [comment]
Hello,

What tab list plugin are you using if it's a plugin on Spigot/Bukkit?

Have you tried disabling the tab list plugin to see if you yield the same results?
