### ISSUE TITLE
Automatically read permission prefixes and suffixes

### ISSUE THREAD

**Issue by BearLeon** [sgtcaze/NametagEdit#279]
I hope to add a function
Automatically read the prefix and suffix in the permission plug-in, and then automatically change the player tag

**Comment by BearLeon** [comment]
I can't speak English very much. I try to use google translate + yahoo translation to send the text and answer.

**Comment by JustOneMoreBlock** [comment]
You can already automatically accomplish this by setting up all the ranks, and permissions with your permission plugin.
