### ISSUE TITLE
Spigot sitesinde indirme linki çalışmıyor

### ISSUE THREAD

**Issue by Blondie8** [sgtcaze/NametagEdit#280]
# Bug Report

**Type /ver NametagEdit and post the output.**

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

**What plugins are you using? Type /plugins**

**Please explain your issue. How do you trigger it?**

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by Blondie8** [comment]
https://www.spigotmc.org/resources/nametagedit.3836/ 
Bu sitede göndermiş olduğunuz indirme linki çalışmıyor, lütfen düzeltiniz.

( Please fix the download link on this site. Link not working )

**Comment by JustOneMoreBlock** [comment]
done
