### ISSUE TITLE
[BUG] White nicknames on 1.13 pre-6

### ISSUE THREAD

**Issue by Feerko** [sgtcaze/NametagEdit#283]
# Bug Report

**Type /ver NametagEdit and post the output.**
<img width="307" alt="zrzut ekranu 2018-07-04 o 20 03 14" src="https://user-images.githubusercontent.com/16988054/42290402-4eb20764-7fc5-11e8-883c-d1ee3d55ad3e.png">

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.12.2
<img width="618" alt="zrzut ekranu 2018-07-04 o 20 03 36" src="https://user-images.githubusercontent.com/16988054/42290414-5deec29e-7fc5-11e8-89bd-37171e293c27.png">

**What plugins are you using? Type /plugins**
ViaVersion allows join on 1.13 pre-6

**Please explain your issue. How do you trigger it?**
<img width="258" alt="zrzut ekranu 2018-07-04 o 20 02 47" src="https://user-images.githubusercontent.com/16988054/42290425-6b0718c8-7fc5-11e8-85c3-dda0fc0e1765.png">

Prefix and suffix works, but nickname of player is white.

**Comment by MagiskSec** [comment]
This is due to how the scoreboards/teams have changed in 1.13 (which fundamentally changes how NTE works) - this will either need ViaVersion to look in to this **OR** updating this build to 1.13

#298 is where the most progress I have seen on it is.

**Comment by JustOneMoreBlock** [comment]
Closing and refer to #298
