### ISSUE TITLE
Tags changing to Member <name>

### ISSUE THREAD

**Issue by orbitly1** [sgtcaze/NametagEdit#284]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.2.0
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running CraftBukkit version git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
You are running the latest version

**What plugins are you using? Type /plugins**
Plugins (24): WorldEdit, NametagEdit, HolographicDisplays, TablistPrefix, OreGenerator, WorldGuard, SuperTrails, MaxBans, VoidGenerator, PermissionsEx, Vault, ChairStairs, ChatColor, ChestShop, CommaMoney, SpawnerShop, Essentials, uSkyBlock, SilkSpawners, SignColors, EssentialsXMPP, EssentialsChat, EssentialsGeoIP, EssentialsSpawn

**Please explain your issue. How do you trigger it?**
When I log on, usernames are the ones I set it to in tab and in-game. After about 2 minutes it changes to Member <name> which I didn't choose. I use groups. Also if I do /nte reload it goes back to normal but it resets after 2 minutes to Member <name>.

**Are there any errors in the console? Please use: https://pastebin.com**
No

**Comment by JustOneMoreBlock** [comment]
Hello,

Can you confirm this issue persists with the latest download of our build? Also, if you still have `TablistPrefix` can you disable to plugin momentarily, and see if it's conflicting.

Kind Regards,
- Cory
