### ISSUE TITLE
Bold Perm Variable

### ISSUE THREAD

**Issue by MrButtersDEV** [sgtcaze/NametagEdit#287]
Request:
Can we have a bold variable that can have a default tab be [rank] but if you have 2 perms ie tag.rank & tag.bold your tag can be [**rank**]

**Comment by JustOneMoreBlock** [comment]
Hello,

Why I can understand your purpose for this feature. At the moment, this can be accomplished by creating similar ranks just the added `bold` option, and permission node.

Example:
```
tag.rank: [rank]
tag.rank.bold: **[rank]**
```

Kind Regards,
- Cory
