### ISSUE TITLE
Nametag consistent colour

### ISSUE THREAD

**Issue by KazOnline** [sgtcaze/NametagEdit#288]
# Bug Report

**Plugin Version**
NametagEdit version 4.2.0
Authors: sgtcase and Cory

**Server version**
This server is running CraftBukkit version git-Spigot-eb3d9zi-b9fi615 )MC: 1.12.2) (Implementing API version 1.12.2-RO.1-SNAPSHOT)

**Server Plugins**
CoreProtect, Questioner, PlaceholderAPI, BetterChairs, NametagEdit, RelaAutoBroadcast, MorePlayerModels2, Multiverse-Core, ProtocolLib, LibsDisguises, AdvancedPortals, TimeManager, FastAsyncWorldEdit, VoxelSniper, PermissionsEx, Vault, StopPushing, Lores, WorldEdit, Essentials, MarriageMaster, HeadDatabase, LWC, SafeTrade, WorldGuard, Brewery, Citizens, DeluxeMenus, AddLight, SuperVanish, MagicSpells, EnjinMinecraftPlugin, RPGItems, Towny, SilkSpawners, TownyChat, TownyNameUpdater, ShopChest, MyPet

**Our Issue**
This is not a massive issue, but it is annoying due to the purpose we're using this plugin for. I've searched for hours for a plugin that would work automatically in 1.12 and can't find one, but we wanted a plugin that set the Tablist and Nametag prefix and colours based on Pex prefixes, which is possible with this through permissions, but we wanted custom prefixes as well and we found a much easier way to set it up with the way our prefixes are currently added(through a GUI script). Our issue isn't a "bug" perse, only that in the tablist the Username and Prefix colour codes are different(the way we set it up through the command) but in the nametag above the player the whole line(prefix and username) both use the beginning colour code used for the prefix.
EDIT: We have discovered that this works fine, but the colour codes for longtags don't load in at the end, only the original colour codes(at the beginning of the prefix tag eg: '&6&lHalf-Goblin &e&o' sets the name to all Bold and Gold, where as '&6&lHuman &e&o' would work fine, having a Hold and Bold prefix and a Yellow Italic username.)

**Console Errors*
_Null_

**Comment by JustOneMoreBlock** [comment]
Hello,

Did you make sure `long tags` was enabled? This is only used for the tab-list.

If you're trying to get `&6&lHalf-Goblin &e&o` to work on `above name`. Unfortunately, the Minecraft limitation of 16 characters will exceed this. However. it should work fine in tab-list.

Once Spigot 1.13 has been released the `16 character limit` would allow for more. However, it would likely cut off on older versions.

- Kind Regards,
Cory
