### ISSUE TITLE
groups prefix shorter

### ISSUE THREAD

**Issue by PhanaticD** [sgtcaze/NametagEdit#29]
it looks like entries in the groups.yml have a much shorter limit than if you set the prefix using the command

**Comment by JustOneMoreBlock** [comment]
What do you mean?

**Comment by PhanaticD** [comment]
I posted a picture on spigot thread, that is what happens if I try to set a longer prefix using the groups.yml

**Comment by JustOneMoreBlock** [comment]
Are you trying to add a space? If so, you need to write the command with single-quotes.

`/ne prefix Owner '&a[&4Owner&a] &r'`

Keep in mind with the space and the &r or color you use is 16 characters and it's the max limit you can do.
