### ISSUE TITLE
Not work with Cauldron-1.7.10-1.1236.05.212

### ISSUE THREAD

**Issue by fatdog66** [sgtcaze/NametagEdit#29]
hi,
i have that error in log (http://pastebin.com/5J6KCpcE) when i use NTE 3.0 build 2 (feb 6) on Cauldron-1.7.10-1.1236.05.212. Plugin load correctly but the error appear when a ranked player log in game. The tab not work and player name not work too. please help me.

sorry for my english, i'm french

Edit: I use only one mod on cauldron (terrafirmacraft) and plugins permissionEx, essentials (+ spawn and chat), we, wg, vote and NTE.

**Comment by Darkool** [comment]
Hello, i can't found #9 build on jenkins, to use on spigot protocol hack, it is missing?

**Comment by fatdog66** [comment]
i don't know

**Comment by sgtcaze** [comment]
I will look into this for you. Perhaps it is the reflection that is causing this.

**Comment by fatdog66** [comment]
reflection ? What is it sgtcaze ? Can i solve them ? thx

**Comment by sgtcaze** [comment]
Reflection allows us to dynamically load classes that would otherwise be different per version.

We're also looking into abstraction to provide support for more than just Craftbukkit/Spigot.

**Comment by fatdog66** [comment]
You mean I will open a support ticket with cauldron ?

**Comment by fatdog66** [comment]
I have closed the cauldron server and i have found solution whith scoreboard. Closed!

**Comment by FiveEYZ** [comment]
Reviving this one as i dont wanna make a duplicate of the same issue.

yes its still occurring using http://ci.playmc.cc/job/NametagEdit/19/ on KCauldron:1.7.10-1614.199 Official https://gitlab.prok.pw/KCauldron/KCauldron

got this when i tried to do /nte prefix <name> <value>
http://pastebin.com/guzG6Sah

and every time some one joins i get:
http://pastebin.com/qYAbkjfr
