### ISSUE TITLE
[Suggestion] Below name editor

### ISSUE THREAD

**Issue by WizzleBear** [sgtcaze/NametagEdit#291]
Add a nameplate to the bottom of the name like [HealthBar](https://dev.bukkit.org/projects/health-bar) and [Animated Names](https://www.spigotmc.org/resources/animatednames.2175/) where we can add extra information like health, XP, etc.

**Comment by JustOneMoreBlock** [comment]
I've used HealthBar on NametagEdit at one point. However, with a lot of code changes over the years, it could have changed.

Does this no longer work for you?

**Comment by WizzleBear** [comment]
HealthBar does work, but I thought it would be good to add so you can compete with other plugins.

**Comment by JustOneMoreBlock** [comment]
I'm all for being included with plugins. Not competing against them per say. NametagEdit is the first Nametag plugin to be created. Therefore, everyone technically competes with me.

Unfortunately, I've seen and tested similar plugins, and they work as intended.
