### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [sgtcaze/NametagEdit#293]
Hey,

Could you add 1.13 support ?

Thanks ! :D

**Comment by JustOneMoreBlock** [comment]
I would like to. However, my friend and dev seem to have disappeared. :(

So, might need to reach out to some friends for some assistance.

**Comment by TheIntelloBox** [comment]
Give me some news when you can. :)

**Comment by sixamscrew** [comment]
Yes, please. We need 1.13 support ;P

**Comment by Xaviite** [comment]
@JustOneMoreBlock 
Any update on 1.13 support?
I am not a plugin developer but work as a software engineer, so might be able to be of some use if you need it. Are you a developer on this plugin?

**Comment by JustOneMoreBlock** [comment]
Closing and refer to #298
