### ISSUE TITLE
deleted #9 build on jenkins

### ISSUE THREAD

**Issue by Darkool** [sgtcaze/NametagEdit#30]
Hello, i can't found #9 build on jenkins, to use on spigot protocol hack, it is missing?

**Comment by sgtcaze** [comment]
Build 4 Should be compatible no problem

http://ci.playmc.cc/job/NametagEdit/4/

**Comment by Darkool** [comment]
its necesary do something more?, because plugin load on protocol hack, but when i join with 1.8.1 version, i can't see colors in tab or tag, and i not recive any message about the prefix was changed with /ne prefix command. thanks for your support

**Comment by sgtcaze** [comment]
Yes you will not receive a confirmation message for now. The messages are being modified and re-added. As for 1.8.1, this was a known issue with the Protocol hack. 1.8 < clients could see Nametags fine, but 1.8.1 couldn't.

Running a non protocol-hack 1.8 server shows the tags fine for both 1.8 and 1.8.1. 

If you're on a server with a 1.8.1 client and you can see nametags, I believe they are using actual scoreboards and not the PacketPlayOutScoreboardTeam packet that we use. I could be wrong though.

**Comment by Darkool** [comment]
ok, i understand, thanks for supporting

**Comment by sgtcaze** [comment]
Thank you for reporting! If you need more help just open a new issue.

**Comment by Darkool** [comment]
Recently i have tested with 1.8 and protocol hack and i still can't see my
tag on tab, maybe its not the correct build?

**Comment by sgtcaze** [comment]
You tested with Spigot 1.8? Which build number? 

If you're on a 1.8.1 client on a 1.8-protocol hack server the tags won't display properly with NametagEdit. We've tested 1.8 support with NametagEdit and everything worked fine (on 1.8+1.7 clients)

**Comment by Darkool** [comment]
No no, im on spigot protocol hack, but on launcher 1.8 of minecraft, im
understand this, but i think that im wrong, sorry
