### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by BeefSoup** [sgtcaze/NametagEdit#301]
# Bug Report

V-4.2.1
Spigot-NTE

In 1.13 the ranks do show up in the tab but there are no priorities like there were in 1.12. Is there a 1.13 build that will fix this and many of the other issues?

**Please explain your issue. How do you trigger it?**

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by MagiskSec** [comment]
#298 - read before posting issues - you just waste everybody else's time!

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar
