### ISSUE TITLE
Dependency problem, an error

### ISSUE THREAD

**Issue by KIZAFOX** [sgtcaze/NametagEdit#307]
# Bug Report

Hello ! My name is KIZAFOX, I wanted to use your API but the only problem is that in the pom.xml (I use Maven) there is an error, here is a screen + my pom.xml. I hope you can help me. Good end of the day or evening.

Screen: https://image.noelshack.com/fichiers/2018/35/6/1535814015-error.png
Pastebin: https://pastebin.com/67QidiUG

**Comment by danjono** [comment]
You're not giving it a location to where the dependency is located so it can use the NametagEdit classes. You either have to supply a maven repository it's hosted on, have the maven data already cached in your .m2 folder or you supply the JAR yourself.

In your case, I'd go with the last option.

Create a folder where your src folder is called lib and drop the NametagEdit.jar inside it. Then update your pom.xml to the following

https://pastebin.com/B14SeseF
