### ISSUE TITLE
RRefresh Interrval Bug

### ISSUE THREAD

**Issue by dabou0** [sgtcaze/NametagEdit#308]
# Bug Report

**Type /ver NametagEdit and post the output.**

NametagEdit version 4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Spigot 1.12.2

**What plugins are you using? Type /plugins**

**Please explain your issue. How do you trigger it?**

When i join with one account, it will show for me in the tab the name formated, but when i join with the  second account, it wont show the first account formated for me, only my own name, but for the first account it will show both, this is due, nametag refreshintervel, so for example, if i put a 10 seconds refresh interval, after 10 seconds the second account will be able to see the first account formatted,
so the solution would be to refresh to everyone on join, or another one that i dont know

**Are there any errors in the console? Please use: https://pastebin.com**
no errors

**Comment by JustOneMoreBlock** [comment]
I use these settings:

```
RefreshTagOnWorldChange: false
```

```
RefreshInterval: 0
```
