### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by Cnly** [sgtcaze/NametagEdit#31]
Hi, I cloned your repo and imported to my IDE but I found the following errors:

* The method getInstance() is undefined for the type NametagEdit
* The method getNteHandler() is undefined for the type NametagEdit

And more like those...
Do you have anything in your local repo updated but not pushed? Could you please have a check?
Thank you.

**Comment by sgtcaze** [comment]
Make sure the pom.xml is being parsed correctly. Perhaps the lombok dependency is not in use (this is required)

**Comment by Cnly** [comment]
I use Eclipse but I didn't find there's anything wrong with the pom.xml or dependencies.
Also, I had a look at the commit https://github.com/sgtcaze/NametagEdit/commit/043d9af8f445208f11916d691d1f8b15687c1cd3, and found that the methods I mentioned were deleted in this commit.

**Comment by sgtcaze** [comment]
The project is compiling fine for me

The @Getter tags (seen here https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/ca/wacos/nametagedit/NametagEdit.java#L31-L35)  control that

**Comment by Cnly** [comment]
Oh, I tried running `mvn clean package` and it worked well. But Eclipse is not so smart. Is there any way to deal with that?

**Comment by sgtcaze** [comment]
Sorry for the delay. What issues are you still facing? To fix some maven ghosting problems: Right click project > Maven > Update Project

**Comment by Cnly** [comment]
I mean the compliation is fine, but Eclipse doesn't know the @Getter
annotation, so it keeps giving errors. Is there any way to deal with that?

**Comment by sgtcaze** [comment]
Yes this is an issue with not being able to resolve the "Lombok" dependency
