### ISSUE TITLE
Confusion regarding NTE and PEX working together

### ISSUE THREAD

**Issue by TrickySpot** [sgtcaze/NametagEdit#310]
# Bug Report

**Type /ver NametagEdit and post the output.**
Version 4.3

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
CraftBukkit - Git-Spigot-2cf50f0-2b93d83

**What plugins are you using? Type /plugins**
CoreProtect, WorldEdit, VotingPlugin, Discord-ProgramVot-API, PermissionsEx, DiscordChatWM, NameTagEdit, Vault, Votifier, GriefPrevention, ProtocolLib, Citizens, Shopkeepers, Essentials, ChatControl, SuperVanish, EssentialsSpawn

Hi, when starting my server, NTE says its found PEX, gives no errors, but after that nothing in-game is different. When I read that NTE supports PEX, I assumed that NTE would talk to PEX to get the prefixes etc (from the PEX yaml files) and format the players names and the tab list accordingly....is this correct, or do I manually have to populate group.yml and players.yml to emulate whats already in PEX? What am I missing, surely you can't be editing players.yml for every new player that joins? 

Thanks for the help in advance!

Kind Regards,
TrickySpot

**Comment by MagiskSec** [comment]
NameTagEdit doesn't pick the prefixes straight from PEX, you have to define them within NameTagEdit.

For example, say if you have an admin group and you wish them to have a red NameTag, in groups.yml

you would do something like

```
 Groups:
  Admin:
    Permission: nte.admin
    Prefix: '&c&lAdmin&r&c '
    Suffix: '&f'
```
and assign the Admin group "nte.admin" 

If you want a specific player to have a specific nametag, you need to define this in NTE yourself too - the plugin does not take this data from PEX, it supports it based on permission nodes and not automatically importing the prefixes/suffixes.

**Comment by JustOneMoreBlock** [comment]
But you can. :)

https://github.com/sgtcaze/NametagEdit/issues/324
