### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by skino0** [sgtcaze/NametagEdit#311]
Dude i cant download your plugin when i  click download (with external website)  the page say unavailable some gone wrong , days now wait to fix it and cant download..........

**Comment by MagiskSec** [comment]
If you're having issues - try from this link: https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by JustOneMoreBlock** [comment]
Yeah, this was fixed and you can now download directly from SpigotMC.
