### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#312]
# Bug Report

**Type /ver NametagEdit and post the output.**

NametagEdit version 4.3.0
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)

**What plugins are you using? Type /plugins**

CoreProtect, BloodEffects, WorldEdit, MaxBans, KingdomWands-Premium, Essentials, EssentialsProtect, EssentialsGeoIp, EssentialsChat, PermissionsEx, EasyChatClear, PunchWood, NametagEdit, HolographicDisplays, Tablist, EssentialsSpawn, Kingdoms, SimpleSit, WorldGuard

**Please explain your issue. How do you trigger it?**

The prefix in tab removes when you chat or rejoin then you need to reload the plugin!

**Are there any errors in the console? Please use: https://pastebin.com**

No

**Comment by JustOneMoreBlock** [comment]
Tested and can confirm this doesn't happen. Possibly could be conflicting with your `Tablist` plugin.
