### ISSUE TITLE
Hide NameTags

### ISSUE THREAD

**Issue by Roper89** [sgtcaze/NametagEdit#313]
You can add the ability to hide NameTags?
NameTags makes the player visible through the walls.
I want players to not have NameTags.

**Comment by MagiskSec** [comment]
This isn't available in NTE (right now) as far as I am aware - but this is possible in Vanilla minecraft (and could be added in a PR to NTE potentially)

If you create a scoreboard team and add all your players (or players who need the scoreboard) you can use the "nametagVisibility" option to hide this.

**Comment by JustOneMoreBlock** [comment]
Hello,

Nametags are hidden if you use vanish. However, if you using 1.8.8 there is a bug that cannot be fixed.

Kind Regards,
Cory
