### ISSUE TITLE
Scoreboard Compatibility

### ISSUE THREAD

**Issue by iBars** [sgtcaze/NametagEdit#32]
Hello. NTE is incompatible with other plugins which using Scoreboard features. Make please setting prefixes only while sending packets and compare with current player prefix as new team (configurable) and only if player team attribute 'setFriendlyInvisibles' setted to false (configurable). It may help you: http://dev.bukkit.org/bukkit-plugins/protocollib/forum/63402-send-score-board-team-prefix-above-head/#p4. And also I have to suggest you make using default chat formatting but with replace player name with prefix+name+suffix (name or displayname is configurable). BIG BIG THANKS! :)

**Comment by sgtcaze** [comment]
I will add this to the "TODO". We'll consider extending the API to allow plugin developers to add compatibility as well. Though, we probably won't add ProtocolLib compatibility. We'll see.
