### ISSUE TITLE
What you see isnt what you get.

### ISSUE THREAD

**Issue by kuzbear** [sgtcaze/NametagEdit#320]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.3.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
paperspigot 1.13.2

**What plugins are you using? Type /plugins**
lots

**Please explain your issue. How do you trigger it?**
When /nte group list is used there is a second colour code that is registered and shown, when you see the tag above a players/staffs head the second colour code isnt noticed.

**Are there any errors in the console? Please use: https://pastebin.com**
No

![screenshot_30](https://user-images.githubusercontent.com/4545802/49119036-74c6e780-f2f2-11e8-8329-62317a4e80f5.png)

**Comment by JustOneMoreBlock** [comment]
Is your aqua and lime green bold? If so:

```
&b&lOperator &a&l
```
This is 17 characters and looks like it may be cutting you off.

**Comment by kuzbear** [comment]
"&b&lOperator &a" 15 characters which means it should be going green not staying aqua. Sorry it took me so long I was on holidays.
