### ISSUE TITLE
Problem setting up MySQL

### ISSUE THREAD

**Issue by LazyFace32** [sgtcaze/NametagEdit#323]
# Bug Report

**Type /ver NametagEdit and post the output.**
NameTag Edit v4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Spigot 1.12.2

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/20za2q7P

So I tried to setup MySQL but I'm not sure if something's wrong or if I just didn't set it up correctly?
Maybe it could be because I used the database address on the ' HostName ' part because I'm not sure if that's even what is suppose to be written there.

(Not exactly a bug report - maybe)

**Comment by JustOneMoreBlock** [comment]
Hello,

The `hostname` is the hostname/ip address provided by your host. Who's your provider?

Kind Regards,
Cory
