### ISSUE TITLE
MySQL SSL

### ISSUE THREAD

**Issue by korhox** [sgtcaze/NametagEdit#327]
# Bug Report

**NametagEdit version**
NametagEdit version 4.4.0
Authors: sgtcaze and Cory

**Server version**
This server is running CraftBukkit version git-Spigot-a1ba5fe-b4230a9 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Plugins used**
Plugins (1): NametagEdit

**Issue explained**
Just by starting server and before that, configured to use MySQL.

**Errors in the console**
This keeps spamming me several times at startup.
https://pastebin.com/0LwB7Pq6

**Comment by JustOneMoreBlock** [comment]
Hello,

Please try: https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

Build 48

No idea if this will fix the issue.

**Comment by JustOneMoreBlock** [comment]
Has this been resolved? If not, please re-open this issue.
