### ISSUE TITLE
Tab List Bug

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#33]
There is a tab list bug causing the rank to be removed from tab list.

Just happens randomly it seems.

http://i.imgur.com/hgxa6tl.png
http://i.imgur.com/5cg7LS4.png
http://i.imgur.com/rNBwrBZ.png

Using Spigot 1.9.2
This server is running CraftBukkit version git-Spigot-944aa20-8d16fc0 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

NametagEdit Build 28

Plugins (17): zPermissions, WorldEdit, PandoraChatFilter, FeatherBoard, Vault, ClearLag, MessageAnnouncer, ProtocolLib, HolographicDisplays, NametagEdit, WorldGuard, Essentials, PlotSquared, NoCheatPlus, EssentialsSpawn, DeluxeChat, TitleManager

Using MySQL
Groups based system
zPermissions

Tested this on my server prior and seemed to be an issue.
Tested this on another test server and didn't see to be an issue.
Tested this on an event server and seems to be an issue.
A lot of issues have been created in related and looks like I'm confirming they're may be some form of issue.

**Comment by sgtcaze** [comment]
Fascinating. I am observing this on TEI as well. Perhaps this is a 1.9.2 issue. See #34 for a followup.

**Comment by JustOneMoreBlock** [comment]
Error in CONSOLE.

Latest Spigot 1.9.2

http://pastebin.com/raw/zrHkU5f0

Figure, this maybe related.

**Comment by sgtcaze** [comment]
```
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
```

Looks like that is an issue with server version and incorrect version of the plugin.

**Comment by JustOneMoreBlock** [comment]
Well, I'm using the latest 1.9.2 and Build 28. So I don't know.

**Comment by JustOneMoreBlock** [comment]
Seems to fixed in build 30.

Tested with Spigot 1.9.4
