### ISSUE TITLE
PermissionsEX Compatibility

### ISSUE THREAD

**Issue by Faller10** [sgtcaze/NametagEdit#33]
I use PemissionsEx..
But I don't know if the plugins works, because I configured the permissions and did it all right, but my players don't have the tags and sometimes they get the tags but it's from another group!

OBS: The tags are only buggy in the tablist, in the player's head its ok!
(Yes I have the "TabListDisabled" option set to true!)

**Comment by Kalorte** [comment]
Same problem with the last version, don't use last version !

**Comment by sgtcaze** [comment]
Thanks for the report. Can I see your permissions file?

**Comment by davewolax** [comment]
I have this issue as well. name tags doesn't show up above players. I have set all things right.

**Comment by Kalorte** [comment]
Ok so I use PEX 1.23.1 with NTE: https://github.com/sgtcaze/NametagEdit/commit/c202057a59a9f6dc3a6db665222e0b3ad9af9a2d

NTE work but the Order seem's to doesn't work :/ 

My groups file: http://puu.sh/hfPSC/3bf7867b8d.yml

I'm a "fondateur" but I have the NTE "modo" :/
All the group have the correct permission. My group fondateur have the perms nte.fondateur, etc...

**Comment by sgtcaze** [comment]
Closing this until v3.0.1 (which will be updated soon).

There were numerous issues with 3.0.0 that have been resolved in the newest dev build.
