### ISSUE TITLE
NTE Color Counts as Prefix

### ISSUE THREAD

**Issue by anthoeknee** [sgtcaze/NametagEdit#336]
# Bug Report

**Type /ver NametagEdit and post the output.**
Version 4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
https://i.imgur.com/UinLdel.png

**What plugins are you using? Type /plugins**
https://i.imgur.com/AQZUzhX.jpg

**Please explain your issue. How do you trigger it?**
My issue is that I want to disable the fact that colour codes count as part of the prefix. It is currently messing up the brackets in our prefix's, and making us not use brackets, which is not what either server owners want.

**Are there any errors in the console? Please use: https://pastebin.com**
None that are related to nametagedit.

**Comment by JustOneMoreBlock** [comment]
Unfortunately, this is Mojang's limitation and we cannot alter this.
