### ISSUE TITLE
Titles Disappear 

### ISSUE THREAD

**Issue by ireeskenz** [sgtcaze/NametagEdit#34]
I got one problem. When i change world, nametag disappear. I use Multiverse Core and Permissions ex.

**Comment by JustOneMoreBlock** [comment]
Are you using the latest Build?

Build 28?

http://ci.playmc.cc/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by ireeskenz** [comment]
Of Course.

**Comment by sgtcaze** [comment]
I am experiencing a similar issue with a network I manage. Are you using 1.9.2? Did this occur in 1.9.0? Do you have a per-worlds permission plugin that refreshes permissions when you change the world?

**Comment by ireeskenz** [comment]
Yeah i'm using 1.9.2. I don't know if is it occur in 1.9.0 because i've discover plugin in 1.9.2. I don't have per-worlds permission (pex) and no plugin who refresh permissions when i change the world.

**Comment by JustOneMoreBlock** [comment]
#33 - Related.
