### ISSUE TITLE
Fix Jenkins

### ISSUE THREAD

**Issue by HeroCC** [sgtcaze/NametagEdit#35]
Hello! This isn't about code, but about your Jenkins Server. You say to use build #10 to get spigot 1.8.3 support, but your jenkins isn't building and only goes up to build #7. If you could fix this it would be great, I prefer not to compile it myself. Thanks!

**Comment by sgtcaze** [comment]
I switched Jenkins, and didn't bring any of the old files. So the builds are correct.

**Comment by HeroCC** [comment]
So build 7 is correct? Oh, you may want to change the readme to reflect that. Thanks!
