### ISSUE TITLE
LuckPerms Hook

### ISSUE THREAD

**Issue by kforbro** [sgtcaze/NametagEdit#354]
# Bug Report
https://imgur.com/a/wot084X
**Type /ver NametagEdit and post the output.**
4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

**What plugins are you using? Type /plugins**

**Please explain your issue. How do you trigger it?**

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by JustOneMoreBlock** [comment]
Hello,

Could you please try this build:
https://ci.nametagedit.com/job/NametagEdit-Dev/12/artifact/target/NametagEdit.jar
