### ISSUE TITLE
per world pls

### ISSUE THREAD

**Issue by Xandervyvey** [sgtcaze/NametagEdit#355]
hello i need help
i want to use the plugin but 
only for one world my faction
how can i disable this on all other worlds?
pls help me

**Comment by a7md1424** [comment]
there is other plugins do this

not the name tag edit + i don't know what is the plugin name

**Comment by Xandervyvey** [comment]
oke thx

**Comment by gelsbern** [comment]
If you are using a permissions plugin, you can do one of two things.  Either add the permissions specifically for the world only or negate the permission for all the other worlds.

so you can either:
/lp group groupname permission set nte.prefixname  false

then

/lp group groupname permission set nte.prefixname true world=factionworldname

the world specific permission will override the global one and they will only have the prefix in that world. 

**or** 

/lp group groupname permission set nte.prefixname true 
/lp group groupname permission set nte.prefixname false world=world1name
/lp group groupname permission set nte.prefixname false world=world2name
/lp group groupname permission set nte.prefixname false world=world3name
...

This means they will have the prefix by default and then you can shut it off per world.

The first method is far easier.

I am sure PermissionsEX works in a similar fashion.
