### ISSUE TITLE
( NameTagEdit + PermissionsEX )

### ISSUE THREAD

**Issue by a7md1424** [sgtcaze/NametagEdit#356]
i use PermissionsEX and NameTagEdit

1- /nte group add member
2- /nte group member prefix '&7VIP &7'
3- /nte group member permission nte.member

1- /nte group add vip
2- /nte group vip prefix '&aVIP &6'
3- /nte group vipp permission nte.vip

when i go to pex and add the nte.vip permission to the vip rank

and give someone the vip rank ( the name tag edit ) didn't change his name or the tags

it's just still on member prefix

**Comment by ItsSchatten** [comment]
Assuming that you are using inheritance, you will need to negate your member groups prefix from the VIP rank.

**Comment by JustOneMoreBlock** [comment]
https://github.com/sgtcaze/NametagEdit/wiki/Setup-Permissions
