### ISSUE TITLE
Erases a letter off username help me please

### ISSUE THREAD

**Issue by TsCode1** [sgtcaze/NametagEdit#36]
All my other ranks work perfectly fine. However, my &5[Grandmaster]&f rank does not. Let say my username is notch. It will show up as [Grandmaster]otch
If I remove a letter from it, it will work fine. If I add a letter, it will work fine. It is only at 13 numerals at which it starts to glitch.
I am using the most recent version of your plugin and I am on Spigot 1.8.3

Thank you

**Comment by JustOneMoreBlock** [comment]
Your current prefix/suffix has17 characters.
&5[Grandmaster]&f

The &5 counts as 2.

You can only have 16 Characters including color codes. Unfortunately, this is a Minecraft limitation and something we cannot change.

**Comment by TsCode1** [comment]
Well that's weird because if I add more letters than it suddenly works fine. Anyways thank you for explaining
