### ISSUE TITLE
Critical bugs that prohibit plugin usage.

### ISSUE THREAD

**Issue by Tantillus-KW1C** [sgtcaze/NametagEdit#361]
# Bug Report

**Type /ver NametagEdit and post the output.**

(https://prnt.sc/ns0kgz)
NametagEdit version 4.4.0
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Screen 1: server version
(http://prntscr.com/ns0le5)

**What plugins are you using? Type /plugins**

Screen 1: Plugins
(http://prntscr.com/ns0lp8)

**Please explain your issue. How do you trigger it?**

- When a player is opped or has * in permission nodes, player will always receive
the highest priority tag (or first tag that is in groups.yml file)
This bug also has effect in the tablist.

Screen 1: Tantillus in Dev rank without * in permissions nodes or OP
http://prntscr.com/ns0w9y
Screen 2: Tantillus in Dev rank witout * but with OP (with '*' in nodes same effect)
http://prntscr.com/ns0xqf

- Rare event where when a tag is configured as in example 1, the first letter of the player's name dissapears from the tablist and the normal client name (above head.)

Though, this bug only effects a few ranks. It's not either all groups have this bug, or none.
It appears to randomly remove the first letter of a players name.
This bug also has effect in the tablist.

Example 1
>   Dev:
    Permission: nte.dev
    Prefix: '&8[&3Dev&8] &r'
    Suffix: ''
    SortPriority: 2

Screen 1: Tantillus in Default(member) group.
http://prntscr.com/ns0zoa

Screen 2: Tantillus in Helper group.
http://prntscr.com/ns107h

Screen 3: Tantillus in Admin group.
http://prntscr.com/ns110y

- Some ranks will not receive configurated tag, but always receive the default (member) tag.
This problem presumed coïncidently occurs only with the donator ranks. The donator ranks 
happen to be the last in the groups.yml list. Is there a limit for tags?

Screen 1: Total list of all tags configured.
http://prntscr.com/ns15si

Screen 2: List of configured tags in game client.
http://prntscr.com/ns171o

**Are there any errors in the console? Please use: https://pastebin.com**

Screen 1: Alot of checking for placeholders.
http://prntscr.com/ns1d92

I personally am not an experienced coder or developer, I'm just extremely good at configuring plugins and doing it fast and good on minecraft servers. Though the bugs with this plugin are driving me crazy and makes this  plugin unusable for me.

**Comment by JustOneMoreBlock** [comment]
If you provide the `*` permission node. You need to put all the `nte permissions` in the rank with a wildcard as a false flag. Then at the end for the rank you want the tag make it true.

Quick Example:
```
# Group ADMIN
permissions group ADMIN create
permissions group ADMIN set nte.admin true
permissions group ADMIN set nte.srmod false
permissions group ADMIN metadata set prefix "&2&lADMIN &r"
permissions group ADMIN setweight 0
permissions group ADMIN setparents SR_MOD
permissions group ADMIN add 8afea857287c453d84c0231b2ac01968/_Keith
permissions group ADMIN add fc9795dc5e1e41e7933acca970e96073/JustPlayHere
# Group OWNER
permissions group OWNER create
permissions group OWNER set nte.admin false
permissions group OWNER set nte.owner true
permissions group OWNER set tab.group.owner true
permissions group OWNER set '*' true
permissions group OWNER metadata set prefix "&4&lOWNER &r"
permissions group OWNER setweight 0
permissions group OWNER setparents ADMIN
permissions group OWNER add 3716427e76ac4df4a50a706618a70f0c/Cory
```
In this case I don't have to list them all since all my ranks before inherit the previous `false` permission node.
