### ISSUE TITLE
Problem with permission "*"

### ISSUE THREAD

**Issue by SrDiegoFxZ** [sgtcaze/NametagEdit#365]
I have a problem, I can not put custom tags to those ranks with the permission "*" takes them as identical, this does not happen with those ranks that do not have the permission *

https://imgur.com/a/stjk1Sw

I have three groups with the permission "*" but the tag of none of them is not modified, just take the OWNER range as a reference. 

Also tags are bugued when putting &l or bold letter.

https://imgur.com/a/mctcCbf

My config: https://imgur.com/a/8aKjgcu

PermissionsEx: https://imgur.com/a/3zc4HhO

Im used tittle manager.

**Comment by JustOneMoreBlock** [comment]
https://github.com/sgtcaze/NametagEdit/wiki/Setup-Permissions
