### ISSUE TITLE
Formatting issue 

### ISSUE THREAD

**Issue by robert-beckley** [sgtcaze/NametagEdit#366]
# Bug Report

**Type /ver NametagEdit and post the output.**

![image](https://user-images.githubusercontent.com/41904721/59504076-67b3c380-8ee5-11e9-8ac2-5c4137b9e17e.png)

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
![image](https://user-images.githubusercontent.com/41904721/59504098-74d0b280-8ee5-11e9-8103-697518852e86.png)

(also tried on 1.14.2 latest Build) 

**What plugins are you using? Type /plugins**
![image](https://user-images.githubusercontent.com/41904721/59504125-92058100-8ee5-11e9-80f1-7cef7b3fc731.png)

Running a 1.13.2 Spigot Server. Latest Bungee Proxy. With ViaVerson on the Proxy. Tried with AutoTeam false & True.

Having issues with how the name tags show up. I'm trying to use this format Prefix: '&4&l[&cAdmin&4&l]&c' But in game it shows up like as if it was formatted as '&4&l[&cAdmin&4&l' so it displays the name as Red Bold and does not display the ] I have long prefixes true.

![image](https://user-images.githubusercontent.com/41904721/59504628-b31aa180-8ee6-11e9-97a7-97f91e7798a1.png)
![image](https://user-images.githubusercontent.com/41904721/59504657-c3328100-8ee6-11e9-8c22-3ba6c0ea59ad.png)

I have tried setting it in the groups.yml file, tried setting it in the game, tried adding it to a group & tried adding it directly to the player with no luck. When I use /nte groups the format it displays is correct. But it does not show that format in the game.

I have tried using the latest Build from http://ci.nametagedit.com:8080/job/NametagEdit/ I have used the Build linked to in the review section and I have used the Build that spigot gives.

I'm only using this for nametags, not tablist I have 14 groups and all have the same issue of not displaying correctly after the ]

[NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/3290299/NametagEdit.zip)

Edit: Image upload

**Comment by SrDiegoFxZ** [comment]
Hello, seeing your problem I do not know if you can help me in something, how to deactivate the autoteam ? I can not find it in the plugin configuration.

**Comment by robert-beckley** [comment]
@SrDiegoFxZ
If you are using ViaVersion its in the config.yml top line. Make sure to use the latest version.

**Comment by SrDiegoFxZ** [comment]
Thank you very much :D

**Comment by SrDiegoFxZ** [comment]
Last question, I can't change the tag to those ranks with the permission "*" do you know what I can do?

**Comment by SrDiegoFxZ** [comment]
My post: https://github.com/sgtcaze/NametagEdit/issues/365

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

Try that build
