### ISSUE TITLE
Nametags don't show above player's heads but in tablist only

### ISSUE THREAD

**Issue by NicholusParkus** [sgtcaze/NametagEdit#367]
# Bug Report

**Type /ver NametagEdit and post the output.**
NTE version 4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
![NTE bug](https://user-images.githubusercontent.com/51903578/59585473-6de8a200-9095-11e9-8075-3a5eba7b4f94.PNG)

**What plugins are you using? Type /plugins**
![NTE bug2](https://user-images.githubusercontent.com/51903578/59585524-8bb60700-9095-11e9-9af1-54aece183c27.PNG)

**Please explain your issue. How do you trigger it?**
After full setup (creating groups assigning prefixes and permissions and giving them priorities)
the nametags I created work wonderfully on the tablist but not at all in-game above the players head. An interesting side note: No tags show up at all if longtags are off even though most of my rank tags are shorter than 16 characters.
![2019-06-17_00 34 09](https://user-images.githubusercontent.com/51903578/59586387-b4d79700-9097-11e9-9116-1e3f1aa899e3.png)

**Are there any errors in the console? Please use: https://pastebin.com**
None, but heres what shows up with /nte debug enabled. (pardon my bad chicken-scratch I can't write with a mouse lol  :)
![NTE bug3](https://user-images.githubusercontent.com/51903578/59586072-dc7a2f80-9096-11e9-83e8-a0877a954152.PNG)

Thanks for your help!

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

Try that build
