### ISSUE TITLE
All player nametag will disappear when a new player join in the server every time

### ISSUE THREAD

**Issue by zykool** [sgtcaze/NametagEdit#369]
# Bug Report

**Type /ver NametagEdit and post the output.**

Lastest version 4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

PaperSpigot 1.12.2

**What plugins are you using? Type /plugins**
citizens
CMI
Mythicmobs
AdvancedMobArena
HealthBar
LeaderHeads
LuckPerms

MySQL:
  Enabled: true
  Hostname: localhost
  Port: 3306
  Username: xxxxx
  Password: 'xxxx'
  Database: xxx
  # WARNING: If you do not know what this is for, do not change it!
  # This allows users to customize their schema to their liking.
  GroupsTable: nte_groups
  PlayersTable: nte_players
  ConfigTable: nte_config
  # Minimum connection pool size
  # WARNING: If you have no idea what this is for, do not change.
  # To see the optimal connections for your setup, please visit:
  # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
  # And review the pool size configuration (Tn x (Cm - 1) + 1)
  MinimumPoolSize: 10

**Please explain your issue. How do you trigger it?**

All player nametag will disappear when a player join in the server every time.

**Are there any errors in the console? Please use: https://pastebin.com**

Noting in the console.

**Comment by zykool** [comment]
Only the last player who join in the server can see Nametag.
Repeat.

**Comment by JustOneMoreBlock** [comment]
Weird 

https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

Try that build
