### ISSUE TITLE
The name above the player Doesnt change only in tab Can you please help me with this problem? :3

### ISSUE THREAD

**Issue by Snukkieboy** [sgtcaze/NametagEdit#370]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

spigot 1.14.3

**What plugins are you using? Type /plugins**

dynmap, luckperms, worldedit, votingplugin, crazycrates, EZlinks, mineablespawners, Antiafkplus, worldborder, nametagedit, vault, votefier, multiverse-core, worldguard, Essentialsx, EssentialsChat, EssentialsSpawn, GriefPervention, BetterRTP.

**Please explain your issue. How do you trigger it?**

when i use /nte group add Guest
                  /nte group Guest prefix '&7[Guest] '
                  /nte group Guest permission nte.guest

and i set it in my default luckperms (nte.guest) it shows only in tab but not above the player. it shows the default white name

**Are there any errors in the console? Please use: https://pastebin.com**

zero errors

**Comment by RitchieDonkers** [comment]
I have this issue as well.

**Comment by vShoxxx** [comment]
Me too...

**Comment by MysticalFelineOG** [comment]
I am having this issue as well.

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

Try that build
