### ISSUE TITLE
useSSL

### ISSUE THREAD

**Issue by ericheinze** [sgtcaze/NametagEdit#371]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.0
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.13.2

**What plugins are you using? Type /plugins**
Plugins (20): Additions, AuctionHouse, Autorank, CratesPlus, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, IPWhiteListBukkit*, LuckPerms, MFHoppers, NametagEdit*, PlaceholderAPI*, PluginLibrary*, ShopGUIPlus, SuperiorSkyblock2, Vault, WorldEdit, WorldGuard

**Please explain your issue. How do you trigger it?**
Upon loading server, asking for `useSSL`

Just wondering if there is a option for setting to `useSSL=false`, trying to reduce the amount of spam in the console

**Are there any errors in the console? Please use: https://pastebin.com**
Nope! Just annoying to see the SSL warnings

**Comment by fredagsguf** [comment]
You can use "ConsoleSpamFix" as a temporary solution.

**Comment by JustOneMoreBlock** [comment]
Please try this new build and let me know if the console spam is gone.

https://ci.nametagedit.com/job/NametagEdit-Dev/12/artifact/target/NametagEdit.jar

**Comment by dev-erich** [comment]
> Please try this new build and let me know if the console spam is gone.
> 
> https://ci.nametagedit.com/job/NametagEdit-Dev/12/artifact/target/NametagEdit.jar

That seems to have fixed it! Thanks for that :)
