### ISSUE TITLE
spam on console!

### ISSUE THREAD

**Issue by leoncp9** [sgtcaze/NametagEdit#372]
As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit. why? my server is paper spigot and i use PlaceholderAPI-2.10.1, and latest version of nametagedit, this is spam on console!

**Comment by JustOneMoreBlock** [comment]
Provide log and re-open.
