### ISSUE TITLE
Long nametags do not work

### ISSUE THREAD

**Issue by Ezerex** [sgtcaze/NametagEdit#373]
# Bug Report

Version 4.4.2
Authors: sgtcaze and Cory

CraftBukkit version git-Bukkit-3a91182 (MC: 1.13.2)

**a lot: WorldEdit, colored signs, healthBar, chatcolor2 minewebBridge
ClearLag,ArmorStandEditor,NameTagEdit,HolographicDisplays,BuycraftX WorldGuard,ServerRestartWarning, ExtraPrefix, RankSigns, PermissionsEx, IConomy, DurabilityAlert, Vault, TabName, StaffPlus, CratesPlus, ChestShop, AdvancedRegionMarket,Essentials,Jobs,Scoreboardstats citizen, Shopkeepers, ChestCommands, EssentialsChat, ServerSigns, SetTheSpawn, Simleychat**

**I heard that in 1.13 or + you can have really really long name tag but mine still have a limit, like i have my [SuperModerator] on the tab, but on my name tag it shows [SuperModerator **
is it normal?**

**No errors in console**

**Comment by JustOneMoreBlock** [comment]
Try this build:
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
