### ISSUE TITLE
[Bug] Only 1 space works in prefix.

### ISSUE THREAD

**Issue by Jadiction** [sgtcaze/NametagEdit#375]
# Bug Report

**Type /ver NametagEdit and post the output.**
[07:32:08 INFO]: NametagEdit version 4.4.2
[07:32:08 INFO]: Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
[07:34:00 INFO]: This server is running Paper version git-Paper-137 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Please explain your issue. How do you trigger it?**
It appears when you have more than one space in a prefix for a group in `groups.yml`, the spaces used later in the string aren't accounted for. For example:
`Prefix: '&8[New Player]&7 '`
only returns `'&8[New Player]&7'` (no space afterward)

**Are there any errors in the console? Please use: https://pastebin.com**
Nope.

**Comment by JustOneMoreBlock** [comment]
I think you need to do something along the lines of:
`'&8[New Player]&7 &r'` to get your space.

**Comment by Jadiction** [comment]
I tried that exactly, actually and it didn't work.
