### ISSUE TITLE
Nametagedit help nametags wont work, only works in the tab

### ISSUE THREAD

**Issue by KemTex25** [sgtcaze/NametagEdit#376]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.14.3

**What plugins are you using? Type /plugins**
KillAllMobs, dynmap, WorldEdit, PluginConstructorAPI, BarAPI, ClearLag, NametagEdit, Votifier, Multiverse-Core, WorldGuard, VotingPlugin, BetterTP, PermissionsEx, LumberJack, ViaVersion, Vault, GriefPrevention, ViaBackwards, SimpleSit, BlockParticles, ChestShop, Essentials, SimpleRename, Holograms, AuctionHouse, EssentialsChat, EssentialsSpawn

**Please explain your issue. How do you trigger it?**
So the tablist has prefixes and all but it wont show the prefix on like the nametags

**Are there any errors in the console? Please use: https://pastebin.com**
There arent any

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

Try that build

**Comment by KemTex25** [comment]
aight thanks homie
