### ISSUE TITLE
[Bug] Prefix parsing is a bit bugged

### ISSUE THREAD

**Issue by Jadiction** [sgtcaze/NametagEdit#377]
# Bug Report

**Type /ver NametagEdit and post the output.**
[07:32:08 INFO]: NametagEdit version 4.4.2
[07:32:08 INFO]: Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
[07:34:00 INFO]: This server is running Paper version git-Paper-137 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Please explain your issue. How do you trigger it?**
I'm not entirely sure of the pattern yet, but certain prefixes do not work. Examples:
`Prefix: '&5[Subscriber]&7 '` (There's a space in prefix but not in the name)
![image](https://user-images.githubusercontent.com/8557785/61935454-2dabf780-af50-11e9-94a5-667ec4ae4657.png)
http://prntscr.com/ok9bp4

`Prefix: '&5[Subscribe]&7 '` (Seems removing the "r" allowed the space to process?)
![image](https://user-images.githubusercontent.com/8557785/61935539-559b5b00-af50-11e9-95d1-f519e390f7fa.png)
https://prnt.sc/ok9cjv

`Prefix: '&5[Subscribe test]&7 '` ("t]" seem to mess up the prefix) 
![image](https://user-images.githubusercontent.com/8557785/61935677-a0b56e00-af50-11e9-8bb9-9adee9ded00b.png)
https://prnt.sc/ok9duq

`Prefix: '&5[God Donator]&7 ' ` (I don't know what's happening here. There's no pattern. The name has no space, doesn't "process" the &7 color code, and even removes the beginning letter from the player's name)
![image](https://user-images.githubusercontent.com/8557785/61936209-da3aa900-af51-11e9-90cb-43d0a95ec9d1.png)
https://prnt.sc/ok9i3r

`Prefix: '&1Server Admin&7 '` (I wanted to say the brackets were the only constant, but even when I remove them, the second space doesn't get processed) 
**(Yes, I also tried `Prefix: '&1Server Admin&r &7'`)** - When I do that, it seems to ignore the `&7` after the second space, because my name is white (due to &r).
![image](https://user-images.githubusercontent.com/8557785/61936531-9005f780-af52-11e9-989b-0dd3069ba4eb.png)
http://prntscr.com/ok9kw1

I can do more examples to further narrow the issue, but I'm hoping this may be enough to find a solution as to why the prefix parsing seems to be a little bit messed up.

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

Try that build

**Comment by Jadiction** [comment]
I tried that build, restarted and the issue is still occurring.

**Comment by JustOneMoreBlock** [comment]
Run the command again to set prefix.

**Comment by Jadiction** [comment]
Alright.
I run:
`/nte group New prefix &5[Subscribe test]&7`
and result:
![image](https://user-images.githubusercontent.com/8557785/61937654-ee33da00-af54-11e9-8ef0-ae3b9e38153e.png)

**Comment by Jadiction** [comment]
I'm unsure why you close the issue when you're not even sure if the issue persists in the most updated build or not (which it is).
