### ISSUE TITLE
vanish

### ISSUE THREAD

**Issue by widsard** [sgtcaze/NametagEdit#380]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.1.4

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

craftbukkit1.8.7

**What plugins are you using? Type /plugins**

a lot

**Please explain your issue. How do you trigger it?**

can still see nametag when in /vanish

**Are there any errors in the console? Please use: https://pastebin.com**

nope

**Comment by JustOneMoreBlock** [comment]
Unfortunately, this is a client-side bug and cannot be fixed.
