### ISSUE TITLE
LuckPerms * is messing with NameTagEdit Plugin

### ISSUE THREAD

**Issue by tntcurtis** [sgtcaze/NametagEdit#381]
# Bug Report 

**Type /ver NametagEdit and post the output.**

`<blockquote class="imgur-embed-pub" lang="en" data-id="a/NQikLUY" data-context="false" ><a href="//imgur.com/a/NQikLUY"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

`<blockquote class="imgur-embed-pub" lang="en" data-id="a/NQikLUY" data-context="false" ><a href="//imgur.com/a/NQikLUY"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

**What plugins are you using? Type /plugins**

`
![image](https://user-images.githubusercontent.com/47724685/62400585-bb3da780-b54d-11e9-92b8-acf19a4107a4.png)
`

**Please explain your issue. How do you trigger it?**

So I use the plugin LuckPerms. When I add the * node to myself the highest priority group will take place and not the actual group I am currently in on LuckPerms.

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by JustOneMoreBlock** [comment]
Could you please try this build:
https://ci.nametagedit.com/job/NametagEdit-Dev/12/artifact/target/NametagEdit.jar

Please try this and report back.
https://github.com/sgtcaze/NametagEdit/wiki/Setup-Permissions
