### ISSUE TITLE
NametagEdit Invisibility Potion Issue

### ISSUE THREAD

**Issue by capitalsminecraft** [sgtcaze/NametagEdit#383]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Spigot 1.8.8

**What plugins are you using? Type /plugins**
Essentials, NametagEdit, Authme Reloaded

**Please explain your issue. How do you trigger it?**
When my friend drink invisibility potion, i can still see his nametag, is this a problem? how i fix it?

**Are there any errors in the console? Please use: https://pastebin.com**
No Console Problems

**Comment by JustOneMoreBlock** [comment]
Unfortunately, this is a client-side bug and cannot be fixed.
