### ISSUE TITLE
Name is white above player head

### ISSUE THREAD

**Issue by MassiveLag** [sgtcaze/NametagEdit#384]
# Bug Report

**Type /ver NametagEdit and post the output.**
[03:21:36 INFO]: NametagEdit version 4.4.0
[03:21:36 INFO]: Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
[03:21:57 INFO]: This server is running Paper version git-Paper-158 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
https://timings.aikar.co/?id=f3f540c1e67449cd9523cc66b438d29a#plugins

**Please explain your issue. How do you trigger it?**
Hi, so when people join my alt at this moment, in tab they have colored. but above their head not. long tags is enabled. I also disabled featherboard to test, makes no difference.

**Are there any errors in the console? Please use: https://pastebin.com**
No, there are no errors.

**Comment by MassiveLag** [comment]
?

**Comment by JustOneMoreBlock** [comment]
Hello,

This has been reported before. Could you please try this build:
https://ci.nametagedit.com/job/NametagEdit-Dev/12/artifact/target/NametagEdit.jar

**Comment by MassiveLag** [comment]
Hi, i will test it right now, thanks!

**Comment by MassiveLag** [comment]
Yes, this one works! Thankyou!
