### ISSUE TITLE
Prefix colors inconsistent between 1.8-1.12 and 1.13-1.14

### ISSUE THREAD

**Issue by iLemon** [sgtcaze/NametagEdit#385]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.8.8

**What plugins are you using? Type /plugins**
Private, can PM if necessary.

**Please explain your issue. How do you trigger it?**
This is how the tab looks (correctly) on version 1.8 to 1.12: https://gyazo.com/96ea567782b389d88ca6f2cd8b3c5aa3

This is how the tab looks (incorrectly) on version 1.13 and 1.14: https://gyazo.com/afe25c5cf34d64e009f3e367823f6f5e

**Are there any errors in the console? Please use: https://pastebin.com**
No

**Comment by JustOneMoreBlock** [comment]
Might have changed in 1.13+ when Mojang made the `team` prefixes. You can fix this by adding:

`/nte group <rank> '&eHelper &r'`

&r would reset the prefix and should get you the same results.

**Comment by iLemon** [comment]
I was already using &r but changing it to &f fixed it for me. Thanks.
