### ISSUE TITLE
Chat Support

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#389]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.0
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Spigot 1.8.8

**What plugins are you using? Type /plugins**
luckperms,worledit,adminfun,placeholderaepi,playershide,idisguise,hubthat,sudo,viaversion,craftingstore,multiverse-core,interactables,vault,viarewind,rankgrantplus,commandsigns,protocollib,wouldgaurd,protectionlib,supervanish,bkcommonlib,holographicdisplays,bungeenpc

**Please explain your issue. How do you trigger it?**
Not really any issue. What is the version of nametagedit where there was chat support in it. The reason I want this is so I have the tags in chat. And yes I know that there will be no support.

**Are there any errors in the console? Please use: https://pastebin.com**
nope.

**Comment by JustOneMoreBlock** [comment]
We removed the chat support in favor of using `PlaceholderAPI` which using a plugin like DeluxeChat can achieve your tags in a chat with the latest NametagEdit.

**Comment by ghost** [comment]
> 
> 
> We removed the chat support in favor of using `PlaceholderAPI` which using a plugin like DeluxeChat can achieve your tags in a chat with the latest NametagEdit.

I do not want to use deluxe chat because it costs $7.50. I am asking for the latest version that had it.

**Comment by ghost** [comment]
> 
> 
> We removed the chat support in favor of using `PlaceholderAPI` which using a plugin like DeluxeChat can achieve your tags in a chat with the latest NametagEdit.

Please. What is the version that last used it?

**Comment by ghost** [comment]
And could you use essentials chat with the latest version?
