### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by TsCode1** [sgtcaze/NametagEdit#39]
I really really really need you to add something to this plugin.
I want to be able to organize the group order shown in tab, for example Owner being first, admin second, donors third, and then anyone that is not in the group list will automatically be last priority.
this plugin did it:   https://www.spigotmc.org/resources/tablistorganizer-beta.15713/
but that one is super glitchy and it messed up my server.
PLEASE
ty <3

**Comment by TsCode1** [comment]
sgtcaze PLSSSSSSS I WILL LOVE U FOR LIFEEE!!!!!!!!!!!!!!!!<3

**Comment by JustOneMoreBlock** [comment]
Looking at the plugin and if anything, we would add our own implementation of it to not soft depend on other plugins.

and make it compatible with Featherboard as seems like it's currently not with the tablist organizer.

Or we may look into adding some kind of support to Bungeetablist as that works fine and does lot of cool stuff!
