### ISSUE TITLE
Groups Command

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#39]
When adding groups using MySQL, it doesn't store at all.

/nte groups add guest
/nte groups add vip
/nte groups add mod
/nte groups add admin
/nte groups add senioradmin
/nte groups add headadmin
/nte groups add owner

Doesn't notify if it's been added or not, so you think it's not adding and you try adding the same group again it says it exists which is doesn't.

http://www.imgwiz.com/images/2015/05/29/GEyqQ.png

On the GitHub page shows a list of commands, however based on the syntax it wouldn't work and in the above image provides errors.

In-game shows you the correct syntax:
http://www.imgwiz.com/images/2015/05/29/C6FXO.png

However, it doesn't store into the database.

If you add the data manually into the table, everything seems to work fine.

**Comment by sgtcaze** [comment]
v3.0.1 addresses this. Thank you.
