### ISSUE TITLE
Rank above Head

### ISSUE THREAD

**Issue by XiNaru** [sgtcaze/NametagEdit#391]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paperspigot 1.14.2 R0.1 Snapshot
Paperspigot 1.14.4 R0.1 Snapshot

**What plugins are you using? Type /plugins**
On bei Testserver i use online EssentialsX (+ Chat + Spawn), Nametagedit, Vault and LuckPerms

**Please explain your issue. How do you trigger it?**
I have create a group with prefix and permission, the i give with luckperms a group the permission an reload the plugin.
Chat and Tablist Prefix works, but overhead names doesnt work.

**Are there any errors in the console? Please use: https://pastebin.com**
No Errors

**Comment by XiNaru** [comment]
Solution:
The official version of Spigot is outdated. There is a version 4.4.2 in Jenkins and with this it works again.

https://ci.nametagedit.com/job/NametagEdit/

**Comment by JustOneMoreBlock** [comment]
> Solution:
> The official version of Spigot is outdated. There is a version 4.4.2 in Jenkins and with this it works again.
> 
> https://ci.nametagedit.com/job/NametagEdit/

Yeah, I haven't updated SpigotMC yet as I was testing a Dev Build. But, I own the domain/ci build server. :)
