### ISSUE TITLE
NTE vanish issue

### ISSUE THREAD

**Issue by Chalwk** [sgtcaze/NametagEdit#4]
There appears to be an issue when staff go into Vanish. 

My server uses a plugin called VanishNoPacket. When a staff member vanishes, that player disappears from the scoreboard. Other staff (including OPs) cannot see their name in the player list. I might point out that this problem seems to be intermittent. However, it occurs 90% of the time. 

Regards,
Jericho

**Comment by JustOneMoreBlock** [comment]
@Chalwk77 

Can you provide a plugin list?
Are you seeing any errors in the console?

**Comment by sgtcaze** [comment]
Version of the server? Are names completely hidden or do the appear somewhat transparent?

I am leaning towards Mojang bug here because I've seen this reported before. (Was an issue in 1.8, fixed in 1.9)

**Comment by Chalwk** [comment]
- **Latest version of Spigot.** 
- **Names are completely hidden.**

**Plugin List:**
ColoredSigns, neoPaintingSwitch, Lift, ScheduledAnnouncer2, NametagEdit, Drills, BanManager, DarkHorse, BiomeTP, BetterSocialSpy, Tablist, PlayerMagnet, CoreProtect, AsyncWorldEditInjector, WorldEdit, InvMaster, HeadNamer, nv, CustomEnderChest, ClearLag, ChatControl, AdminFunPlus, Frame_Protector, Modifyworld, Votifier, ProtocolLib, Multiverse-Core, LibsDisguises, SignEdit, CustomServerMessages, Rename, PermissionsEx, mcMMO, Vault, ChairStairs, UltraCosmetics, HolographicDisplays, LWC, WorldGuard, DeathBounty, CheckMyInventory, Stats, Commandspy, boosCooldowns, HolographicScoreboard, GameModeInventories, Essentials, Jobs, HeadDatabase, RandomTP, Auctions, WarpPortals, SilkSpawners, WhatIsIt, Citizens, EssentialsKitManager, RegionGUI, VanishNoPacket, EssentialsChat, BlocksHub, EchoPet, BuyRegion, CS-CoreLib, EnjinMinecraftPlugin, ChestShop, Slimefun, EssentialsProtect, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, PvPManager, ExtraGear, AsyncWorldEdit, HotbarPets, SlimefunLuckyBlocks, ExoticGarden, Gun_Fun, PrivateStorage

**The only error I see is the following on (Start up).**
[VanishNoPacket] Enabling VanishNoPacket v3.19.2-SNAPSHOT-unofficial
**[VanishNoPacket] Colored nametags enabled, but I couldn't find TagAPI**
[VanishNoPacket] For awesome colored nametags on vanish, visit
[VanishNoPacket] http://dev.bukkit.org/server-mods/tag/ 
[VanishNoPacket] and download TagAPI.jar
[VanishNoPacket] Now hooking into Essentials
[VanishNoPacket] You wanted Dynmap support. I could not find Dynmap.
[VanishNoPacket] SpoutPlugin not running but you wanted SpoutPlugin features.
[VanishNoPacket] Not a release version. Update check disabled
[VanishNoPacket] 3.19.2-SNAPSHOT-unofficial loaded.

**Comment by sgtcaze** [comment]
Latest as in 1.7.10 (Spigot 1658 I think) or Latest 1.8.8?

To be clear, you are saying when you use /vanish, no one can see this player? However, you want _certain_ players to see them, right?

**Comment by Chalwk** [comment]
Spigot 1.8.8

Previously, when a staff member used /vanish, the vanishing players name would remain visible to other staff members who have permission to see vanished players in the scoreboard - which is what we want. The latest update is now causing the vanishing players name to disappear from the player list entirely. Even from OP staff. 

On a side note, I have a feature request. When a player goes into Vanish, could a Prefix [V] be applied to the players name automatically. (Visible only to staff, of course)?

**Comment by Chalwk** [comment]
UPDATE:
This issue appears to have "vanished" completely. I can't say what was causing this to occur, for sure, but I suspect it had something to do with EssentialsX. In any case, the problem is gone.

**Comment by sgtcaze** [comment]
Thank you for the updated @Chalwk77 

Some of our tests didn't work. So, glad this worked out for you.
