### ISSUE TITLE
Healthbar

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#40]
http://dev.bukkit.org/bukkit-plugins/health-bar/

Every time a player gets hurt the Nametag is removed.
- Investigating

**Comment by JustOneMoreBlock** [comment]
Confirmed.

http://i.imgur.com/0jRdgte.gif

However, player can fix this by:

```
player-bars:
  enable: true
```

to

```
player-bars:
  enable: false
```

**Comment by sgtcaze** [comment]
This is not an issue with NametagEdit. The plugin in question uses a scoreboard to display a suffix at the end of the name when the player is hit (see the yellow bars when the player takes damage.)

This effectively creates a new scoreboard and overrides the one we send via packets.
