### ISSUE TITLE
PlaceholderAPI not working

### ISSUE THREAD

**Issue by thetopthailand** [sgtcaze/NametagEdit#403]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
SPIGOT-1.8.8-R0.1-SNAPSHOT-LATEST.JAR

**What plugins are you using? Type /plugins**
Plugins (10): WorldEdit, NametagEdit, Vault, WorldEditCrashFix, GroupManager, PlaceholderAPI, ProtocolLib, WorldGuard, Essentials, TitleManager

**Please explain your issue. How do you trigger it?**
Please watch it : http://103.131.200.118/Nametagedit.mp4
PlaceholderAPI Not updated, need to reload, it will show results
Sorry, I'm not good at English.

**Are there any errors in the console? Please use: https://pastebin.com**
no

**Comment by julfuc** [comment]
This is not a Bug!

Just set the "RefreshInterval" in the config.yml in for example 1 seconds:
```
# If enabled, NametagEdit will refresh nametags on an interval. Note: this does NOT do any
# reloading. This will not pickup changes made from the file or database. Instead, it will
# take any changes made by commands and/or placeholder changes. Set this to < 1 to disable
# this feature. This feature is in seconds. NOTE: We do not recommend this.
RefreshInterval: 1

**Comment by thetopthailand** [comment]
> นี่ไม่ใช่ข้อผิดพลาด!
> 
> เพียงแค่ตั้งค่า "RefreshInterval" ใน config.yml ในตัวอย่าง 1 วินาที:
> 
> ```
> # If enabled, NametagEdit will refresh nametags on an interval. Note: this does NOT do any
> # reloading. This will not pickup changes made from the file or database. Instead, it will
> # take any changes made by commands and/or placeholder changes. Set this to < 1 to disable
> # this feature. This feature is in seconds. NOTE: We do not recommend this.
> RefreshInterval: 1
> ```

Thank you very much. I am glad you responded quickly.
