### ISSUE TITLE
Bungeecord 1.14 kicking all players from server when any player joins

### ISSUE THREAD

**Issue by shastagrande** [sgtcaze/NametagEdit#408]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
version git-Paper-186 (MC: 1.14.4)

**What plugins are you using? Type /plugins**
BungeeGuard, Essentials (Chat, Protect & Spawn) FeatherBoard, KeepChunks, LuckPerms, MVdWPlaceholderAPI, NametagEdit, PlaceholderAPI, ProtocolLib, ShopGUIPLUS, SuperVanish, TitleManager, Vault, WDLCompanion, WorldBorder, WorldEdit, WorldGuard

**Please explain your issue. How do you trigger it?**
I join the 1.14.4 server, and it kicks me, I join back and it doesn't kick me. I join on my other account and it kicks that account and my main account.

**Are there any errors in the console? Please use: https://pastebin.com**
No errors are in the paper server, there are errors in bungee console: https://pastebin.com/hhG6pJ2g

**Comment by NEZNAMY** [comment]
Bungeecord bug.

**Comment by shastagrande** [comment]
okay so how would i fix

**Comment by NEZNAMY** [comment]
Modifying bungeecord code is one way.
There's nothing you can do as a server owner with no coding skills.

**Comment by JustOneMoreBlock** [comment]
I've had this error myself and usually corrects itself by ensuring you have an updated BungeeCord version, and if that doesn't correct it. Restart all your Minecraft Servers (Paper) and should resolve itself.
