### ISSUE TITLE
Luckperms API 5.0

### ISSUE THREAD

**Issue by MineTim** [sgtcaze/NametagEdit#409]
Hello,
LuckPerms now uses the API 5.x. If I uses LuckPerms with version 5.x, your plugin does not work. I found a post from LuckPerms:
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5.
I tried these steps and it works now.

Can you please update the LuckPerms API from 4.x to 5.x. that the extension-legacy-api is not needed anymore in the feature?

Greetings
MineTim

**Comment by JustOneMoreBlock** [comment]
New  build
