### ISSUE TITLE
nte reload dispath

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#41]
"Can you add "nte reload" as dispath Command in onEnable? Cuz when you use /reload on the sv, nte doesn't show prefixes anymore for the connected players."

Request: https://www.spigotmc.org/threads/nametagedit.48578/page-10#post-1542096

/reload on the server - The tags are no longer shown.
Add-in nte reload as a dispath Command in OnEnable will fix this?

Should probably just fix loading, so nobody has to do /reload or /ne reload. :)

**Comment by sgtcaze** [comment]
The /ne reload command already exists. What exactly is he requesting? To my knowledge loading is fine.
