### ISSUE TITLE
Color code not working

### ISSUE THREAD

**Issue by SladeHazard** [sgtcaze/NametagEdit#419]
# Bug Report

*[*03:05:26 INFO]: NametagEdit version 4.4.6
[03:05:26 INFO]: Authors: sgtcaze and Cory**

**Paper-1617 (MC: 1.12.2)**

**Not necessary except ViaVersion,ViaBackwards,ViaRewind**

**I am using the plugins listed above to allow players from 1.8 to 1.15 connect to my server but for some reason for 1.14 and 1.15 users  color codes don't work on on players head but they work fine in the tab, preview: https://imgur.com/a/N6anDfy**

**No errors**

**Comment by SladeHazard** [comment]
bump

**Comment by SladeHazard** [comment]
bump

**Comment by NEZNAMY** [comment]
You reached the 16 character limit on <1.13. Although the limit is not present on 1.14.4 which you are using, the cutting decision in NTE is based on server version (you are using 1.12.2 (<1.13)), not client version.

**Comment by JustOneMoreBlock** [comment]
While @NEZNAMY is correct. Your server version is 1.12.x. That's your limitation of 16 characters max. If you were to upgrade your server to use 1.13.x+ you can fully utilize max color codes.

I've created a new build that didn't have 1.14_R2 added. So, this could fix any issues later on.
https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by SladeHazard** [comment]
Problem still not resolved i tried using this version:
It still doesn't work and i didn't pass the limitation of 16 characters
:face_palm:
  A:
    Permission: animatednames.group.A
    Prefix: '&8[&a&lA&8]&7 '
    Suffix: '&7'
    SortPriority: 35
It shows the gray prefix like [A] &7<playername> on version 1.12.2 but not
after that can't this be fixed?!

**Comment by SladeHazard** [comment]
Problem still not resolved i tried using this version:
https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar
 *
