### ISSUE TITLE
Prefixes all jacked up!

### ISSUE THREAD

**Issue by B00MERzY2K** [sgtcaze/NametagEdit#42]
So I've had this problem for around 3 weeks now, and I have yet to solve it. I am having this issue where if I am in my Owner group, I get the Mod's prefix next to my name. This happens with every other group as well. I have kinda found this issue, but I have no clue on how to resolve it. Basically, whatever group is at the top of the list, it's prefix is going to be set on every other group. For example, if Owner was at the top of the list, the prefix "Owner" would show up for all the other groups instead of the proper prefix I had setup. I have no clue what the hell is going on here, and it'd be kinda nice to get some sort of help for once.

**Comment by sgtcaze** [comment]
What version of the plugin are you use (/ver NametagEdit). MySQL or FlatFile?

Please post a picture of your groups.yml/players.yml or your database structure if applicable.

**Comment by B00MERzY2K** [comment]
I am using version 4.0.2, and I am using MySQL. And yes, I can send you a pic.

Groups.yml Pic: http://imgur.com/5pzwMJW
Player.yml Pic: http://imgur.com/IgYYvcW

And this last one is a picture of my problem. Please take note of both my rank and my name on the side bar.
http://imgur.com/W55SVS0

I hope you're able to help.

**Comment by JustOneMoreBlock** [comment]
Hello,

Are you providing all the permissions to every group?

For example, Does;

Owner: nte.owner
Admin: nte.admin

Your group file seems fine. This seems to be a matter of permissions.

What permission plugin are you using?

Can you provide all your configs and upload to http://pastebin.org
- NametagEdit config.yml
- NametagEdit groups.yml
- NametagEdit players.yml
- Permissions Plugin

If you use any MySQL database information, please remove these connection details on the upload website.

**Comment by B00MERzY2K** [comment]
Yeah, I am giving each group the proper permission, but that still doesn't seem to work. I am currently using PermissionsEx. And yes, I can provide the configs for you.

NametagEdit config.yml: http://pastebin.com/fZ0Te6Ey
NametagEdit groups.yml: http://pastebin.com/0GnL2X1k
NametagEdit players.yml: http://pastebin.com/GsvA9mMM
PermissionsEx permissions.yml: http://pastebin.com/DzstC37r

I hope this is what you need! :)

**Comment by B00MERzY2K** [comment]
Did you guys get my latest message? I'm not too sure because it says this issue hasn't been opened for 7 days. I'm not sure if my previous message even went through or not.

**Comment by JustOneMoreBlock** [comment]
Have you tried using the order command?

`
/nte groups order Owner Admin Developer Builder SrMod Moderator VIP Saint MVP
`

**Comment by B00MERzY2K** [comment]
Yeah, I've tried that but it still does the same thing. :(

**Comment by B00MERzY2K** [comment]
Okay, now it's working a bit better. Apparently I can't reload the plugin, or else it will mess up again. Guess I'll just have to keep restarting my server whenever I want to add new nametags. :/
