### ISSUE TITLE
Random groups

### ISSUE THREAD

**Issue by Agazed** [sgtcaze/NametagEdit#42]
When a player joins my server, the groups seem to be random and have nothing to do with permissions.

Kind of hard to explain with text, test out the plugin on a server and you would see the issue

**Comment by sgtcaze** [comment]
If you're using MySQL, the groups will be random for now until I add the sorter.

If you're using flat file, please post your groups.yml. The "Order:" is no longer used. The new structure is Top -> Bottom

**Comment by Agazed** [comment]
http://pastebin.com/1XUnKJJF

Yes I realized you removed order, I read through the code.

**Comment by sgtcaze** [comment]
Tested against zPerms: https://hub.spigotmc.org/jenkins/job/zPermissions/
With this commit: https://github.com/sgtcaze/NametagEdit/commit/9dcd8998a187220caa01841bc977c9754dde4692

Tested as operator and deopped, and was correctly inheriting the groups permissions fine. Perhaps remove the default "nte" permissions, and try creating your own?

**Comment by sgtcaze** [comment]
If this is still an issue, please reopen/open a new issue. This issue was resolved with flat file on that earlier commit.
