### ISSUE TITLE
NTE Not Getting Along with the latest BungeeCord

### ISSUE THREAD

**Issue by mercurialmusic** [sgtcaze/NametagEdit#422]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.6

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
CraftBukkit version git-Spigot-05bb8bc-8073dbe (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT) with BungeeCord build 1430.

**Please explain your issue. How do you trigger it?**
See this discussion: https://github.com/SpigotMC/BungeeCord/issues/2735
Tags worked, but any time someone joined the server everyone was kicked to another server. No crash, no error on the Spigot server, but Bungee showed the error same as the one reported in that issue. Removing NTE solved the problem.

**Comment by JustOneMoreBlock** [comment]
try new build
