### ISSUE TITLE
LongTags only working in TAB

### ISSUE THREAD

**Issue by Saymoan** [sgtcaze/NametagEdit#428]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.6

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper 1.13.2 654

**What plugins are you using? Type /plugins**
Plugins (66): AAC, AdvancedPortals, AuctionHouse, BetterRTP*, BlockParticles, BuycraftX, Citizens, CitizensCMD, ClearLag, CoreProtect, CrazyCrates, DeathSign*, DeluxeMenus, DeluxeTags*, DiscordSRV, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, EZBlocks*, EZRanksPro, FastAsyncWorldEdit, FeatherBoard*, HeadDatabase*, Headdatabase-Addon, HolographicDisplays, Hotels*, InvRestore2, Item2Chat, ItemEditor, KitCreator*, LiteBans, LuckPerms, MiningLimiter, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, NametagEdit*, NetherTransporter*, NoVillagerTrade*, OreRegen, PlaceholderAPI, PlayerBlocks, PlayTime*, PlugMan, ProtocolLib*, Realistic_World, SellStick, ServerListPlus*, ShopGUIPlus, StaffChat*, SuperVanish, TAB, Towny, TownyNameUpdater, Unstuck, Vault, ViaVersion*, VoidGenerator, Votifier, VotingPlugin, Vouchers, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Please explain your issue. How do you trigger it?**
LongTags don't work above the player name, but work in tab, even though it says that it should work over the player name

**Are there any errors in the console? Please use: https://pastebin.com**
Nope

**Comment by archql** [comment]
I have the same problem. Also minecraft 1.13.2

**Comment by minzeck** [comment]
I have the same problem, works fine on tab, but in nametag doesn't works. Version 1.15.1

**Comment by JustOneMoreBlock** [comment]
LongTags is only for tab.

**Comment by Saymoan** [comment]
On the spigot page it shows that the LongTags also work above the player’s name. If this isn’t the case I suggest updating the page.
