### ISSUE TITLE
MySQL Order bug

### ISSUE THREAD

**Issue by MnkyArts** [sgtcaze/NametagEdit#43]
Hey, i used the command /nte group order [highest to lowest](/nte group order Owner Moderator Supporter User). but it doesn't worked, everytime when someone was on the Server and i joint i was at the bottom of the tablist :/ but if i use the command /nte reload im on the top of the Tablist..

i hope you can help me to fix this bug! :)

(sorry for my bad english, im german)

**Comment by JustOneMoreBlock** [comment]
`/ne groups order Owner Admin Default`

Make sure you're using `groups` and not `group`.

Let me know if you still have any issues.

**Comment by MnkyArts** [comment]
i have make a little video to show you my issue @JustOneMoreBlock 
https://www.youtube.com/watch?v=NYyoRUEw-ks&feature=youtu.be&pxtry=1

**Comment by JustOneMoreBlock** [comment]
Can you provide a MySQL database dump of just the nte_ tables?
config.yml (remove your database connection information)

**Comment by MnkyArts** [comment]
sorry, i dont know what you mean can you explain it more? i dont really know what are a dump is, sorry

**Comment by MnkyArts** [comment]
so i show you the tables,
thats nte_config http://prnt.sc/b41bry

thats nte_groups http://prntscr.com/b41cft

in nte_players is nothing in.

config.yml http://prntscr.com/b41d4s

**Comment by sgtcaze** [comment]
There should be a table called "nte_config". Please post an image of that.

**Comment by MnkyArts** [comment]
here
http://prntscr.com/b4nkbs 
http://prnt.sc/b41bry

**Comment by sgtcaze** [comment]
Hmm, looks like it's storing correctly. I'll take a closer look tonight. I'll let you know asap.

**Comment by MnkyArts** [comment]
allright, thanks!

**Comment by JustOneMoreBlock** [comment]
Cannot reproduce.

Please try build 30.
