### ISSUE TITLE
CAN NO LONGER DOWN PLUGIN

### ISSUE THREAD

**Issue by SladeHazard** [sgtcaze/NametagEdit#430]
# Bug Report

** PLUGIN VERSION: NOT REQUIRED **

**SERVER VERSION: NNOT REQUIRED **

**PLUGINS: NOT REQUIRED**

**No one can download the plugin anymore or the older versions or the dev builds http://ci.playmc.cc/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar is down PLS FIX ASAP**

**Are there any errors in the console? NOT REQUIRED / NONE**

**Comment by JustOneMoreBlock** [comment]
The domain hasn't been used in a while.

https://ci.nametagedit.com/job/NametagEdit/
