### ISSUE TITLE
Color codes still not working:

### ISSUE THREAD

**Issue by SladeHazard** [sgtcaze/NametagEdit#431]
Server Version: 1.12.2 Paper
Plugin version: 4.4.7

Problem still not resolved I tried using the version last time you suggested which was suppose to fix the issue: https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

It still doesn't work and I didn't pass the limitation of 16 characters 🤦‍♂ 
  A:
    Permission: animatednames.group.A
    Prefix: '&8[&a&lA&8]&7 '
    Suffix: '&7'
    SortPriority: 1
It shows the colorcode for [A] but not the same for example look at this image: https://imgur.com/a/8maUq9u

P.S I know that this can be fixed because server purpleprison.net is also only using nametagedit and 1.14.4 still sees color code for the names there

**Comment by JustOneMoreBlock** [comment]
What's your server?

**Comment by SladeHazard** [comment]
> What's your server?

play.archernetwork.us

**Comment by SladeHazard** [comment]
bump

**Comment by SladeHazard** [comment]
fixed after enabling fix-team color in viaversion
