### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by termanator1128** [sgtcaze/NametagEdit#44]
Hi i was just making sure that i have permissions to have a plugin connect to yours just want to have this for the person that makes it to know they can connect to this plugin
Thanks
-term

**Comment by JustOneMoreBlock** [comment]
Permission to connect to which plugin?

We have an API for that purpose. You can use it any way you would like.

**Comment by termanator1128** [comment]
it would be a custom plugin

**Comment by JustOneMoreBlock** [comment]
Yeah, you can. :)

https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Developers.creole
