### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by termanator1128** [sgtcaze/NametagEdit#45]
Hi so this person said "You should create a ticket for the developer of Nametagedit to add UUID support so that the name tag change will simply follow you when you change names" (tcwolf12). So here i am requesting uuid support

**Comment by JustOneMoreBlock** [comment]
We have UUID support.

Please use the latest build: http://ci.playmc.cc/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar
