### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Saymoan** [sgtcaze/NametagEdit#451]
**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.6

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper 1.13.2 654

**What plugins are you using? Type /plugins**
Plugins (66): AAC, AdvancedPortals, AuctionHouse, BetterRTP*, BlockParticles, BuycraftX, Citizens, CitizensCMD, ClearLag, CoreProtect, CrazyCrates, DeathSign*, DeluxeMenus, DeluxeTags*, DiscordSRV, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, EZBlocks*, EZRanksPro, FastAsyncWorldEdit, FeatherBoard*, HeadDatabase*, Headdatabase-Addon, HolographicDisplays, Hotels*, InvRestore2, Item2Chat, ItemEditor, KitCreator*, LiteBans, LuckPerms, MiningLimiter, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, NametagEdit*, NetherTransporter*, NoVillagerTrade*, OreRegen, PlaceholderAPI, PlayerBlocks, PlayTime*, PlugMan, ProtocolLib*, Realistic_World, SellStick, ServerListPlus*, ShopGUIPlus, StaffChat*, SuperVanish, TAB, Towny, TownyNameUpdater, Unstuck, Vault, ViaVersion*, VoidGenerator, Votifier, VotingPlugin, Vouchers, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Please explain your issue. How do you trigger it?**
LongTags don't work above the player name, but work in tab, even though it is advertised on the spigot page that these long name tags will work above a player's head.
[Link to Photo](https://proxy.spigotmc.org/395806402b83712af93f07140095f299f6306c11?url=https%3A%2F%2Fi.imgur.com%2FJUODe2e.png)

**Are there any errors in the console? Please use: https://pastebin.com**
Nope

**Comment by feniqx** [comment]
i have the same issue
