### ISSUE TITLE
TheTowers Bug?

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#46]
User: tryolivier reported a bug.

Hi :)

I have this problem with the towers

http://hastebin.com/ociqowucal.avrasm

The towers author says me it's a problem with the last nametagedit

Do you think you can update the resource to resolve this bug ?

thanks

**Comment by sgtcaze** [comment]
Looks like that plugin is using a way outdated NametagEdit version. See this line:

java.lang.NoClassDefFoundError: ca/wacos/nametagedit/NametagEdit

**Comment by JustOneMoreBlock** [comment]
Yep, I can concur.

I only added it to test it.

**Comment by JustOneMoreBlock** [comment]
Invalid.
