### ISSUE TITLE
Problem with the colors in the chat

### ISSUE THREAD

**Issue by sez76** [sgtcaze/NametagEdit#461]
Hello,

I contact you after having a problem with but color in the chat, I did create but group with but permissions, the color is displayed in the Tab without problem, but when it comes to writing in the chat I have the default color in white, I looked at the configuration, everything is well informed, do you have a solution? 

thank you in advance

**Comment by alfiejfs** [comment]
NametagEdit doesn't handle anything with chat. Look into a permissions plugin such as [luckperms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) and a chat plugin such as [essentials chat](https://hub.spigotmc.org/jenkins/job/spigot-essentials/)

**Comment by sez76** [comment]
@AvrooVulcan I wanted to avoid going through Luckyperms, but in the end, it's doesn’t change much, thanks for giving me time, have a nice day
Many Thanks
