### ISSUE TITLE
Tablist Prefix (VERY ANNOYING!!!!)

### ISSUE THREAD

**Issue by B00MERzY2K** [sgtcaze/NametagEdit#47]
So I'm having some big problems with my tablist, and I feel that the prefix that shows up next to my name in the tablist is the problem. Well, when I set TabListDisabled to "true", it doesn't work. If I set it to "true" and then reload NTE, then the prefix will disappear. But if I type something in chat, the tablist reloads or something and the prefix comes back. How do I get this to stop happening?

Thanks! :)

**Comment by sgtcaze** [comment]
What happens after server restarts? Does it still not apply correctly?

**Comment by JustOneMoreBlock** [comment]
Tested the following:

`TabListDisabled: false`
to
`TabListDisabled: true`

`/ne reload`

Works as intended. Disables the tab list just fine. Also, tested this with a "Stopping" and "Starting" the server.

Please use Build 30.
Tested with Spigot 1.9.4
