### ISSUE TITLE
When a player names their tamed animal, it shows the player's prefix as well

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#482]
# Bug Report

**Type /ver NametagEdit and post the output.**
version 4.4.8

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper c11668a

**What plugins are you using? Type /plugins**
Too many, if you really need to know just ask

**Please explain your issue. How do you trigger it?**
In the configuration file of the plugin, I have a placeholder to grab every player's prefix and suffix from luck perms to put that before and after their username. When anyone tames an animal and attempts to name it via nametag, their prefix and suffix shows up on the tamed animal. The prefixes and suffixes will also change when their group is changed.

**Are there any errors in the console? Please use: https://pastebin.com**
no.

**Comment by JustOneMoreBlock** [comment]
Unfortunately, I believe this is a limitation because of Mojang. Possibly could be a way to remove and don't have a fulltime dev at the moment.

**Comment by ghost** [comment]
Okay, be nice to see it fixed. Honestly no big deal though. Thanks for the response!
