### ISSUE TITLE
Error NTE

### ISSUE THREAD

**Issue by MrPesee** [sgtcaze/NametagEdit#49]
http://pastebin.com/73bcLX9K

I get this error when i start the server, that error spams the console
i have seen that the config.yml its empty...

**Comment by sgtcaze** [comment]
See this build http://ci.playmc.cc/job/NametagEdit/15/

**Comment by MrPesee** [comment]
Now its wroking but i have the same error on console:
... 	21 more
[Java ERROR] 	org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot.jar:git-Spigot-2f787bd-501372f]
Interval: 	60 # Seconds between u ...
in 	'string', line 31, column 7:
expected 	, but found BlockMappingStart
OnJoin: 	false # Update from the ...
in 	'string', line 29, column 5:
Caused 	by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
[Java ERROR] 	java.lang.Thread.run(Thread.java:722) [?:1.7.0]
[Java ERROR] 	net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.7.0]
[Java ERROR] 	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.7.0]
[Java ERROR] 	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0]
[Java ERROR] 	net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:973) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1138) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	ca.wacos.nametagedit.NametagCommand.onCommand(NametagCommand.java:47) [NametagEdit.jar:?]
[Java ERROR] 	ca.wacos.nametagedit.NametagCommand.cmdReload(NametagCommand.java:111) [NametagEdit.jar:?]
[Java ERROR] 	ca.wacos.nametagedit.core.NametagHandler.reload(NametagHandler.java:80) [NametagEdit.jar:?]
[Java ERROR] 	org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:214) [spigot.jar:git-Spigot-2f787bd-501372f]
[Java ERROR] 	org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-2f787bd-501372f]
Interval: 	60 # Seconds between u ...
in 	'string', line 31, column 7:
expected 	, but found BlockMappingStart
OnJoin: 	false # Update from the ...
in 	'string', line 29, column 5:
org.bukkit.configuration.InvalidConfigurationException: 	while parsing a block mapping
[02:02:23] 	[Server thread/ERROR] : [NametagEdit] Cannot load configuration from jar

**Comment by sgtcaze** [comment]
That's not the same error. Send me all of your configuration files, or correct your YAML syntax with: http://yaml-online-parser.appspot.com/

**Comment by MrPesee** [comment]
I tried fixing it but it stills gives error
http://pastebin.com/HaMN5vvT

**Comment by sgtcaze** [comment]
I mean your groups.yml and players.yml

**Comment by MrPesee** [comment]
Groups: http://pastebin.com/XzVfkhxi
Players: http://pastebin.com/XsXn34pX
Thanks fror your time

**Comment by sgtcaze** [comment]
Thank you for the report. Your issue helped discover 2 others. You can find the build here: http://ci.playmc.cc/job/NametagEdit/16/

**Comment by MrPesee** [comment]
Thanks for your time!
Now it works perfectly.
