### ISSUE TITLE
Question: Is the invisibility bug fixed?

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#5]
Hello,
I just would like to know if the invisibility bug is fixed please? ^^
Because in the previous version, when a player was "invisible" his tag was still remaining above his head..

Thank you forward,
Best regards

**Comment by sgtcaze** [comment]
This is a minecraft issue with 1.8. In 1.9 snapshots the issue was fixed.

There is nothing we can do for now.
