### ISSUE TITLE
Tablist prefix help me please !

### ISSUE THREAD

**Issue by ImNeverLose** [sgtcaze/NametagEdit#50]
Hello, great plugin! However, when I add a prefix / suffix, after a couple of seconds, it goes. It just resets back to my original name, please help me. I just want to add, i used the plugin when my server was 1.8, and after a week or so of having it on 1.9, it has stopped working, don't know if it's the version or a plugin overriding it? Which i don't think it is.

**Comment by JustOneMoreBlock** [comment]
Seems to fixed in build 30.

Tested with Spigot 1.9.4
