### ISSUE TITLE
Can NTE check changes in placeholders every minute or so?

### ISSUE THREAD

**Issue by spencermacca** [sgtcaze/NametagEdit#504]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper version git-Paper-89 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
https://i.imgur.com/vxUeG9W.png

**Please explain your issue. How do you trigger it?**
Is there a feature or any way where I can get NTE to check a change in a placeholder every minute or something like that, essentially, when I'm vanished, the placeholder for vanish is in tab and on my nametag and it stays like that even after I've unvanished. To fix this, I have to manually reload NTE.

**Are there any errors in the console? Please use: https://pastebin.com**
No.

**Comment by spencermacca** [comment]
_bump_

**Comment by HauserGrim** [comment]
Check "RefreshInterval" in config.
But first of all, I  advise you to turn off the settings for changing the nickname in the configs of other plugins that do this.
