### ISSUE TITLE
Support for HEX colour codes

### ISSUE THREAD

**Issue by TaursGB** [sgtcaze/NametagEdit#517]
# Bug Report / Suggestion?
With the release of Minecraft 1.16, there is an added support for HEX colour codes, and they work fine with the other plugins used on the server however not with NTE. I'm unaware as to whether NTE does not support this yet, or if it is a bug causing it to now work.

**Type /ver NametagEdit and post the output.**
4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
git-Paper-83 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
N/A

**Please explain your issue. How do you trigger it?**
[https://prnt.sc/tuh44k](url)

**Are there any errors in the console? Please use: https://pastebin.com**
N/A

**Comment by accLarson** [comment]
Would love this.

**Comment by winnipeg21** [comment]
This plugin doesn't support hex. Someone offered to make a PR to add support but it appears the dev gave up on this plugin/disappeared.

**Comment by JustOneMoreBlock** [comment]
Dev disappeared.
I have a friend helping me.
I'm the owner and never disappeared.

We are adding support.

**Comment by winnipeg21** [comment]
Damn welcome back! I just saw the code and issues and never seen anyone respond/commit. Glad to see you are still working on this plugin!

**Comment by andris155** [comment]
When is support expected?

**Comment by winnipeg21** [comment]
I know I'm reviving a dead issue. But when will Hex support be added? It's been about 1 month+ without any update and it's been close to 4 months since 1.16 came out (little more for hex support). I know you might be busy and I respect that, but I'd like to keep this plugin used.

**Comment by andris155** [comment]
If you don’t want to wait there are much better plugins that already support it.

**Comment by winnipeg21** [comment]
Oh I know. I just rather a simply plugin with all the features I need
rather than a plugin blouted with crap that I would never use.

**Comment by NEZNAMY** [comment]
> Oh I know. I just rather a simply plugin with all the features I need rather than a plugin blouted with crap that I would never use.

What you are looking for is called "private plugins".

**Comment by winnipeg21** [comment]
Or a "custom plugin" which I use now for only my server.
