### ISSUE TITLE
Long Tags Above Head

### ISSUE THREAD

**Issue by feniqx** [sgtcaze/NametagEdit#525]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.11

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
Plugins (18): ChestCommands, DevHider*, Essentials, EssentialsChat, EssentialsSpawn, EternalNetwork, FastAsyncWorldEdit, LiteBans, LuckPerms, NametagEdit*, PlaceholderAPI, ProtocolLib, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

**Please explain your issue. How do you trigger it?**
The longtags above the head doesn't work as told on the Spigot page: https://proxy.spigotmc.org/395806402b83712af93f07140095f299f6306c11?url=https%3A%2F%2Fi.imgur.com%2FJUODe2e.png

**Are there any errors in the console? Please use: https://pastebin.com**
no

**Comment by Neovitalism** [comment]
I'm on Spigot 1.16.2 and can confirm this happens here as well. Personally, tags on tab work fine with longtags, but the display name above the head is cutting off most of my tags. 
![mod](https://user-images.githubusercontent.com/70066544/92769982-7ea2c900-f367-11ea-8bed-206cdb70b622.png)

**Comment by soy-chrislo** [comment]
![image](https://user-images.githubusercontent.com/69398172/95001398-4b7ede80-058f-11eb-94b1-ea51298aa5e1.png)
The same thing happens to me, spigot 1.16.3

**Comment by razorrider7** [comment]
Apparently this feature works in the latest dev build, but not the latest build on Spigot. Dev builds can be found here: http://ci.nametagedit.com:8080/job/NametagEdit/
