### ISSUE TITLE
New Config Value

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#53]
Add:
`dbVersion: 1`

This will allow us to adapt new conversion scripts based on the version file the player has. Possibly, make it version.yml file and resets on every reload and doesn't effect the config.yml at all?

Since we current don't have a file. A new version would provide a new file and we would read it.

Based on that, we'll assume it's on a specific version or figures it out somehow and we can determine if  we need to modify the database.

For example,
Older version of permissions in MySQL is varchar(16);

Our code will initiate a change:
For example:
`alter table nte_groups modify permission VARCHAR(64);`

**Comment by sgtcaze** [comment]
Good idea. Will add this after placeholder api support.

**Comment by sgtcaze** [comment]
Added to NametagEdit v4.1.2. Update soon, just cleaning up the code.
