### ISSUE TITLE
Missing Constructors and Methods after Cloning Repo and Importing to Eclipse

### ISSUE THREAD

**Issue by Redigits** [sgtcaze/NametagEdit#53]
Hello,

I cloned your repository, opened it in Eclipse, downloaded all of the sources via Maven, and updated the project via Maven. After cleaning the project, I have 139 errors.

Here are screenshots of all of the errors I have:
http://prntscr.com/8t5xk1
http://prntscr.com/8t5xwf
http://prntscr.com/8t5xzl

This appears to be a similar issue to Issue #31 
But as I mentioned, I cloned the repo, updated with Maven, downloaded all sources, and I still have those errors upon cleaning the project in Eclipse. Do you have any recommendations for me? Thank you for your help.

**Comment by sgtcaze** [comment]
You must have Lombok installed to your IDE for annotation processing to work.

Lombok handlers I use are: @Getter, @Setter, @AllArgsConstructor. Without Lombok, your IDE will not be able to compile the project.

**Comment by Redigits** [comment]
That helped me. Following the instructions in this threat at StackOverflow (http://stackoverflow.com/questions/3418865/cannot-make-project-lombok-work-on-eclipse-helios/3425327#3425327), here's what I did:

* Installed Lombok to Eclipse
* Referenced the Lombok jar as an external jar file in my project 
* Restarted Eclipse
* Did a clean operation on my project

After performing the above steps, all of my warnings disappeared and I only had a few warnings remaining. Thanks again! :)
