### ISSUE TITLE
Loaded class me.clip.placeholderapi.PlaceholderAPIPlugin from PlaceholderAPI v2.10.9 which is not a depend, softdepend or loadbefore of this plugin

### ISSUE THREAD

**Issue by Anonymous6214** [sgtcaze/NametagEdit#530]
# Bug Report
![image](https://user-images.githubusercontent.com/44813050/91712197-dac45b00-ebb9-11ea-9485-b43829628acc.png)

**Type /ver NametagEdit and post the output.**

4.4.10
Loaded class me.clip.placeholderapi.PlaceholderAPIPlugin from PlaceholderAPI v2.10.9 which is not a depend, softdepend or loadbefore of this plugin

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

git-Paper-370 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**

IridiumSkyblock, NametagEdit*, PlaceholderAPI, UltraPermissions, Vault

**Please explain your issue. How do you trigger it?**

When I start the server,it always shows the warn that NTE plugin is in legacy mode,and when I put the group and prefix in,it starts show the error that can't find any placeholder plugins

![image](https://user-images.githubusercontent.com/44813050/91712415-427aa600-ebba-11ea-8f5a-b9885f98e874.png)

**Comment by Anonymous6214** [comment]
I don't have the error screen of the [can't find any placeholder plugin] because I rebuild the server...

**Comment by richgrov** [comment]
Those are just warnings and safe to ignore. It's specified as a soft-depend in the plugin.yml but Spigot doesn't recognize it for some reason.

**Comment by JustOneMoreBlock** [comment]
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.

We did make a change for softdepend. So, perhaps this could be resolved? Re-open if not. Thanks
