### ISSUE TITLE
Color Bug

### ISSUE THREAD

**Issue by Lorenzo0111** [sgtcaze/NametagEdit#534]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.10
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.12.2

**What plugins are you using? Type /plugins**
I'm using a lot of plugins (about 100), but this is the only with this function.

**Please explain your issue. How do you trigger it?**
The color is extended to the player's full name. This is not a LongTags problem because the problem also exists with a short name.
![immagine](https://user-images.githubusercontent.com/69311874/95213347-01943380-07ef-11eb-8372-3ef2549c3350.png)
My groups.yml: https://hastebin.com/vagucemogu.less

**Are there any errors in the console? Please use: https://pastebin.com**
No

**Comment by Zoiter7** [comment]
Only add at the end of your prefix your default color or use &r.

**Example, your tag:** &c&lAdmin
**Fix:** Choose one, depends what you want.
&c&lAdmin &r
&c&lAdmin &f

**Comment by Lorenzo0111** [comment]
> Only add at the end of your prefix your default color or use &r.
> 
> **Example, your tag:** &c&lAdmin
> **Fix:** Choose one, depends what you want.
> &c&lAdmin &r
> &c&lAdmin &f

Ok, I’m trying.

**Comment by Lorenzo0111** [comment]
Ok, it works, thanks.
