### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by WortyHax** [sgtcaze/NametagEdit#536]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Spigot 1.8.8

**What plugins are you using? Type /plugins**
https://prnt.sc/uzvhwz

**Please explain your issue. How do you trigger it?**
Console spaming errors, i know it says not issue with NametagEdit but i need help to get it fixed
I have Placeholder Plugin installed but seems not to be that issue ive updated everything to latest version

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/Yzhyw95G

**Comment by JustOneMoreBlock** [comment]
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.
