### ISSUE TITLE
Refactor Order Command

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#54]
Refactor the order command to support the flat file and MySQL. This will eliminate modifying the groups.yml manually.

`/ne groups order`

We haven't had this issue yet. However, I could see it being an issue later in the future.

/ne groups order Owner Admin Dev Architect Builder Mod JrMod AsstMayor Mayor Governer VIP VIP+ MVP Citizen Guest

With Minecraft's character limitation. This could be an issue. Granted, they could go into the MySQL database and add it manually. This will avoid any future errors.

**Comment by sgtcaze** [comment]
Added to NametagEdit v4.1.2. Update soon.
