### ISSUE TITLE
Configurable luckperms hook

### ISSUE THREAD

**Issue by Crypnotic** [sgtcaze/NametagEdit#546]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper 259 1.16.4

**What plugins are you using? Type /plugins**
LuckPerms & NameTagEdit. Along with a collection of private plugins

**Please explain your issue. How do you trigger it?**
NTE automatically sets the prefix of a player based off of LP permissions. I would like to disable this, but I can't find how to do such. I wrote a custom minigame that uses NTE to set player prefixes/suffixes, but it refuses to work on certain ranks as those ranks have elevated permissions(think Owner). It's clashing with my local name tag changes, but I have no way of disabling that hook.

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by Crypnotic** [comment]
It appears the issues I have go much deeper than the luckperms hook.

I've now created a patch project to remove the luckperms hook and disable group name tag assigning on join as both are unneeded in my use case.

I might suggest breaking the core function of changing nametags(API, packets, etc) into a seperate 'core' project so that users such as myself don't have to modify the project for the sole purpose of not having random name tags assigned.

**Comment by JustOneMoreBlock** [comment]
Imported a change from LuckPerms creator #459 

Maybe this will work for you. Lastest build on jenkins
