### ISSUE TITLE
Maven Repo Gone

### ISSUE THREAD

**Issue by eslym** [sgtcaze/NametagEdit#548]
This is not really a bug but the maven repo for nametagedit is no longer exists, any alternative?

**Comment by JustOneMoreBlock** [comment]
> This is not really a bug but the maven repo for nametagedit is no longer exists, any alternative?

It's only temporary. Should be up soon.

**Comment by Aurelien30000** [comment]
Still not apparently :/

**Comment by BadWolf-i** [comment]
> > This is not really a bug but the maven repo for nametagedit is no longer exists, any alternative?
> 
> It's only temporary. Should be up soon.

still not =(

**Comment by Frisk17** [comment]
any day now

**Comment by JustOneMoreBlock** [comment]
Fixed.

**Comment by Aurelien30000** [comment]
Gone again :/

**Comment by StitchieMC** [comment]
Not fixed.
