### ISSUE TITLE
Tag bug

### ISSUE THREAD

**Issue by ElitStrikerzHD** [sgtcaze/NametagEdit#55]
When a name of a player is to long it will glitch.
the prefix is &8{&7Bedrock&8} timothy2001.
but when its a bigger name it will be like
&8{&7Bedroctimothy2000001 so that bugs really hard
i could send some pics if you want me to

**Comment by sgtcaze** [comment]
There is a limit with the amount of characters allowed in the prefix and suffix. It is 16 characters. If we go over the limit, clients will crash.

**Comment by ElitStrikerzHD** [comment]
LoL

**Comment by ElitStrikerzHD** [comment]
lol then the plugin is bad configured i think i'll need a better plugin then

**Comment by jensz12** [comment]
@ElitStrikerzHD i think you need to understand how plugins work before complaining about it

**Comment by ElitStrikerzHD** [comment]
i do understand them but its sad
this was the only good plugin
but i guess that you shouldn't make it when it can only have 16 characters lol
there ai'nt players going to be called
111
222 
mia
die
...

**Comment by sgtcaze** [comment]
Yeah the restriction is imposed by Mojang. Plugins are the way we access and provide these features. The 16 characters can be added infront of and behind the name. E.g. Prefix + name + Suffix (48 characters including name)
