### ISSUE TITLE
MySQL causes errors

### ISSUE THREAD

**Issue by unchilled** [sgtcaze/NametagEdit#553]
# Bug Report

**Type /ver NametagEdit and post the output.**
![image](https://user-images.githubusercontent.com/56901314/102818363-75ca8600-439f-11eb-8911-e1a9b86163c7.png)

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
![image](https://user-images.githubusercontent.com/56901314/102818390-82e77500-439f-11eb-9269-f0834c17471d.png)

**What plugins are you using? Type /plugins**
![image](https://user-images.githubusercontent.com/56901314/102818427-9397eb00-439f-11eb-9278-ea8b0885c2cc.png)

**Please explain your issue. How do you trigger it?**
When using MySQL, I keep getting errors in the console.

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/g7Bw863T

**Comment by tsgrissom** [comment]
Can report I am also having these issues. NametagEdit does not work with an external MySQL database at the moment.

**Comment by JustOneMoreBlock** [comment]
This may have been an issue with your host. Please try the latest version.

This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.
