### ISSUE TITLE
Bug with Reflex: Advanced Killaura Blocker

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#56]
Plugin: https://www.spigotmc.org/resources/reflex-advanced-killaura-blocker-1-7-1-9.21122/

Post: https://www.spigotmc.org/threads/nametagedit.48578/page-11#post-1627355

"Hello, would it be possible to update this plugin? I'm using this plugin together with reflex: advanced kill aura blocker, would it be possible to make it so that plugin ignores invisible (or maybe add an option in the config?) => Because the reflex plugin creates invisible NPC's above a player, this causes a weird issue. A player sees his own nametag / name high above his head"

example image: http://imgur.com/Th4Ywnm

**Comment by benjabvb** [comment]
Any solutions?

**Comment by sgtcaze** [comment]
Are you using ViaVersion? Any specific proxy: e.g. WaterFall/BungeeCord? Server version: e.g. Spigot, Craftbukkit, Paper, TacoSpigot etc.

**Comment by benjabvb** [comment]
Ok well i was using **spigot 1.8.8 back then** with **ViaVersion**! no bungee,..
Well for me **it's currently fixed**. I did an update to **spigot 1.9.4** and switched from **reflex anticheat(this was causing the problem)** to Advanced anti cheat,

**Comment by sgtcaze** [comment]
Thanks for following up with your fix. I'll keep an eye on this, and keep your solution on hand in case anyone else experiences this.
