### ISSUE TITLE
Have to reload to get the nametags to show up

### ISSUE THREAD

**Issue by JezWalmsley** [sgtcaze/NametagEdit#562]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Final build 1.14.4 spigot

**What plugins are you using? Type /plugins**
WE,PlaceholderAPI,ViaVersion,NTE,ViaBackwards and rewind,Luckperms,Citizens,OldCombatmechanics,DeluxeHub,ViaRewind-Legacy,LPC,CitizensCMD

**Please explain your issue. How do you trigger it?**
When I join the tags aren't there but when I do /nte reload they appear

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by MiffedLyric559** [comment]
Same Issue for me and multiple others. I heard this was a problem with 1.16.5 but I also tried another plugin called PlayerRanks but it seems to have the exact same issue.
