### ISSUE TITLE
Mysql issue

### ISSUE THREAD

**Issue by Ragemalik** [sgtcaze/NametagEdit#563]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.1

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

PaperSpigiot

**Please explain your issue. How do you trigger it?**

Hello,

I had manetag edit on all my servers they were not synced then i wanted to sync them (i still have all my groups in the group.yml in all the servers) so i hooked up mysql on all my servers
I thought everythign will be fine though non of my groups show there not there anymore but there in the groups.yml in all my servers if you see my groups are there i dont want to manually redo all my groups so i need to get this to work i tried contacting people they said i was good to go but it dose not work oddly maybe i am missing a step? so far i jsut hooked myaql on all my servers and restarted all my servers i am not too sure if i am forgetting something there is no English tutorial on how to use this feature so i need your help. Before all my groups were working so you know and when i went into the database the groups were not there so they did not sync correctly though when i make a new group it shows in the database so i am not sure the issue going on right now maybe there is a nametag edit bugnee plugin that i dont have i did not think nametag edit had a bungee version of there plugin though that may be the issue

**Are there any errors in the console? Please use: https://pastebin.com**

No errors

**Comment by JustOneMoreBlock** [comment]
You have to run the `/nte convert` command to import into `MySQL`. Providing this is still an issue for you. Regardless, it can helpe someone else out.
