### ISSUE TITLE
Squished names in game

### ISSUE THREAD

**Issue by OllieJW** [sgtcaze/NametagEdit#566]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
PaperSpigot 1.16.5

**What plugins are you using? Type /plugins**
![image](https://user-images.githubusercontent.com/71931263/106332923-9380ea00-627f-11eb-8f90-1c63985474ac.png)

**Please explain your issue. How do you trigger it?**
Tags above the players head get merged into their name

![image](https://user-images.githubusercontent.com/71931263/106332982-aeebf500-627f-11eb-81f5-e8aa958ba50a.png)
How it should be:
![image](https://user-images.githubusercontent.com/71931263/106333041-cdea8700-627f-11eb-9fef-f90dd9fa515d.png)

**Are there any errors in the console? Please use: https://pastebin.com**
None

**Comment by OllieJW** [comment]
**Long names is enabled in the config**

**Comment by JustOneMoreBlock** [comment]
> # Bug Report
> **Type /ver NametagEdit and post the output.**
> 4.4.10
> 
> **What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
> PaperSpigot 1.16.5
> 
> **What plugins are you using? Type /plugins**
> ![image](https://user-images.githubusercontent.com/71931263/106332923-9380ea00-627f-11eb-8f90-1c63985474ac.png)
> 
> **Please explain your issue. How do you trigger it?**
> Tags above the players head get merged into their name
> 
> ![image](https://user-images.githubusercontent.com/71931263/106332982-aeebf500-627f-11eb-81f5-e8aa958ba50a.png)
> How it should be:
> ![image](https://user-images.githubusercontent.com/71931263/106333041-cdea8700-627f-11eb-9fef-f90dd9fa515d.png)
> 
> **Are there any errors in the console? Please use: https://pastebin.com**
> None

Download the latest 4.4.16 to support the names above your head.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by OllieJW** [comment]
Works thanks :)
