### ISSUE TITLE
maven repo not working??

### ISSUE THREAD

**Issue by goofyclown** [sgtcaze/NametagEdit#567]
seems that the maven repo from this https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Developers.creole isnt working

**Comment by ItsVinnyX** [comment]
I can confirm that this is true. https://i.imgur.com/wpPGKgs.png

**Comment by StitchieMC** [comment]
Can confirm please help...

**Comment by JustOneMoreBlock** [comment]
This is brought back online. If there is an issue, please re-open.
