### ISSUE TITLE
Not changes prefix....

### ISSUE THREAD

**Issue by TanielHD** [sgtcaze/NametagEdit#57]
Hello, I have server that is using this NametagEdit plugin. So I changed prefix like Creative - prefix &8[&a&lC&8] but it shows up like &[&a&lF&8] 

Is it my mistake or a bug or something?

**Comment by JustOneMoreBlock** [comment]
Doesn't seem like a bug on our end.

Can you try placing it in '' single-quotes?

`/ne groups Creative prefix '&8[&a&lC&8]'`

**Comment by sgtcaze** [comment]
Please post your Groups.yml or a photo of your database for nte_groups.

**Comment by sgtcaze** [comment]
User did not for 4 weeks. I will chalk this up to server versions and/or misconfigurations. v4.1.0 will fix any lingering issues.
