### ISSUE TITLE
Nametags visible while invis potted

### ISSUE THREAD

**Issue by ArgonHCF** [sgtcaze/NametagEdit#571]
I want it to be so when you use an invisibility potion the nametag disappears but when you do it currently you can still see their name

**Comment by JustOneMoreBlock** [comment]
> I want it to be so when you use an invisibility potion the nametag disappears but when you do it currently you can still see their name

What client version of Minecraft?

**Comment by ArgonHCF** [comment]
1.8.9

**Comment by JustOneMoreBlock** [comment]
> 1.8.9

Figured as much. Unfortunately, this is a client-side bug and not a plugin/server-side bug and cannot be fixed.

**Comment by ArgonHCF** [comment]
Ah okay do you know of any plugins that work the same but dont show nametags when invis potted?
