### ISSUE TITLE
Gradle?

### ISSUE THREAD

**Issue by tomasweigenast** [sgtcaze/NametagEdit#574]
I just wanna know if this has support for Gradle. Because im importing like so:
```
maven { 
    	url = 'http://ci.nametagedit.com/plugin/repository/everything/'
    }
```

```
compileOnly 'com.nametagedit:nametagedit:4.1.0'
```

And it does not work

**Comment by Lorenzo0111** [comment]
The repository is currently offline

**Comment by Lorenzo0111** [comment]
Also this is a duplicate of  #567

**Comment by JustOneMoreBlock** [comment]
This is brought back online.
