### ISSUE TITLE
Update prefix for other people

### ISSUE THREAD

**Issue by DevSchmidtchen** [sgtcaze/NametagEdit#58]
**Hi**,
I am using the API of this great plugin and I set the player's Nametag if the player joins. The player who joins is able to see the prefix and he also sees the prefixes of all the other players. But the players, who had been on the server before, couldn't see the prefix of the new player.

Sorry for my bad English! I am from Germany :)
Schmidtchen

**Comment by DevSchmidtchen** [comment]
I solved the problem by making it asychronisly!

**Comment by sgtcaze** [comment]
Glad you solved the problem @DevSchmidtchen . Please be mindful about Asynchronous packets! They are not guaranteed to fire in the correct order.
