### ISSUE TITLE
Bold, Italic etc. Name format not working

### ISSUE THREAD

**Issue by AnimeDrache** [sgtcaze/NametagEdit#588]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
paper-1.16.5-570

**What plugins are you using? Type /plugins**
See attached file ![Screenshot_7](https://user-images.githubusercontent.com/51856826/116788708-6c6acc00-aaab-11eb-91e6-999615f89c1c.png)

**Please explain your issue. How do you trigger it?**
It is not possible to make usernames bold or in any other format / style. I can only change the color.

**Are there any errors in the console? Please use: https://pastebin.com**
No

**Comment by TNTUP** [comment]
Can confirm. I have a certain rank which uses `&3&l` and only the &l takes priority ...

**Comment by TNTUP** [comment]
Minecraft limitation, pls ignore this issue :(

**Comment by JustOneMoreBlock** [comment]
I don't think this is an issue in the latest build.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.

Re-open if the issues persists.

**Comment by TNTUP** [comment]
Tested this build with &3&l, doesn't work. This is a limitation of Minecraft, not the plugin.
