### ISSUE TITLE
Only work while few sencods

### ISSUE THREAD

**Issue by Wisky987** [sgtcaze/NametagEdit#59]
When I start the plugin, this works and show the nametags a tab. The problem is that few seconds later  this not work. But is some strange, in my main server (lobby) works always correctly, but when the players travel to other servers via BungeeCord in that servers don't works. 

Can you fix that? Thanks, is a good plugin :)

**Comment by sgtcaze** [comment]
Try Builds #32 and above, see if this fixes your problem
http://ci.playmc.cc/job/NametagEdit/32/

**Comment by Wisky987** [comment]
No, that build neither works :(

**Comment by sgtcaze** [comment]
Please post your plugin list and server version.

**Comment by Wisky987** [comment]
The serveris running at 1.9.4. The plugins running https://gyazo.com/9340385b5bb800f2409ffd67c91b3975

Thanks :)

**Comment by sgtcaze** [comment]
Hang tight, have an update coming soon!

**Comment by sgtcaze** [comment]
Little late, but update is almost here. You can track changes here: https://github.com/sgtcaze/NametagEdit/commits/master
