### ISSUE TITLE
Nametag not working

### ISSUE THREAD

**Issue by slowspace** [sgtcaze/NametagEdit#594]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.4.10
**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

**What plugins are you using? Type /plugins**

**Please explain your issue. How do you trigger it?**

/list and and when people kill you wont show up in chat example: [staff] steve was killed wouldn't show up, instead it would just say steve was kill without the [staff]

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by Lorenzo0111** [comment]
It is not releated to NametagEdit

**Comment by JustOneMoreBlock** [comment]
This doesn't fall under the scope of NameTagEdit.

With that said, you can use:
- A permissions plugin to set your rank prefixes there.
- Then use Vault to get those prefixes.
- You would probably would require Placeholder API as well.
- Then use the vault prefixes and set those up on your `Chat Plugin` and inside `NameTagEdit`. Once you change all in the permissions plugin. It updates everywhere.
