### ISSUE TITLE
tab organizer

### ISSUE THREAD

**Issue by JugadorNinja** [sgtcaze/NametagEdit#6]
just a feature to put in nametagedit, is a tab organizer to make the tab more fun. When there are more than 80 people on the server, all vips users disappear from the tab showing only default users, it will be better to show vips first in the tab and not normal users without a nte prefix.
https://www.spigotmc.org/resources/tablistorganizer-beta.15713/

**Comment by sgtcaze** [comment]
This is a cool idea for larger servers, but changes like this should be done via the API (still a work in progress). I think most people would like to have all names in tab.
