### ISSUE TITLE
URGENT! Set Default group with colored nametag.

### ISSUE THREAD

**Issue by blixion** [sgtcaze/NametagEdit#60]
I have searched around, but can't find any "default" setting for the nametag. How can I make all new players on my server receive the nametag color by default?

**Comment by JustOneMoreBlock** [comment]
You need to order your groups.

If you're using a flat file system (groups.yml), Make sure the groups are from the highest to the lowest.

If you're using a MySQL system. Use the order command to make the groups from highest to lowest in-game.

`/ne groups order Owner Admin Default`

Once completed, make sure you give groups permissions.
