### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by Bartek200219** [sgtcaze/NametagEdit#604]
# 1.17 Compatibility request

Will the plugin be available for version 1.17? 
If yes, is there any ETA?

**Comment by JustOneMoreBlock** [comment]
> # 1.17 Compatibility request
> Will the plugin be available for version 1.17?
> If yes, is there any ETA?

It's not hard to add support. But, I'm trying to get Hex Color support first in 1.16.5 and I'll push that out and then update to 1.17.

**Comment by Aurelien30000** [comment]
> # 1.17 Compatibility request
> Will the plugin be available for version 1.17?
> If yes, is there any ETA?

I updated NTE to support 1.17 (on my fork, pr #605). If you would like to test it, tell me ;)

**Comment by Blobbie01** [comment]
> > # 1.17 Compatibility request
> > Will the plugin be available for version 1.17?
> > If yes, is there any ETA?
> 
> I updated NTE to support 1.17 (on my fork, pr #605). If you would like to test it, tell me ;)

I’d love to test it out :) Really missing NTE right now😄

**Comment by Aurelien30000** [comment]
Try this :D [NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/6670997/NametagEdit.zip)

**Comment by Blobbie01** [comment]
> Try this :D [NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/6670997/NametagEdit.zip)

Thank you so much, works perfectly😄💖

**Comment by Bartek200219** [comment]
> Try this :D [NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/6670997/NametagEdit.zip)

Thank you, I will use this too <3
