### ISSUE TITLE
1.17 Support

### ISSUE THREAD

**Issue by Fire177** [sgtcaze/NametagEdit#607]
Is there going to be support added for 1.17

**Comment by Cristelknight** [comment]
yes please add support for 1.17!!!

**Comment by Aurelien30000** [comment]
Try this :D [NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/6670997/NametagEdit.zip)

**Comment by Sergentval** [comment]
> Try this :D [NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/6670997/NametagEdit.zip)

Merci !

Work very fine on Java 16 MC 1.17.

**Comment by emilinator11** [comment]
1.17 plis

**Comment by secretchowc** [comment]
plz add 1.17 plugin in aternos

**Comment by Aurelien30000** [comment]
> plz add 1.17 plugin in aternos

This is not our responsibility, download it manually, wait or ask aternos ;)

**Comment by secretchowc** [comment]
> > por favor agregue el complemento 1.17 en aternos
> 
> Esto no es de nuestra responsabilidad, descárgalo manualmente, espera o pregunta aternos;)
Le acabo de preguntar a aternos para poder poner este plugin para la 1.17 pero me dijieron que le pregunte al creador, no a aternos, entonces cuando van a actualizarlo a 1.17?

**Comment by Aurelien30000** [comment]
@secretchowc Currently you have to update the plugin manually, _if able_, or to wait, this is still a dev-branch ;)

**Comment by viveleroi** [comment]
Even using the unofficial dev builds from this post I get this error: `As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.`

While it says it's not an error with nametagedit, I do have placeholder plugins installed, even the latest dev builds of papi, so I don't understand that issue.
