### ISSUE TITLE
Name showing when player is invisible

### ISSUE THREAD

**Issue by PadsCraft** [sgtcaze/NametagEdit#61]
When a player is invisible with a invisibility potion, their nametag is showing. Please make a part in the config where you can choose if you want the nametag to be visible or not when being invisible. Thanks!

Example: [Link to picture](http://styxnetwork.net/wp-content/uploads/2016/06/2016-06-11_22.15.37.png)

**Comment by sgtcaze** [comment]
This is an issue with 1.8 Minecraft. This was fixed in 1.9 (or at least that's what Mojang claimed.) If you are not using 1.8, please reopen this issue - we'll look into it further.
