### ISSUE TITLE
Compatibilidad o Actualizacion a 1.17 

### ISSUE THREAD

**Issue by secretchowc** [sgtcaze/NametagEdit#610]
# Bug Report

**Type /ver NametagEdit and post the output.**

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper 1.17

**What plugins are you using? Type /plugins**
-Essentials,Luckperms,Skin Restorer

**Please explain your issue. How do you trigger it?**
-Al configurarlo me sale error de comando interno

**Are there any errors in the console? Please use: https://pastebin.com**
-me sale error de comando interno

**Comment by Lorenzo0111** [comment]
Can you speak english? Use translator if you don't know it.
There is an error in the console, can you paste it to https://pastebin.com?

**Comment by secretchowc** [comment]
Type / view NametagEdit and post the result.

What version of Bukkit / Spigot / PaperSpigot are you using? Type / view
Paper 1.17

What plugins are you using? Type / accessories
-Essentials, Luckperms, Skin Restorer

Explain your problem. How do you trigger it?
-When I configure it I get an internal command error

Is there an error in the console? Use: https://pastebin.com
-I get internal command error

**Comment by Lorenzo0111** [comment]
Are you serious? I asked you the error in the console, not in the game

**Comment by secretchowc** [comment]
[23:07:12] [Server thread/ERROR]: Error occurred while disabling NametagEdit v4.4.10 (Is it up to date?)
--
144 | java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
145 | at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[?:?]
146 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[minecraft_server.jar:git-Paper-46]
147 | at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[minecraft_server.jar:git-Paper-46]
148 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[minecraft_server.jar:git-Paper-46]
149 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:525) ~[minecraft_server.jar:git-Paper-46]
150 | at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[?:?]
151 | at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[?:?]
152 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Paper-46]
153 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[minecraft_server.jar:git-Paper-46]
154 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Paper-46]
155 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[minecraft_server.jar:git-Paper-46]
156 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[minecraft_server.jar:git-Paper-46]
157 | at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[minecraft_server.jar:git-Paper-46]
158 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[minecraft_server.jar:git-Paper-46]
159 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[minecraft_server.jar:git-Paper-46]
160 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[minecraft_server.jar:git-Paper-46]
161 | at java.lang.Thread.run(Thread.java:831) [?:?]
162 | [23:07:12] [Server thread/ERROR]: [NametagEdit]
163 | ------------------------------------------------------
164 | [WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
165 | ------------------------------------------------------
166 | This might be an issue with reflection. REPORT this:
167 | > Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
168 | The plugin will now self destruct.
169 | ------------------------------------------------------

**Comment by secretchowc** [comment]
and 


[23:07:12] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.4.10*
--
88 | [23:07:12] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutScoreboardTeam
89 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
90 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
91 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
92 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.Class.forName0(Native Method)
93 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.Class.forName(Class.java:375)
94 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.packets.PacketAccessor.<clinit>(PacketAccessor.java:59)
95 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:25)
96 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
97 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
98 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
99 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
100 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
101 | [23:07:12] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
102 | [23:07:12] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
103 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
104 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
105 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
106 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
107 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
108 | [23:07:12] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.ChatComponentText
109 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
110 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
111 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
112 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.Class.forName0(Native Method)
113 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.Class.forName(Class.java:375)
114 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:28)
115 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
116 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
117 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
118 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
119 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
120 | [23:07:12] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
121 | [23:07:12] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
122 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
123 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
124 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
125 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
126 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
127 | [23:07:12] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.newInstance()" because "com.nametagedit.plugin.packets.PacketAccessor.packetClass" is null
128 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.packets.PacketAccessor.createPacket(PacketAccessor.java:123)
129 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.packets.PacketWrapper.<init>(PacketWrapper.java:18)
130 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
131 | [23:07:12] [Server thread/WARN]: at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
132 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
133 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
134 | [23:07:12] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
135 | [23:07:12] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
136 | [23:07:12] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
137 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
138 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
139 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
140 | [23:07:12] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
141 | [23:07:12] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Lorenzo0111** [comment]
Ok, this will be fixed in #611
