### ISSUE TITLE
Tags don't appear until /nte reload

### ISSUE THREAD

**Issue by AshourAziz** [sgtcaze/NametagEdit#62]
When logging in, tags don't seem to take effect until /nte reload is performed, then the tab shuffles and the tags appear.

**Comment by AshourAziz** [comment]
Running latest build on 1.10 but this also was happening on 1.9.4

**Comment by sgtcaze** [comment]
Please see this build: http://ci.playmc.cc/job/NametagEdit/32/
Let me know if things get better.

**Comment by AshourAziz** [comment]
Nope same situation, /ne reload is the only way to bring it online for anyone that is currently online, once relogging or new players they do not get the proper tag.

Also, /nte or /ne don't work they don't display the help message. doing /nte reload or /ne reload will reload it and display the reloaded message. Referencing it to #51 and the commit to fix it.

**Comment by sgtcaze** [comment]
Sorry for the delay @AshourAziz. Please post your plugin list. I just experienced this issue on a server I work for, and I believe a few plugins are culprits.

**Comment by AshourAziz** [comment]
https://www.ashour.pw/images/160628131914160613191406.png

**Comment by sgtcaze** [comment]
Forgot to update this. The newest version (4.1.2) likely fixes this and other lingering issues.
