### ISSUE TITLE
 Not working at all

### ISSUE THREAD

**Issue by ItzFrosty4** [sgtcaze/NametagEdit#621]
Type /ver NametagEdit and post the output.
4.4.10

What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
This server is running Paper version git-Paper-"1830de5" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

What plugins are you using? Type /plugins
![image](https://user-images.githubusercontent.com/86136877/124423228-576c1c80-dd2a-11eb-9eae-afb9a5e62887.png)

Please explain your issue. How do you trigger it?
I have create a group with prefix and permission, the i give with luckperms a group the permission an reload the plugin.
nothing works

**Comment by Lorenzo0111** [comment]
Is there any error in the console?

**Comment by DarkKingKaan** [comment]
Same issue here, running on Paper 1.17
Error on startup: https://pastebin.com/zygLcnG4

**Comment by Lorenzo0111** [comment]
NametagEdit 1.17 support has not been released yet

**Comment by DarkKingKaan** [comment]
Is there an estimated time of release? Thanks.

**Comment by AlfreDGR** [comment]
Is there an estimated time of release?

**Comment by Lorenzo0111** [comment]
I don’t know. We have to wait the owner of the plugin

**Comment by Aurelien30000** [comment]
Build the plugin yourself…
Or let’s provide a pinned track issue with a test build. Besides, 1.17 support must be released, it’s now enough stable ;)

@Lorenzo0111 @JustOneMoreBlock

**Comment by Aurelien30000** [comment]
https://github.com/sgtcaze/NametagEdit/issues/631

**Comment by JustOneMoreBlock** [comment]
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.
