### ISSUE TITLE
ProtocolSupport error

### ISSUE THREAD

**Issue by Bartek200219** [sgtcaze/NametagEdit#626]
# Bug Report

**Type /ver NametagEdit and post the output.**
![image](https://user-images.githubusercontent.com/37016424/125080833-94873480-e0c5-11eb-93b7-0750892097a5.png)

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper 1.17.1-79

**What plugins are you using? Type /plugins**
![image](https://user-images.githubusercontent.com/37016424/125080796-8507eb80-e0c5-11eb-9222-0d3ae5aa9b17.png)

**Please explain your issue. How do you trigger it?**
Install protocolsupport 
Join server with version that isn't version of server

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/Fp3N52jc

**Comment by Lorenzo0111** [comment]
NametagEdit does not support 1.17 yet, please wait for the release

**Comment by Bartek200219** [comment]
> NametagEdit does not support 1.17 yet, please wait for the release

I don't think it's problem only on 1.17

**Comment by Lorenzo0111** [comment]
> 
> 
> > NametagEdit does not support 1.17 yet, please wait for the release
> 
> I don't think it's problem only on 1.17

Yes, it is

**Comment by JustOneMoreBlock** [comment]
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.
