### ISSUE TITLE
NameTagEdit not working 1.17.1

### ISSUE THREAD

**Issue by bloxoss** [sgtcaze/NametagEdit#628]
Hello! It's been quite some time since the plugin was last updated, and I was wondering, why? There's no discord server so this is my only way of contacting you guys. I had to download an unofficial version to even have it working on 1.17.
PLEASE try and release an update for 1.17.1 as soon as you can, thank you!
- blox

**Comment by Lorenzo0111** [comment]
Hello, the 1.17 update is almost ready. We are waiting for a release from the owner of the plugin

**Comment by bloxoss** [comment]
Do you have any if this will come out within the next week or two? My server really needs it...

**Comment by Lorenzo0111** [comment]
> Do you have any if this will come out within the next week or two? My server really needs it...

I can’t say it because it depends from the owner of the plugin

**Comment by Aurelien30000** [comment]
https://github.com/sgtcaze/NametagEdit/issues/631

**Comment by JustOneMoreBlock** [comment]
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.
