### ISSUE TITLE
Any ETA on the 1.17.1 update? The dev doesn't seem to be very active...

### ISSUE THREAD

**Issue by bloxoss** [sgtcaze/NametagEdit#629]

**Comment by Lorenzo0111** [comment]
Please do not open lots of issues for the same problem

**Comment by bloxoss** [comment]
Well you didn't reply to my last one, so I just wanted to make sure you saw it

**Comment by Lorenzo0111** [comment]
> Well you didn't reply to my last one, so I just wanted to make sure you saw it

I replied..

**Comment by Aurelien30000** [comment]
https://github.com/sgtcaze/NametagEdit/issues/631

**Comment by JustOneMoreBlock** [comment]
This has been resolved in #633. Closes issue.

You can download the latest version here.

https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar

- Supports: 1.8.x to 1.17.1
- HEX Code Support - Thanks to https://github.com/Lorenzo0111 and https://github.com/Aurelien30000
- Added `api-version`. Too many issues reported.
- Updated database to use jdbc instead.
- Updated our database to version 5. Alters the `prefix` and `suffix` tables to increase the `varchar` from 64 to 256.
- Many other bug fixes.
