### ISSUE TITLE
wont Start...

### ISSUE THREAD

**Issue by LimitedGames** [sgtcaze/NametagEdit#63]
I instaled the plugin, than i did join the server and got kicked...
I was thinking ''maby it needs MySQL to work?''
so i did configur that and a few groups.
I did restart the server and it did crash with this ERROR:

17.06 09:05:29 [Server] [Informatie] HikariPool-0 - is starting. 

17.06 09:05:59 [Server] [Informatie] HikariPool-0 - is closing down. 

17.06 09:06:03 [Server] WARN Task #18 for NametagEdit v4.1.0 generated an exception 

17.06 09:06:03 [Server] [Informatie] com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30000ms. 

17.06 09:06:03 [Server] [Informatie] at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526) ~[?:?] 

17.06 09:06:03 [Server] [Informatie] at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:136) ~[?:?] 

17.06 09:06:03 [Server] [Informatie] at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[?:?] 

17.06 09:06:03 [Server] [Informatie] at com.nametagedit.plugin.storage.database.tasks.TableCreator.run(TableCreator.java:26) ~[?:?] 

17.06 09:06:03 [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:53) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:677) [cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336) [cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626) [cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534) [cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at java.lang.Thread.run(Thread.java:722) [?:1.7.0_21] 

17.06 09:06:03 [Server] [Informatie] Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30000ms. 

17.06 09:06:03 [Server] [Informatie] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195) ~[?:?] 

17.06 09:06:03 [Server] [Informatie] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147) ~[?:?] 

17.06 09:06:03 [Server] [Informatie] at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510) ~[?:?] 

17.06 09:06:03 [Server] [Informatie] ... 10 more 

17.06 09:06:03 [Server] [Informatie] Caused by: java.sql.SQLException: Access denied for user 'ron24227'@'v138.violet.fastwebserver.de' (using password: YES) 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[cb1.8.3.jar:git-Bukkit-0a645a2] 

17.06 09:06:03 [Server] [Informatie] at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[cb1.8.3.jar:git-Bukkit-0a645a2]

**Comment by sgtcaze** [comment]
Your database details are incorrect, or your mysql server is not reachable (offline or firewall?)
