### ISSUE TITLE
NTE prefix bug?

### ISSUE THREAD

**Issue by SwitzerLad** [sgtcaze/NametagEdit#637]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit Version 4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Mohist Version 1.12.2

**What plugins are you using? Type /plugins**
Essentials, EssentialsChat, EssentialsSpawn, LPC, LuckPerms, Minepacks, NametagEdit, PlaceholderAPI

**Please explain your issue. How do you trigger it?**
There's an issue when trying to create a prefix. I was doing one for myself aka Owner with this command: 
_/nte group Owner prefix "&0[&4&lOwner&0] &4"_
With this my name should appear red but instead its black. It does work though when I take the &l (bold) away.

**Are there any errors in the console? Please use: https://pastebin.com**
No errors but i am getting this:
_[NametagEdit] [DEBUG] Trying to use PlaceholderAPI for placeholders_
Mabye this is cause of the issue?

**Comment by JustOneMoreBlock** [comment]
Please download the dev build here.
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
