### ISSUE TITLE
An internal error occurred while attemping to preform this commands

### ISSUE THREAD

**Issue by iSergiix** [sgtcaze/NametagEdit#638]
# Bug Report

**Type /ver NametagEdit and post the output.**
Version 4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
paper 1.17

**What plugins are you using? Type /plugins**
actionhelat, advanced ban, chest commands, clear lag, coreprrotect, cubcustomdrops, epicrename, EsscentilsX, fram protect, golden crates, holograpic displays, item editor, loginsecurity, luckperms, multiversecore, NAMETAGEDIT (in red ), nex engine, player kits, shopkeepers, skinsrestorer, skquery, skript, stackmob, staffplus, tiger reports, vault, voidgen, world edit and world guard

**Please explain your issue. How do you trigger it?**
An internal error occurred while attemping to preform this commands

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by Lorenzo0111** [comment]
That error only says there is another error in the console, please give us that error
