### ISSUE TITLE
Tag showing issue

### ISSUE THREAD

**Issue by GershonR** [sgtcaze/NametagEdit#64]
I setup the groups here:
http://pastebin.com/C3RzueSq

I gave each rank its own permission node, but when players with different ranks login it always shows the player prefix, but it works for mods

**Comment by JustOneMoreBlock** [comment]
Hello,

Based on this file. Your default players would be shown as Mods.

It needs to be from highest rank to lowest rank.

**Comment by GershonR** [comment]
Don't I need to give the permission nodes to each group?
It's player -> knight -> baron -> mod
So I gave the nodes to each of those groups but players who are baron/knight still show up as a player.

Edit: I see what you meant by order, looks like its all good now thanks :)
