### ISSUE TITLE
NametagEdit is not working :(

### ISSUE THREAD

**Issue by chilledMia** [sgtcaze/NametagEdit#645]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
[16:43:11 INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
AntiWDL, WorldEdit, CustomUnknownCommand, Skript, SpigotGuard, Plugman, skDragon, SkExtras, SkQuery, NametagEdit, SuperTrailsPro, Tablist, ProtocolLib, BungeePortals, VIPHide, AntiTab

**Please explain your issue. How do you trigger it?**
NametagEdit suddenly stopped working. I do not know why.

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by JustOneMoreBlock** [comment]
Please download the dev build here.
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
