### ISSUE TITLE
Listen scoreboard team join?

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#65]
Hello, I have a question: Is it possible for the NametagEdit plugin to listen when a player is joining a new team (with default color blank), in order to apply the nametag again just after joining a new team? So players do not have to disconnect and reconnect?

A lot of plugin are using the scoreboard feature, and it brokes the colors. If it's possible, it would be a great solution that would work with all plugins!

Thank you very much (and sorry for my bad english)

**Comment by sgtcaze** [comment]
I am not sure what you mean. We have a NametagChangeEvent for developers. What plugins are you using that are incompatible?

**Comment by ghost** [comment]
For example, ChangeSkin is putting you on a new team when we change our skin, we have to do /ne clear player to reset his skin. I was wondering if this was possible that every time a player is put on a team (with no color), a "/ne clear player" could be executed.
But I understand that this is not a NametagEdit issue. I will find a way to do /ne clear player when it is necessary ^^

**Comment by sgtcaze** [comment]
Hello again. Very sorry I forgot to reply! There is no way to tell with the default Bukkit API. However, you CAN use ProtocolLib to listen for the team packet... however there's no way to distinguish illegitimate (non NametagEdit) packets from others in different plugins.

We are unable to fix this.

**Comment by ghost** [comment]
Okay thank you for explainations, I found a way to manually execute a /ne clear when a player is putting on a team (with a command block for example) so no problem and thank you again :)
