### ISSUE TITLE
Doesn't Load

### ISSUE THREAD

**Issue by skirtingas** [sgtcaze/NametagEdit#651]
Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because 
"com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
The plugin will now self destruct.

Error

**Comment by Lorenzo0111** [comment]
https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar
