### ISSUE TITLE
Prefixes Color keeps going back to default color "white" every /nte reload

### ISSUE THREAD

**Issue by Incorretc** [sgtcaze/NametagEdit#653]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.5.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

purpur 1.17.1

**What plugins are you using? Type /plugins**

**Please explain your issue. How do you trigger it?**

issue: color goes back to "white" everytime i reload the plugin

**Are there any errors in the console? Please use: https://pastebin.com**

none

**Comment by Incorretc** [comment]
fixed it when editing the format through the config.yml instead of editing it ingame or through commands

**Comment by ghost** [comment]
how did you do it? i have the same problem
