### ISSUE TITLE
Prefix Above Username In Game

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [sgtcaze/NametagEdit#658]
# Bug Report

**Type /ver NametagEdit and post the output.**
Ver 4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running Paper version git-Paper-"e04368045" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 598 version(s) behind
Previous version: git-Paper-771 (MC: 1.16.5)
**What plugins are you using? Type /plugins**
![image](https://user-images.githubusercontent.com/57046530/139131001-5b71c2e1-c411-40a0-ad90-db891fb19680.png)
**Please explain your issue. How do you trigger it?**
I just wanted to know if there was a way to put a prefix ABOVE a player's name, like for example instead of
[OWNER] HypnoticOcelot

it would be

[OWNER]
HypnoticOcelot

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by Lorenzo0111** [comment]
No, you can’t do that with NametagEdit

**Comment by RealHypnoticOcelot** [comment]
would that be possible in the future or at some point? that'd be so useful especially with char limits, I'm on 1.17 but it has char limits so it'd be nice. Plus it'd look nice lol

**Comment by Lorenzo0111** [comment]
Idk, it will require a full rewrite

**Comment by RealHypnoticOcelot** [comment]
i mean it'd be a nice addon if you ever decide it's a good idea lol
