### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Mr1rbis** [sgtcaze/NametagEdit#659]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.16.5 Tuinity

**What plugins are you using? Type /plugins**

**Please explain your issue. How do you trigger it?**
The plugin does not see the database

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/vXeKWpWz

**Comment by JustOneMoreBlock** [comment]
Please download the dev build here.
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
