### ISSUE TITLE
API setPrefix and setSuffix bug

### ISSUE THREAD

**Issue by xTrig** [sgtcaze/NametagEdit#67]
I am currently using your NametagEdit API in one of my plugins. I noticed that there seemed to be an error when using setPrefix and then setSuffix right after.

On line 39 of NametagAPI, you pass the suffix argument as null, which according to NametagManager, will set the prefix to "" instead of leaving it as is.

Same with line 48 of NametagAPI, where the prefix argument is passed as null. As a result, the following error will occur:

NametagEdit.getApi().setPrefix(p, "Test");
NametagEdit.getApi().setSuffix(p, "Test");

When the nametag updates, the prefix will be "" because it is reset when using setSuffix().

To fix this issue, instead of passing a null value into each method, you should attempt to get the player's current prefix/suffix and pass that instead.

**Comment by sgtcaze** [comment]
Oops, I forgot to add this check back in when I rewrote the manager!
Edit: update soon

**Comment by xTrig** [comment]
Yeah I just ended up forking and writing my own quick fix. Thanks for addressing the issue so quickly!
