### ISSUE TITLE
doesnt load and told me to report

### ISSUE THREAD

**Issue by TristanVos** [sgtcaze/NametagEdit#678]
# Bug Report

**Type /ver NametagEdit and post the output.**
i can't

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running Paper version git-Paper-397 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1a83e90 on ver/1.17.1)
You are running the latest version

**What plugins are you using? Type /plugins**
nametagedit, Luckperms, essentials and a bunch of custom plugins i made by myself

**Please explain your issue. How do you trigger it?**
while starting

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/sTKdQ7j2

**Comment by Lorenzo0111** [comment]
Can you send me the stacktrace above this error?

**Comment by TristanVos** [comment]
Not sure what a stacktrace is but this is everything it gave me: https://pastebin.com/rCUWbBM6

**Comment by webboyt** [comment]
I have the same issue running spigot 1.18, posted stack trace
https://pastebin.com/xppuxew6

**Comment by Lorenzo0111** [comment]
> Not sure what a stacktrace is but this is everything it gave me: https://pastebin.com/rCUWbBM6

Download the new version at https://ci.nametagedit.com/job/NametagEdit/lastSuccessfulBuild/artifact/target/NametagEdit.jar



> I have the same issue running spigot 1.18, posted stack trace
> https://pastebin.com/xppuxew6

1.18 support is not ready yet

**Comment by TristanVos** [comment]
well i am running 1.17, ill update when i have time, thanks for the help

**Comment by JustOneMoreBlock** [comment]
Please download the dev build here.
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
