### ISSUE TITLE
Tab prefixes not showing up

### ISSUE THREAD

**Issue by xJqlen** [sgtcaze/NametagEdit#68]
The plugin is great however there is one problem. The prefixes work with the players but then the don't show up in the tab.

**Comment by JustOneMoreBlock** [comment]
Hello,

Please provide a list of your plugins via console using:
`/plugins`

Please provide your Spigot version via console using:
`/version`

What build of NametagEdit are you using?

Are you using flatfile (groups.yml) or mysql database?

**Comment by xJqlen** [comment]
Plugins: I have AvdancedBan, AuctionHouse, Banknotes, Beast-XpWithDraw, ChatControl, CustomGUI, DeliveryMan, Duels, Envoys, Essentials, Factions, FlightParticles, KitAdder, LinkItem, Lores, Nametagedit, ObsidianDestroyer. PermissionsEX, PhoenixAntiCheat, PlayerVaults, PlugMan, ProtocolLib, RandomPackage_1.8, Staff+, StaffAndVipChat 2.7, StaffGUI, TimTheEnchanter_1.8, Vault, VoxelSniper, WorldEdit, WorldGuard, YouTube.

Version: Spigot 1.8.8

I am using the NameTagEdit groups.yml.

**Comment by JustOneMoreBlock** [comment]
@xJqlen I see you closed this issue. Did you figure everything out?
