### ISSUE TITLE
Bug 1.18.1

### ISSUE THREAD

**Issue by BySwiizen** [sgtcaze/NametagEdit#681]
# Bug Report

Hi, I just upgraded the server to 1.18.1 (Paper) and since then I have this error. I can no longer make any commands and I no longer have a prefix in the TAB.

NTE version: 4.5.2
Paper version: Paper 1.18.1 #68
Error: https://pastebin.com/Agyus41W
Plugin used: ProtocolLib, PlaceholderAPI

**Comment by BySwiizen** [comment]
PS: When the "/nte player BySwiizen prefix &8" command is carried out, I get another error

Error: https://pastebin.com/mDbvSVt8

**Comment by Lorenzo0111** [comment]
Are you running this dev build? https://ci.nametagedit.com/job/NametagEdit-Dev/16/artifact/target/NametagEdit.jar

**Comment by Pascalpex** [comment]
I am running the dev build and get the same error

**Comment by BySwiizen** [comment]
I am running the dev build

Help please

**Comment by BySwiizen** [comment]
Help please

**Comment by Aurelien30000** [comment]
Right, needs a few fixes, check #683

**Comment by BySwiizen** [comment]
Not working for me

**Comment by BySwiizen** [comment]
Work thanks @Aurelien30000
