### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by LudnicaKiller** [sgtcaze/NametagEdit#684]
# Bug Report

NametagEdit version 4.5.0

CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins (65): SaberCoreX, PlaceholderAPI, GroupManager, NametagEdit, PandaWire, AntiDupe, SyntaxBlocker, SSX-Connector, MobFarmManager, NoPortals, ViaVersion, CreeperDrop, CoreProtect, OpenInv, FreeCamDupePatch, BarGamble, WorldBorder, BuycraftX, ProtocolLib, NoCheatPlus, ChatSentinel, MVdWPlaceholderAPI, FastAsyncWorldEdit, IPWhitelist, RedstoneClockDetector, FreezePlus, UltimatePlugin, zTournament, AntiDisconnectSpam, ConditionalCommands, Vault, ThunderDeath, HolographicDisplays, BungeeGuard, PlayerVaults, CratesPlus, WorldEdit, KarhuLoader, Essentials, Citizens, EssentialsChat, HolographicExtension, LeaderHeadsRevamped, WorldGuard, CSGO-CratesPlus, CommandNPC, EssentialsSpawn, ObsidianDestroyer, Factions, CombatLogX, TitleManager, LunarSandBotRecoded, GenBucket, FBasics, FactionsBridge, IllegalStack, KoTH, SilkSpawners, SilkSpawnersEcoAddon, FactionsTop, ShopGUIPlus, DeluxeSellwands, Scyther, ShopGUIPlusSilkSpawnersBridge, FactionsTopv5Hologram2.0

Nothing triggering it, just prints this in console:
17.12 02:43:55 [Server] INFO [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
17.12 02:43:55 [Server] INFO [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
17.12 02:43:55 [Server] INFO [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
17.12 02:43:55 [Server] INFO [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
17.12 02:43:55 [Server] INFO [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
17.12 02:43:55 [Server] INFO [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.

**Comment by JustOneMoreBlock** [comment]
Please download the dev build here.
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
