### ISSUE TITLE
NametagEdit Won't Work on 1.18

### ISSUE THREAD

**Issue by NotAlbatross** [sgtcaze/NametagEdit#687]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.10
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running Paper version git-Paper-77 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5ad1d9a)

**Please explain your issue. How do you trigger it?**
It happened on server startup.

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/GQfYaBMV

**Comment by JustOneMoreBlock** [comment]
Please download the dev build here.
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
