### ISSUE TITLE
1.18 not working

### ISSUE THREAD

**Issue by feeeedox** [sgtcaze/NametagEdit#690]
# Bug Report

**Type /ver NametagEdit and post the output.**
Latest version

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper 1.18

**What plugins are you using? Type /plugins**
[14:59:46 INFO]: Plugins (27): AntiAura, AntiAura-ML, Citizens, DecentHolograms, FastAsyncWorldEdit (WorldEdit), InstantSmelt*, InteractionVisualizer, Multiverse-Core, NametagEdit*, Orebfuscator, PermissionsEx*, PlayerSimulator*, PlotSquared, PlugManX (PlugMan), ProtocolLib, ProtocolSupport, skDragon, Skellett, SkQuery, Skript, skript-reflect, TCPShield, TreeFeller, TuSKe*, Vault, VoidGen, WorldGuard

**Please explain your issue. How do you trigger it?**
Server start

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/7cStxxAY

**Comment by PhoenixSK1** [comment]
I confirm!

The plugin does not want to run on version 1.18, an error appears in the console

**Comment by feeeedox** [comment]
> I confirm!
> 
> The plugin does not want to run on version 1.18, an error appears in the console

i hope they fix it fast

**Comment by Zarbaha** [comment]
this plugin doesn't run on 1.18 i confirm

**Comment by JustOneMoreBlock** [comment]
Use
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by Czempionus** [comment]
> Use https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

This link isn't working ;/

**Comment by PhoenixSK1** [comment]
> 

link is not working, atleast for me

**Comment by fabegalo** [comment]
link is not working,

@JustOneMoreBlock

**Comment by leoncp9** [comment]
with version 4.5.4 of the link now work fine at paper 1.8.1, just add this version to the correct page on spigot cuz a lot of people need this correct version

**Comment by LoboMetalurgico** [comment]
same here
