### ISSUE TITLE
Nametagedit plugin crash upon server boot. Paper 1.17.1

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#691]
# Bug Report

**Type /ver NametagEdit and post the output.**

Nametagedit version 4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Paper 1.17.1

**What plugins are you using? Type /plugins**

Plugins (8): Essentials, EssentialsDiscord, LPC, LuckPerms, NametagEdit*, PlaceholderAPI, TAB, WorldEdit

**Please explain your issue. How do you trigger it?**

Plugin crashes upon server boot. Was working great until it wasn't.

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/uM7wRUgd

**Comment by Jcodeerd** [comment]
I got this exact same problem too.

**Comment by Jcodeerd** [comment]
@sgtcaze Mind having a look please?

**Comment by LoboMetalurgico** [comment]
Try this version: https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar

(Source: https://github.com/sgtcaze/NametagEdit/issues/690#issuecomment-1000904214)
