### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ghazitarazi** [sgtcaze/NametagEdit#697]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.5.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
craftbukkit version 3339-spigot-3c40a6c-581df18 (MC:1.18)

**What plugins are you using? Type /plugins**
coreprotect luckperms inventoryspy randowspawner chairs enternaltags nametagedit vault protocollib orebfuscator

**Please explain your issue. How do you trigger it?**
It keeps giving "An internal error occurred while attempting to perform this command" when i try /nte

**Are there any errors in the console? Please use: https://pastebin.com**

**Comment by Lorenzo0111** [comment]
please send your full server log or the errors from nametagedit

**Comment by ghazitarazi** [comment]
where will i find logs of nametagedit?

**Comment by Lorenzo0111** [comment]
on the server console or in the logs/latest.log folder

**Comment by ghazitarazi** [comment]
[latest.log](https://github.com/sgtcaze/NametagEdit/files/7788377/latest.log)
here is it

**Comment by Lorenzo0111** [comment]
Use https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
