### ISSUE TITLE
Automatically update nametag when player changes group (PEX)

### ISSUE THREAD

**Issue by comfysquirrel** [sgtcaze/NametagEdit#7]
I'm using PEX groups instead of the built-in group system in this plugin. Would it be possible to listen for users changing groups in PEX / Vault and automatically refresh the nametags?

**Comment by sgtcaze** [comment]
We listen to PEX's PermissionEntityEvent which should automatically hook in, and accomplish what you're asking for.

https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/hooks/HookPermissionsEX.java

**Comment by comfysquirrel** [comment]
I was using v4.0 (from spigot). Updated to the newest development build and it automatically refreshes just fine! thanks. :)
