### ISSUE TITLE
Prefix not showing up in TAB!

### ISSUE THREAD

**Issue by ItsArdo** [sgtcaze/NametagEdit#70]
Hey I'm having trouble.

Prefix's aren't showing up in my TAB but are showing up on top of player's skin.

I'm running spigotmc 1.7.10 - 1649 - PROTOCOL

Not sure why it not working. I'm running.

Plugins (30): WorldEdit, LegendWarsEnchants, GroupManager, ClearLag, ChatControl, WorldBorder, NametagEdit, ProtocolLib, WorldGuard, VoxelSniper, TradePlus, mcMMO, Vault, ItemRestrict, RedeemableMCMMO, Essentials, CompatNoCheatPlus, Banknotes, HolographicDisplays, NoCheatPlus, AuctionHouse, EssentialsProtect, EssentialsChat, PlayerVaults, EssentialsSpawn, Factions, Combat, ObsidianDestroyer, FBasics, SilkSpawners
- I've tried removing, ClearLagg, Chat Control, Auction House, Custom Balance, Essentials, Banknotes, Holographic Displays, - Still no luck :/

There is no error in consoles..

And yes i went to config to enable tab.. still nothing.

**Comment by sgtcaze** [comment]
Are you using a development version of NametagEdit? Tryout /ne debug and see if you get console output.

Also please attach your Players.yml/Groups.yml. We do provide support for 1.7, so this should work fine.

**Comment by sgtcaze** [comment]
There has been no followup in 8 days. Please reopen if you need help.
