### ISSUE TITLE
NametagEdit wont load

### ISSUE THREAD

**Issue by DaliborTrampota** [sgtcaze/NametagEdit#703]
# Bug Report

**Type /ver NametagEdit and post the output.**
cant because the plugin wont start but latest from spigot page

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running Paper version git-Paper-134 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 55a1756)
You are running the latest version
Previous version: git-Paper-117 (MC: 1.18.1)

**What plugins are you using? Type /plugins**
![image](https://user-images.githubusercontent.com/31895316/148378366-fc46e58a-beff-4566-99d9-9345426fa1e4.png)

**Please explain your issue. How do you trigger it?**
Start the server

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/2TFN2xzJ
missed this part: https://pastebin.com/82kyH0F9

**Comment by craftyfoxe** [comment]
I have the same issue too

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
