### ISSUE TITLE
Nte don't work; Error: An internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by alberto-taccon** [sgtcaze/NametagEdit#705]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

3284-a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
**What plugins are you using? Type /plugins**

SimpleTPA,LuckPerms,SkinsRestorer,AnticheatPlus,FlyToggle,PlaceholederAPI,HomeSpawn,EasyWarp,MOTD,NametagEdit,CustomChatPrefix,Vault,Lores,SilkSpawners,WorldEdit,PlayerVaults,GriefPrevention,Elevators

**Please explain your issue. How do you trigger it?**

/nte

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/TxEhDZsX

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
