### ISSUE TITLE
Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null

### ISSUE THREAD

**Issue by JunSuner** [sgtcaze/NametagEdit#707]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.10
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
git-Paper-77 (MC: 1.18.1)    PaperSpigot 1.18.1 #77

**What plugins are you using? Type /plugins**
Plugins (36): AdvancedBan, AdvancedNMotd, AuthMe, CMILib, ConsoleSpamFix, CoreProtect, EndReset, Essentials, EssentialsSpawn, HiveChecker, HolographicDisplays, Images, InfiniteScoreboard, JukeBox, LuckPerms, Matrix, Multiverse-Core, MyCommand, NametagEdit*, NoteBlockAPI, Orebfuscator, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, Residence, SkinsRestorer, SuperVanish, TabCompleteFilter, TigerReports, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldEditSUI

**Please explain your issue. How do you trigger it?**
When the plugin is loaded. (what depend plugins have i missed?)

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/c9ZvqY18

**Comment by PappoYT** [comment]
Same problem.

I've just installed plugin on my Paper server and I got hits message in console:
`Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null`

Paper 1.17.1 build #408 
NametagEdit version: 4.4.10

Log: [https://mclo.gs/xzzGYrW](https://mclo.gs/xzzGYrW)

**Comment by PappoYT** [comment]
Installing NametagEdit DEV build 4.5.0 ([from here](https://ci.nametagedit.com/job/NametagEdit/)) removed the error.

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
