### ISSUE TITLE
Doesn't work for Paper 1.18.1.

### ISSUE THREAD

**Issue by Oqark** [sgtcaze/NametagEdit#710]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

git-Paper-175 (MC:1.18.1)

**What plugins are you using? Type /plugins**

Plugins (13): AdvancedBan, Essentials, LuckPerms, NametagEdit*, NoPlugins, PlaceholderAPI, PlayTime*, ProtocolLib, ServerListPlus*, SkinsRestorer, TitleManager, Vault, WorldEdit

**Please explain your issue. How do you trigger it?**

The plugin gives an error when starting the server.

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/t728TFCW

**Comment by SoraCent** [comment]
Same Error for me with NametagEdit 4.4.10 and 4.5.0 on the newest Paper version

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
