### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Samgamer1212** [sgtcaze/NametagEdit#712]
# Bug Report

**Type /ver NametagEdit and post the output.**
**Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null**

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.17

**What plugins are you using? Type /plugins**
BKCommonLib, ChestShop, ColoredSigns, DiscordSRV, EconomyPlus, Elevators, ImageOnMap, LuckPerms, MyWarp, NametagEdit*, ProtocolLib, QuickShop, ServerSigns, SignLink, SignManager*, Train_Carts, Vault, WorldEdit

**Please explain your issue. How do you trigger it?**
Idk how i triggered it but i just get this;

**Are there any errors in the console? Please use: https://pastebin.com**
Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
