### ISSUE TITLE
Error on console, cause "not have" placeholder but already had 

### ISSUE THREAD

**Issue by TheExotik** [sgtcaze/NametagEdit#714]
https://mclo.gs/YYlphVG
this error show when i change the player to another group, they don't receive the tag and show this error, i need to do /nte reload so they receive their tag...

spigot 1.16.5
NTE 4.4.10
28/01/2022

i'm using 2 placeholders and the NTE say i don't have any placeholder.

1 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Trying to use MVdWPlaceholderAPI for placeholders
-- | --
2 | [22:18:07] [Server thread/INFO]: [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
3 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Trying to use PlaceholderAPI for placeholders
4 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Trying to use MVdWPlaceholderAPI for placeholders
5 | [22:18:07] [Server thread/INFO]: [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
6 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Trying to use PlaceholderAPI for placeholders
7 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Created FakeTeam MKWDW_Z24. Size: 1
8 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] The_Exotik has been added to team MKWDW_Z24
9 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Trying to use MVdWPlaceholderAPI for placeholders
10 | [22:18:07] [Server thread/INFO]: [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
11 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Trying to use PlaceholderAPI for placeholders
12 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Trying to use MVdWPlaceholderAPI for placeholders
13 | [22:18:07] [Server thread/INFO]: [NametagEdit] As the error above suggests, you do NOT have any placeholder plugins installed. The placeholder API is merely an interface, it requires other plugins to function. This is NOT an issue with NametagEdit.
14 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Trying to use PlaceholderAPI for placeholders
15 | [22:18:07] [Server thread/INFO]: [NametagEdit] [DEBUG] Created FakeTeam MKWDW_Z25. Size: 2

**Comment by nickaleatorioo** [comment]
show your configuration, try remove plugin MVdWPlaceholderAPI

**Comment by TheExotik** [comment]
i found the issue, was about other plugin conflit... but thanks btw
i left open cause i forget ;-; sorry
