### ISSUE TITLE
Can not run the plugin

### ISSUE THREAD

**Issue by JUJKZ** [sgtcaze/NametagEdit#715]
# Bug Report

**Type /ver NametagEdit and post the output.**

 NametagEdit version 4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

 Paper version git-Paper-177 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2e99e5e)

**What plugins are you using? Type /plugins**

lots of plugins but tested it on no plugins server it told me the same

**Please explain your issue. How do you trigger it?**

I installed the plugin and it says it cannot invoke it

**Are there any errors in the console? Please use: https://pastebin.com**
 https://pastebin.com/77VDbJqn

**Comment by JUJKZ** [comment]
?

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
