### ISSUE TITLE
NametagEdit 4.4.10 will NOT load/enable on Paper 1.18.1

### ISSUE THREAD

**Issue by colorlessvoid** [sgtcaze/NametagEdit#717]
# Bug Report

NametagEdit Version:
4.4.10

Paper version git-Paper-183 (API Version 1.18.1-R0.1-SNAPSHOT)

List of plugins being used.
AdvancedPortals, AnvilColor, AWD*, BuycraftX, ChatInjector, CoreProtect, DropEdit2, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, EZRanksPro, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, Graves, GriefDefender, HolographicDisplays, ItemEdit, LiteBans, LuckPerms, MiniMOTD, NametagEdit*, NexEngine, PlaceholderAPI, ProtocolLib, RandomTP, TabList, Vault, Vivecraft-Spigot-Extensions, VotifierPlus, VotingPlugin, Vulcan, WorldGuard

The issue?
The plugin fails to load on startup.

Are there any errors?
https://pastebin.com/Dpd0s1JP

**Comment by jordanwilliams1** [comment]
@ZERO511-55 Did you ever get this fixed? I'm having the same problem :(

**Comment by jordanwilliams1** [comment]
@ZERO511-55 The latest dev build works fine. This can be closed

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
