### ISSUE TITLE
Crash Upon Startup

### ISSUE THREAD

**Issue by NotAlexNoyle** [sgtcaze/NametagEdit#718]
# Bug Report

**Type /ver NametagEdit and post the output.**

[21:47:43 INFO]: NametagEdit version 4.4.10
[21:47:43 INFO]: Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

[21:47:27 INFO]: This server is running Pufferfish version git-Pufferfish-20 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b9556fd on HEAD)
Received invalid status code (404) from server.
Previous version: git-Airplane-"74774a0" (MC: 1.17.1)

**What plugins are you using? Type /plugins**

Plugins (44): AdvancedRegionMarket, AFKPlus, Afkpluspapi, BountyHunters, Celeste, Chunky, ClearLag, CoreProtect, DiamondBank, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, HorseTpWithMe, KeepDeathDrop, LuckPerms, NametagEdit*, NBTAPI, NewbsCreative, NoCheatPlus, NoClip*, NoNetherRoof, OldCombatMechanics, OpenInv, Parties, PetMaster, PlaceholderAPI, Playtimes*, ProtocolLib, QuickShop, QuickShopList, ServerSigns, Stylizer, TAB, TitleManager, Vault, ViaBackwards, ViaPotions, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldGuard

**Please explain your issue. How do you trigger it?**

Installed the plugin onto my server and started itup

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/raw/PHHpNQrz

**Comment by ConspicuousDev** [comment]
Getting the same here. My server has no plugins and it still crashes with the same error message.

**Comment by JustOneMoreBlock** [comment]
Try https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
