### ISSUE TITLE
Permission based NameTags (or even MySQL syncing)

### ISSUE THREAD

**Issue by gtsatsis** [sgtcaze/NametagEdit#72]
Hi there,

I run a network and I would like to be able to sync the nametags through the servers,

The reason I ask for permission based NameTags is because I have setup PermissionsEx so it syncs through the whole network.

(If there is MySQL syncing then i am fine with it)

**Comment by sgtcaze** [comment]
Yes we do support MySQL and currently support PermissionsEx as well.

**Comment by gtsatsis** [comment]
@sgtcaze :smile:
