### ISSUE TITLE
failed to load nametagedit

### ISSUE THREAD

**Issue by Devox628** [sgtcaze/NametagEdit#720]
# Bug Report

**Type /ver NametagEdit and post the output.**

------------------------------------------------------
[WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
------------------------------------------------------
This might be an issue with reflection. REPORT this:
> Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
The plugin will now self destruct.
------------------------------------------------------

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

paper-1.18.1-198

**What plugins are you using? Type /plugins**

clearlag
essentialsx 2.19.2 , essentialsxChat, essentialsxProtection, essntialsxSpawn
griefprevention,
loginSecuryty,
LuckPerms
tab v3.0.2
vault
viaBackwards, viaRewind, ViaVersion

**Please explain your issue. How do you trigger it?**

idk what it mean

**Are there any errors in the console? Please use: https://pastebin.com**

no

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
