### ISSUE TITLE
Not working on 1.18.2

### ISSUE THREAD

**Issue by moda84** [sgtcaze/NametagEdit#729]
# Bug Report

**Type /ver NametagEdit and post the output.**

Version:

[00:46:53 INFO]: Checking version, please wait...
[00:46:54 INFO]: Current: git-Purpur-1579 (MC: 1.18.2)*
[00:46:54 INFO]: Previous: git-Purpur-1555 (MC: 1.18.1)
[00:46:54 INFO]: * You are 2 version(s) behind

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Purpur

**What plugins are you using? Type /plugins**

 Plugins (68): 2FA, AdvancedBan, AdvancedCrates, AskOp*, AuctionHouse, AuthMe, BetterRTP, ChatManager, ChestCommands, ChestShop, Citizens, ClearLag, CMILib, CommandCooldown, CoreProtect, DailyRewardsPlus, Denizen, dtlTraders, dynmap, Essentials, EssentialsAntiBuild, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), GSit, HeadDatabase, HoloExtension, HolographicDisplays, ImageMaps, Jobs, LuckPerms, Marriage, MoonCoin, MWCustomItems, MWFine3, MWFly, MWHardMobs, MWKitChecker, MWLevel, MWLuckPerms, MWPrefix, MWPVPDisabler, MythicMobs, NametagEdit, PlaceholderAPI, PlasmoVoice, PlayerReport, PlayTime*, ProtocolLib, PvPManager, Quests, Scavenger*, SimpleClans, SkinsRestorer, SkipNight, TheSearch, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, Vulcan, WGExtender, WorldBorder, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, WorldGuardRegionProtect

**Please explain your issue. How do you trigger it?**

Plugin not working on 1.18.2

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/KEkfTDyE

**Comment by Aurelien30000** [comment]
See https://github.com/sgtcaze/NametagEdit/pull/730
