### ISSUE TITLE
Error On StartUp

### ISSUE THREAD

**Issue by Ph4ntooom** [sgtcaze/NametagEdit#731]
Plugin not running

**Type /ver NametagEdit and post the output.**
4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.17.1

**What plugins are you using? Type /plugins**
AdvancedLogin*, AntiCooldown, BanItem, ChatCore, CombatLogX, CraftEnhance, DiscordSRV, DriveBackupV2, ExcellentCrates, GlowAPI, HarvestEXP, HCFClasses, HellConomy, Hibernate, LuckPerms, mcMMO, NametagEdit*, NexEngine, PacketListenerApi, PinataParty, PlaceholderAPI, SiegeWar, SirBlobmanCore (SirBlobmanAPI, XSeries), TAB, Towny, TownyChat, TubeTils, Vault, Votifier, WorldEdit, WorldGuard

**Please explain your issue. How do you trigger it?**
I added nametagedit plugin in plugins folder and then when i start my server it gave error and didnt startup

**Are there any errors in the console? Please use: https://pastebin.com**
Yes, https://pastebin.com/ra80MjWx

![j](https://user-images.githubusercontent.com/101184930/157231046-33d9c3ac-0784-4ac8-82b4-0f24ffa3ea4f.png)

**Comment by ieaston5** [comment]
Same issue on v4.5.0 on 1.18
