### ISSUE TITLE
Not working in 1.18.2

### ISSUE THREAD

**Issue by Attila144** [sgtcaze/NametagEdit#737]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.5.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
git-Paper-241 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
Announcer*, ChatReaction, Citizens, CommandNPC*, CoreProtect, DiscordSRV, DropEdit2, Essentials, EssentialsChat, EssentialsSpawn, InventorySaver, IridiumEnchants, IridiumSkyblock, LibsDisguises, LiteBans, MMOItems, MythicLib, MythicMobs, NametagEdit, OldCombatMechanics, PermissionsEx*, PlaceholderAPI, Prison, ProtocolLib, Quests, StaffPlus, Vault, Vouchers

**Please explain your issue. How do you trigger it?**
I have no clue how I am triggering it.

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/AhpRayvp

**Comment by tristiisch** [comment]
@JustOneMoreBlock can you add a release with the branch staging ? I tested it quickly and it seems to work in 1.18.2. But the "Nametag Visibility" fix is really not optimized and I think it's only for 1.8, so it would be nice to add a parameter in the config or optimize it. (A task every 2 ticks to check this is not great)

**Comment by JohnsanGeezo** [comment]
Yeah getting the same error as attila.

**Comment by Attila144** [comment]
https://pastebin.com/mAKUhDiN

I tried to use a version previous to this and it still doesnt work but I got no clue if the error is the same within this paste bin.

**Comment by DarkKingKaan** [comment]
Same issue here. Waiting for 1.18.2 support to be released. Using the latest Paper 1.18.2 with the latest version of NametagEdit.

https://i.imgur.com/VJmOLzX.png

**Comment by McGames6565** [comment]
Same!
