### ISSUE TITLE
Nametags above players and in tablist issue

### ISSUE THREAD

**Issue by HyperKids** [sgtcaze/NametagEdit#74]
Nametags both above players and in the tablist have a gap the size of a tab after them.
![2016-08-01_20 17 50](https://cloud.githubusercontent.com/assets/12666237/17315973/0d6fc6a2-5825-11e6-8452-078443381f36.png)

Implementing API version 1.8.8-R0.1-SNAPSHOT

**Comment by sgtcaze** [comment]
Are you sure the Suffix section doesn't have an empty color char? Such as &f

**Comment by HyperKids** [comment]
@sgtcaze Yes, I can put the configs onto Pastebin if you like. I tried a mix; some have &f, some have '', and some just don't have the prefix tag.
*This is in groups.yml
http://pastebin.com/dpjXD1JA

**Comment by sgtcaze** [comment]
Yeah each section _needs_ a Prefix/Suffix, otherwise the white color code &f is applied. This is adding the 2 character space you see.

**Comment by HyperKids** [comment]
So I'm not permitted to take out the prefix? How would I remove it altogether?

**Comment by HyperKids** [comment]
@sgtcaze Found the problem and hence the bug: When there is bold formatting in the prefix, it adds that extra space. Pls fix :P

**Comment by sgtcaze** [comment]
I'll look into it, but this sounds like a minecraft thing. Stay tuned for an update ;3

**Comment by sgtcaze** [comment]
Try Dev build 39 on Jenkins and above.

**Comment by HyperKids** [comment]
@sgtcaze Still not fixing problem

**Comment by sgtcaze** [comment]
I've done several tests, and this appears to be the default behavior of vanilla minecraft. What is happening is Minecraft tries to size the tab depending on the number of characters (prefix + name + suffix). The more color codes you have, the larger this indent factor will be. We are unable to change that spacing.
