### ISSUE TITLE
Plugin will not start

### ISSUE THREAD

**Issue by bakedpotato132** [sgtcaze/NametagEdit#740]
# Bug Report

NametagEdit 4.5.0

Paper 1.18.2 267

Plugins: AdvancedEnchantments, ajLeaderboards, AnimatedScoreboard, AuctionMaster, BackPacksPlus, BuycraftX, Citizens, CitizensGUI, CommandHelper, CommandPanels, CompressedHearts, CustomCrafting, DeathMessages, DeathPenalties, DriveBackupV2, EconomyPlus, ExcellentCrates, ExecutableItems, FirstJoinPlus*, HoloExtension, HolographicDisplays, HoloMobHealth, HonezuCustomMaps, LibsDisguises, LuckPerms, MoneyFromMobs, Multiverse-Core, MyCommand, MythicMobs, NametagEdit, NBTAPI, NexEngine, OpenInv, Parties, PL-Hide, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, SCore, ServerListMotdSpigot, SirBlobmanCore (SirBlobmanAPI, XSeries), TabList, TradeSystem, Vault, VentureChat, ViaBackwards, ViaVersion, VoidGen, Votifier, Wardrobe, WolfyUtilities, WorldEdit, WorldGuard

Plugin wont enable

Error: https://pastebin.com/j96dZ93m

**Comment by Sashazypzyp** [comment]
Здравствуйте у меня сервер вкл на 1.18.0 а он у меня не работает а он на 1.18 тоже

**Comment by Sashazypzyp** [comment]
hello, my plugin does not work on version 1.18.1 and there is 1.18 please add version 1.18.1
