### ISSUE TITLE
Error enabling NTE plugin

### ISSUE THREAD

**Issue by GalaxyBlade** [sgtcaze/NametagEdit#749]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
PaperMC: git-Paper-317
Minecraft: 1.18.2
API Version: 1.18.2-R0.1-SNAPSHOT

**What plugins are you using? Type /plugins**
ActionHealth
Citizens
CitizensCMD
ClearLag
CoreProtect
EazyNick
EssentialsX
EssentialsXChat
EssentialsXSpawn
LuckPerms
Multiverse-Core
PlaceholderAPI
PlugmanX
ProtoclLib
ProtocolSupport
Vault
ViaVersion
VoidGen
VoxelSniper
WorldEdit
WorldGuard
Dynmap

**Please explain your issue. How do you trigger it?**
Put all the plugins in the plugins folder then start the server.

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/nNiAAa73

**Comment by Schmazda** [comment]
try a newer version from [here](https://ci.nametagedit.com/job/NametagEdit-Dev/)
