### ISSUE TITLE
Bug Report ( Cannot ivoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.Packets.PacketWrapper.ChatCompenentText" is null)

### ISSUE THREAD

**Issue by Cosphy78** [sgtcaze/NametagEdit#756]
# Bug Report

version of nametagedit was : v4.4.10

i use paperMC: paper-1.18.2-344.jar 
(https://api.papermc.io/v2/projects/paper/versions/1.18.2/builds/344/downloads/paper-1.18.2-344.jar)

i download the plugin from: 
https://www.spigotmc.org/resources/nametagedit.3836/

plugin that i use:
![image](https://user-images.githubusercontent.com/92912213/170133242-8f831996-b1a9-4c93-adf2-1e6d83ff897e.png)
![image](https://user-images.githubusercontent.com/92912213/170133303-b2cda0b2-8631-4c9b-98ff-f22803457900.png)

error in the console:
![image_2022-05-24_230848977](https://user-images.githubusercontent.com/92912213/170132693-943dfca9-2e99-416d-910e-b0214558bfcf.png)

**Comment by JustOneMoreBlock** [comment]
Use Build: https://ci.nametagedit.com/job/NametagEdit-Test/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by JustOneMoreBlock** [comment]
Use updated version
