### ISSUE TITLE
> Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null

### ISSUE THREAD

**Issue by onePlaceholder** [sgtcaze/NametagEdit#757]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Paper

**What plugins are you using? Type /plugins**

 Epheria, FastAsyncWorldEdit (WorldEdit), LuckPerms, NametagEdit*, ServerRestorer

**Please explain your issue. How do you trigger it?**

loading the plugin

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/L7hvSJJM

**Comment by JustOneMoreBlock** [comment]
Use updated version
