### ISSUE TITLE
2 new features

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#77]
Hello :)
Its possible to increase Prefix and Suffix lenght?
My next idea is displaying {PLAYER} than {USERNAME} (Configured by yml config?)

**Comment by sgtcaze** [comment]
The first one is not possible due to restrictions in default minecraft.

The second request is definitely possible. I was considering PlaceHolderAPI support for something like this + defaults.

Edit: Closing this as the second suggestion is coming soon.

**Comment by ghost** [comment]
Hi, I have a question.
Did you added showing in name tag PlayerName (from /nick blabla) than Original name?

**Comment by sgtcaze** [comment]
You mean a way to see the nametag in chat?
e.g.
/nte player <name>
Player "Bob" has nametag: [Potato]

Or something along those lines?

**Comment by ghost** [comment]
My original nickname is BOB
I changed nickname in game by /nick command for example /nick Dave
So my name on chat is Dave. But nick above player is still BOB.
It's possible to replace original minecraft nickname (BOB) on player? by /nick with nametag? [ADMIN] DAVE

**Comment by sgtcaze** [comment]
Not with NametagEdit's default behavior. What you're looking for is something that modifies the player's GameProfile textures. NametagEdit uses scoreboard team packets.
