### ISSUE TITLE
consoles-spam since 1.19.1

### ISSUE THREAD

**Issue by Leahcimkrob** [sgtcaze/NametagEdit#784]
# Bug Report

**Type /ver NametagEdit and post the output.**
NTE 4.5.8

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper 1.19.1-86

**What plugins are you using? Type /plugins**
(https://i.badlion.net/eUcWJzdbEE2TAWRa4X5kWK.png)

**Please explain your issue. How do you trigger it?**
Console-Spam

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/AfrTcCWk

**Comment by BySwiizen** [comment]
Same problem.

**Comment by BySwiizen** [comment]
Same problem.

**Comment by Chopnex** [comment]
+1

**Comment by t4ba** [comment]
please check this :) 

https://pastebin.com/M7ctaJZw

**Comment by biggermine** [comment]
+1

**Comment by JustOneMoreBlock** [comment]
Pushed an update on Spigot.
