### ISSUE TITLE
Not working on 1.19

### ISSUE THREAD

**Issue by ProphetSAMA** [sgtcaze/NametagEdit#786]
# Bug Report

**Type /ver NametagEdit and post the output.**

NametagEdit version 4.5.8
Authors: sgtcaze, Cory, Lorenzo0111 and Aurelien30000

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Current: git-Purpur-1732 (MC: 1.19)

**What plugins are you using? Type /plugins**

![X6%83UF@1AYOOEFX8NW}Y05](https://user-images.githubusercontent.com/66639916/181684674-a4cf3e94-1b8c-4558-86e3-e594710ff1b9.png)

**Please explain your issue. How do you trigger it?**

Except /nte reload, no other commands work

**Are there any errors in the console? Please use: https://pastebin.com**

No error reported

**Comment by JustOneMoreBlock** [comment]
Pushed an update on Spigot.
