### ISSUE TITLE
Ordering in tabs

### ISSUE THREAD

**Issue by FlippantCactus** [sgtcaze/NametagEdit#79]
I'm using nametag grouping and have the "order" setup, but it's not ordering it in TAB how I'd like, I'm just curious if it's possible to add the order function into the TAB, i.e. have staff, then donators, then regular players in tab. (Level of importance). Using latest version and MySQL.

**Comment by FlippantCactus** [comment]
Just to confirm, this is now useless due to https://github.com/sgtcaze/NametagEdit/commit/a512b0ef807c83fa079b74370b506bb78a9dfe09 correct?

**Comment by sgtcaze** [comment]
Hey @TWSSYesterday the order feature is BETA testing with groups flat file (only) at the moment. A large server recently tested it and they've been doing fine, so I'll push it to MySQL asap.

**Comment by sgtcaze** [comment]
Added to NametagEdit v4.1.2. Update soon, just cleaning up the code.

**Comment by FlippantCactus** [comment]
Ily <3

**Comment by sgtcaze** [comment]
Build 43 is now available for testing - it contains lots of new features and fixes! Please let us know how it works @TWSSYesterday (or wait a few days until we confirm it's stable)
