### ISSUE TITLE
Setting prefix only happens for that user

### ISSUE THREAD

**Issue by remydimauro** [sgtcaze/NametagEdit#8]
When setting a players prefix, it only shows up for the player that I set the prefix on. Shouldn't it do it for all players online?

**Comment by JustOneMoreBlock** [comment]
You're setting the player prefix using:
`/ne prefix Player '[Tag]'`

If so, this specific for only that player. However, the player should see his tag in tab list (If enabled) and normal users will see his tag as well.

If users have the same tag you want to setup groups and provide a permission node in your permissions file.

If the issue still persists, please provide:
- Spigot Version (/version)
- List of Plugins (/plugins)

**Comment by remydimauro** [comment]
I forgot to mention that this is using the API. I currently have 4 plugins installed:

AAC
ProtocolLib
NeolyteHub (My custom hub plugin)
Nametagedit

**Comment by sgtcaze** [comment]
Are you setting the tag on Join? e.g. PlayerJoinEvent?

**Comment by remydimauro** [comment]
Yes of course. And before you ask, the listeners are registered.

**Comment by sgtcaze** [comment]
https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/NametagHandler.java#L149

We send teams on clear the player's tags in the PlayerJoinEvent. Notice how we have this set to the highest priority. You are calling the API methods too early. Try placing this on a 1 tick delay and see if that fixes anything.

Another guy had a similar problem, the delay resolved it.

**Comment by remydimauro** [comment]
Thanks. Will try and get back to you. :)

**Comment by remydimauro** [comment]
Worked! Thanks for your help.
