### ISSUE TITLE
Is there a way to make the nametag size bigger through java?

### ISSUE THREAD

**Issue by LArrowHead** [sgtcaze/NametagEdit#80]
I understand you can change the color, but is there a way to modify the size of the nametag above the users head?

**Comment by sgtcaze** [comment]
Are you referring to exceeding the default lengths of 16 characters before and after the username?

**Comment by LArrowHead** [comment]
I was referring to making the size of the entire box (the border, font size, etc) of the nametag. I already asked someone else and I figured out that you could make a custom nametag or make an illusion with multiple nametags.

**Comment by sgtcaze** [comment]
Ah, that is all handled client side. We would be unable to do as you described. However, you might be able to use multiple Holograms to give the illusion of a multidimensional/larger name.

**Comment by LArrowHead** [comment]
Yea I was just curious and found this and decided to ask
