### ISSUE TITLE
I am unable to access the dev builds website

### ISSUE THREAD

**Issue by ItsMitlit** [sgtcaze/NametagEdit#808]
# Bug Report

**Please explain your issue. How do you trigger it?**

Go to the dev builds website

**Are there any errors?*

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by JustOneMoreBlock** [comment]
try now
