### ISSUE TITLE
Service Unavailable - ci.nametagedit.com/job/NametagEdit

### ISSUE THREAD

**Issue by lonadels** [sgtcaze/NametagEdit#824]
# Bug Report

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

![image](https://user-images.githubusercontent.com/15861168/208096139-09138f71-b55a-43ba-b96a-bde2c88d7a44.png)

**Comment by JustOneMoreBlock** [comment]
Try again
