### ISSUE TITLE
The link to the test build does not work

### ISSUE THREAD

**Issue by Kremanit** [sgtcaze/NametagEdit#825]
The link to the test build does not work

![image](https://user-images.githubusercontent.com/74011871/208103052-b7bfe2a7-efee-48d1-8336-105728bdf12c.png)

https://ci.nametagedit.com/job/NametagEdit-Test/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by JustOneMoreBlock** [comment]
Try again

**Comment by Kremanit** [comment]
> Try again

![image](https://user-images.githubusercontent.com/74011871/208242033-717c0d1e-71fc-43e8-b01f-18ec262602ce.png)

**Comment by JustOneMoreBlock** [comment]
- Keeps closing every day. I added a restart policy and hopefully, it will stay online.
- Also, I fixed the SSL certificate.

**Comment by Kremanit** [comment]
> * Keeps closing every day. I added a restart policy and hopefully, it will stay online.
> * Also, I fixed the SSL certificate.

Yes, everything works, thank you very much
