### ISSUE TITLE
1.19.3 bur report: error and warns spamming after the player joins

### ISSUE THREAD

**Issue by VladOliinyk** [sgtcaze/NametagEdit#826]
# Bug Report

NametagEdit version 4.5.11

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
- waterfall-1.19-510
- pufferfish-paperclip-1.19.3-R0.1-SNAPSHOT-reobf
> This server is running Pufferfish version git-Pufferfish-49 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8f95751 on HEAD)

>Plugins (47): ActionHealth, AdvancedHelp, AuthMe, BetterSleeping4, BungeeGuard, BungeeTabListPlus, ClaimChunk, ColorCodes*, CommandAliases, ConditionalTextPlaceholders, CoreProtect, DecentHolograms, DiscordSRV, FastAsyncWorldEdit (WorldEdit), GSit, InventoryRollbackPlus, InvisibleItemFrames, LagAssist, LuckPerms, MyCommand, MysqlPlayerDataBridge, NametagEdit, NoEncryption (ChatSignatures), Omhms, PlaceholderAPI, Plan, PlasmoVoice, PlayerReport, PluginManager, ProtocolLib, ServerBackup, SkinsRestorer, spark, squaremap, squaremap-banners, squaremap-worldguard, UberEnchant, UltimateAutoRestart, Vault, VentureChat, ViaBackwards, ViaVersion, WarpSystem, WorldBorder, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

**Please explain your issue. How do you trigger it?**
After the player joins the server, the error appears and warns are spamming. 
Also, the [BungeeTablistPlus](https://www.spigotmc.org/resources/bungeetablistplus.313/) are not showing the players in the TAB list, so I will continue trying to understand the issue with this too. 

Error in Waterfall console: https://pastebin.com/7g7nrT4v
Spamming WARNs in the waterfall console: https://pastebin.com/TnJU4H57 (like, hundreds of these warns)
Spamming WARNs in the Pufferfish console: https://pastebin.com/7SpdaHKd (really, hundreds of these warns)

**Comment by JustOneMoreBlock** [comment]
Use https://ci.nametagedit.com/job/NametagEdit-Test/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by VladOliinyk** [comment]
Oh, great, Thanks!

i’ve just have been working on my own pull request, just created tiny fix in VersionChecker.java but then saw that there are already a fix for 1.19.3 in the pull request list 😅

thanks <3
