### ISSUE TITLE
Add 1.19.3 Support

### ISSUE THREAD

**Issue by Vertical149** [sgtcaze/NametagEdit#828]
# Bug Report

**Type /ver NametagEdit and post the output.**

Latest

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

1.19.3 Paper

**What plugins are you using? Type /plugins**
Luckperms 

**Please explain your issue. How do you trigger it?**
Add 1.19.3 Support. Plugin not working for 1.19.3

**Are there any errors in the console? Please use: https://pastebin.com**

23.12 09:15:01 [Server] WARN Plugin NametagEdit v4.5.11 generated an exception while executing task 32252

**Comment by PanetiX** [comment]
+1

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Test/lastSuccessfulBuild/artifact/target/NametagEdit.jar
