### ISSUE TITLE
Index out of range exception while convert file to db

### ISSUE THREAD

**Issue by eric2788** [sgtcaze/NametagEdit#83]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

4.0.2 & devbuild#47 also have this problem 
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

paperspigot 1.10.2
### What plugins are you using? Type /plugins

https://gyazo.com/3c1363dd07374c01002151d1d28c58f8
### Please explain your issue?

here's the error code when i tried /nte convert file db true/false
https://gyazo.com/2f0fcef70988d81b3de2e9c813813e47
and it still doesn't load the group
### How do you reproduce the issue?

/nte convert file db true/false
i want to change my  file data to mysql
### Is there an error(s) in the console? Please use: https://pastebin.com

http://pastebin.com/NhYT0ZzG

PS: it is plugin problem or mysql problem ?
if it is mysql problem, how can i fix it ?

**Comment by sgtcaze** [comment]
Please use Jenkins Build 48.

Link: http://ci.playmc.cc/job/NametagEdit/48/
