### ISSUE TITLE
Players are getting kicked for "The received string length is longer than maxiumum allowed (17 > 16)"

### ISSUE THREAD

**Issue by phil568622** [sgtcaze/NametagEdit#84]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

git-Paper-727 (MC: 1.9.2)
### What plugins are you using? Type /plugins

http://i.imgur.com/1gIU3gC.png (NametagEdit was disabled using PlugMan to stop our players from getting kicked)
### Please explain your issue?

Sometimes when a player connects to the server all players are getting kicked for this error: https://slack-imgs.com/?c=1&url=https%3A%2F%2Fbot.gyazo.com%2F980b8c9cb195292e8a8b8602ffd9a0d1.png
### How do you reproduce the issue?

Join the game
### Is there an error(s) in the console? Please use: https://pastebin.com

Couldn't find any

**Comment by JustOneMoreBlock** [comment]
Hello,

One of your groups has 17 Characters in it. The max limit is 16 characters.

**Comment by phil568622** [comment]
Nope, I manually set the Name Tags using a Script, and their Max length is 4 characters

**Comment by sgtcaze** [comment]
Please post your groups/players configuration.

**Comment by sgtcaze** [comment]
No follow up in 8 days. If this issue persists, please reopen this issue. In newer versions of NametagEdit this shouldn't be possible.
