### ISSUE TITLE
libs disguises

### ISSUE THREAD

**Issue by PhanaticD** [sgtcaze/NametagEdit#86]
when using libs disguises, if you disguise as something then un-disguise you lose your title (tab list as well)

**Comment by sgtcaze** [comment]
Please see this commit:
https://github.com/sgtcaze/NametagEdit/commit/8840a5a23d6418d4033296ec36599c47eb06a18c

Build 50 has an untested fix
http://ci.playmc.cc/job/NametagEdit/50/

We're now listening to the UndisguiseEvent and are immediately applying the nametag to the player.

**Comment by PhanaticD** [comment]
it is not fixed, just tried it

**Comment by sgtcaze** [comment]
Just tested and I do not have this issue (test was on 1.8.8 Spigot with ViaVersion 0.9.9, ProtocolLib 4.1.0 and LibsDisguises 8.6.7). Please send me the output of:
/ver
/ver ProtocolLib
/ver LibsDisguises

Also version of your client.

**Comment by sgtcaze** [comment]
No update in 10 days. Issue hasn't been observed with our fix. Closing for now. Please reopen if the issue continues.

**Comment by PhanaticD** [comment]
I am using 1.10 paperspigot
protocollib 4.1.0
libs disguises 9.0.9

**Comment by PhanaticD** [comment]
and yes this is still happening every time

**Comment by PhanaticD** [comment]
I am using Forge 1.10 as my client right now

**Comment by sgtcaze** [comment]
Alright, will try to reproduce and get back to you soon.

**Comment by PhanaticD** [comment]
any news?

**Comment by sgtcaze** [comment]
Jenkins build #52 contains this commit: https://github.com/sgtcaze/NametagEdit/commit/3f9eff107278c399b2bc60e30aea7ef6f8203ef9

It should fix the issue you've been experiencing.
http://ci.playmc.cc/job/NametagEdit/52/

Let me know if it works :D

**Comment by sgtcaze** [comment]
No update in ~20 days. If the issue persists, please reopen. I privately tested this and found it to work using the same client/server/jar.
