### ISSUE TITLE
how does it work :)?

### ISSUE THREAD

**Issue by 1mRAAAH** [sgtcaze/NametagEdit#87]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.2

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
Craftbukkit version git-spigot-4af49dc-23da8b0 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
AntiWDL, Playerheadsm FAWEm Voxelsniper, Voidworld, Pex, Plugman, CategoryWarps, Viaversion, Vault, CustomCommands, BungeeTabListPlusm MV-core, Voidspawn, Worldedit, Chestcommands, Essentials, GoBrush, EssentialsSpawn, WorldGuard, CrateKeys, NTE, HexaCore

### Please explain your issue?
Whenever I /nte player 1mRAAAH priority 1 - /nte player 1mRAAAH prefix prefix it doesn't show anything nor does it give me a prefix

### How do you reproduce the issue?
It simply doesn't do anything no matter what I try

### Is there an error(s) in the console? Please use: https://pastebin.com
nope.

- No documentation on spigot page which indicates how the plugin works, what depencies there are (if there are) and how to (if needed) setup chat plugins e.g.
It doesn't work for me...

**Comment by sgtcaze** [comment]
To get some quick information, checkout this documentation:
https://github.com/sgtcaze/NametagEdit/tree/master/documentation

You will have to reload tags in order for priority to apply (first time). Also, ensure you're using our most recent dev builds. A few builds back Priority was broken for players.
