### ISSUE TITLE
NTE Bug

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#88]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

Spigot 1.8.8
### What plugins are you using? Type /plugins

Just NameTagEdit
### Please explain your issue?

When i set a prefix, instead of showing up the one i created, it shows up the one on the permissions list, like the prefix on the pex

**Comment by sgtcaze** [comment]
Please post your Groups.yml and Players.yml. Are you trying to apply the tag using the Players or Groups options?

**Comment by ghost** [comment]
Groups: http://pastebin.com/6ByZzsFS
Players: http://pastebin.com/G9uU9h4s
Im trying to apply using group options

**Comment by sgtcaze** [comment]
Hmm your groups file looks fine. You mentioned the tag applies "like the prefix on the pex". We do not interact with PEX in this way (as in we do not use PEX prefixes/suffixes).

What command are you running? And please send a screenshot of the tablist when you do this. It sounds like this is a permission issue, or maybe some sort of configuration mismatch.

**Comment by ghost** [comment]
Okay, so i created 6 groups, User, Vip, God, Mod, Admin and Owner. Mod, Admin prefix's works fine, but when i set myself User or god, it shows up the Vip prefix, and when i set myself Owner, Admin tag shows up.

The command, i just created the groups with, /nte group create Admin (mod,vip,user,etc) prefix [prefix] 
and i started changing ranks with pex, and there is when i found this error

**Comment by ghost** [comment]
![2016-09-17_00 34 03](https://cloud.githubusercontent.com/assets/8934431/18605673/c0486942-7c6e-11e6-88c5-4d0834c3e7f2.png)
![sky](https://cloud.githubusercontent.com/assets/8934431/18605678/d73783b8-7c6e-11e6-8511-7ab05079dfe7.png)

The first picture, shows myself without rank, just user, and nothing on the tablist, and in the second photo, you can see im user rank and the user group should be with colour

**Comment by sgtcaze** [comment]
The default rank (Usuario) needs the permission "nte.usuario". If a player or permission group does not explicitly have a permission, it will not apply. 

From what I can see in the screenshot, your permissions plugin does not have any permissions listed under your UUID and Group. Keep in mind having OP is not considered in this process.

**Comment by ghost** [comment]
![2016-09-17_01 04 53](https://cloud.githubusercontent.com/assets/8934431/18605801/d03ad57a-7c72-11e6-8094-ed5603d2c944.png)
![2016-09-17_01 04 47](https://cloud.githubusercontent.com/assets/8934431/18605802/d03aba9a-7c72-11e6-8c30-bb16bcab9eff.png)

Ok, so now i fixed almost everything, right now, im ranked as Owner, but in the tablist it shows up the ADMIN prefix, instead of the owner one, i've added the owner group nte.owner

**Comment by sgtcaze** [comment]
Make sure the order is Descending, so you can use /ne group order or set them manually in your files.
E.g.

```
Groups:
  MyTopGroup:
   ...
  MySecondGroup:
   ...
```

**Comment by ghost** [comment]
You mean like priority?

**Comment by sgtcaze** [comment]
Priority represents the order in Tab. Group priority represents which groups are used to determine Hierarchy.

**Comment by ghost** [comment]
I didnt understand what you mean with /nte group order :$

**Comment by ghost** [comment]
Nevermind, issue solved!

**Comment by ghost** [comment]
I just did this 

Groups:
  Owner:
    Permission: nte.owner
    Prefix: '&b&lOWNER '
    Suffix: ''
    Priority: 1
  Sky-Admin:
    Permission: nte.skyadmin
    Prefix: '&4&lADMIN &7'
    Suffix: '&f'
    Priority: 2
  Sky-Mod:
    Permission: nte.skymod
    Prefix: '&e&lMOD &a'
    Suffix: '&f'
    Priority: 3
  SkyVip:
    Permission: nte.vip
    Prefix: '&eSkyVip &b'
    Suffix: '&f'
    Priority: 4
  SkyGod:
    Permission: nte.skygod
    Prefix: '&3SkyGod &a'
    Suffix: '&f'
    Priority: 5
  Usuario:
    Permission: nte.usuario
    Prefix: '&6Usuario &f'
    Suffix: '&f'
    Priority: 6

**Comment by ghost** [comment]
Okay so, this happens now, i created one group for each rank of the server.
![c5da5ca94867efdbb549551d0599be63](https://cloud.githubusercontent.com/assets/8934431/18611503/362e3900-7d11-11e6-97bf-7e9b70108ef9.png)

Im currently owner,, so my prefix should be &b&lOWNER Aeeder, but instead of having the prefix of NTE, i have like the first 16 characters of the prefix instead of the full prefix which is this "&b&l[&2&l&k;;;&3&lSky-&3&lOwner&2&l&k;;;&b&l"
![9d54760fe83faeb178577a6f621df9d4](https://cloud.githubusercontent.com/assets/8934431/18611530/33e7e636-7d12-11e6-969d-d171d9bd3919.png)

![c76b8b05ab63e5d85c240cba22205d50](https://cloud.githubusercontent.com/assets/8934431/18611539/a9d0bde6-7d12-11e6-8281-03a5332f3f98.png)

**Comment by sgtcaze** [comment]
You can only have maximum 16 characters for a prefix and suffix. These are the default limits for minecraft scoreboards.

**Comment by ghost** [comment]
I know that, but my question is, why does the pex prefix appears instead of the nte one?

**Comment by sgtcaze** [comment]
Well that is very peculiar, yeah. As I said earlier, NametagEdit does NOT pick up any information from PermissionsEX except permissions and groups. We do not load or consider any prefixes, suffixes, titles etc. In fact, we only listen to when a user permission is changed, and then apply the Nametag update.

I don't know how what you're experiencing is possible. This is not doable with default NametagEdit.

**Comment by ghost** [comment]
When i join the server, the tab shows the PEX prefix, but when i type /nte reload, it shows up the NTE prefix, any idea how could this happen?

**Comment by sgtcaze** [comment]
Do you have another plugin that modifies the tab? This is just not possible with NametagEdit.

Edit: Are you using placeholders?

**Comment by ghost** [comment]
I'll send you all plugins i have

**Comment by ghost** [comment]
AAC, AnimatedNames, ASkyBlock, AuctionHouse, ChestCommands, Citizens, ClearLag, CustomJoinItems, Essentials (Spawn,Chat,Protect), FeatherBoard, HolographicDisplays, iDisguise, LibsDisguises, MotdManager, Multiverse-Core, NameTagEdit,PacketListenerApi, Pex,PerWorldChat, PerWorldPlugins, Placeholderapi, Plugman, ProtocolLib, Skywars, TitleAPI, UltraCosmetics, Vault, VoidGenerator, VoidWorld, WorldEdit, WorldGuard

**Comment by sgtcaze** [comment]
Animated Names appears to have an overlapping functionality with NametagEdit:
https://www.spigotmc.org/resources/animatednames.2175/

Perhaps try removing this plugin for a moment and see if this fixes the issue?

**Comment by ghost** [comment]
Yep, that was it, it was because AnimatedNames, thanks for the help mate, Excellent support here

**Comment by ghost** [comment]
I'll close the ticket
