### ISSUE TITLE
Prefix disappeared

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#89]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

I am running version 1.9.4
### What plugins are you using? Type /plugins

Well, I have 46 plugins but I don't think any of them would collide with nametagedit.
### Please explain your issue?

I did /ne player (my name) prefix &8[&4&lOwner&8] and it showed up on tab for a second, then disappeared
### How do you reproduce the issue?

I don't get what you mean.

**Comment by sgtcaze** [comment]
Do you have Citizens2 or an NPC plugin on your server?

**Comment by ghost** [comment]
no but I do have HolographicDisplays if that effects anything

**Comment by sgtcaze** [comment]
Use /ne debug and then /ne reload
If your tag disappears again, please send the output around that time.

**Comment by sgtcaze** [comment]
No update in 5 days. Closing for now. Please reopen if the issue persists.
