### ISSUE TITLE
LuckPerms Support on 1.20.2

### ISSUE THREAD

**Issue by M4xi2312** [sgtcaze/NametagEdit#893]
**LuckPerms Prefixes don't work on Player Nametags with NametagEdit.**

**Paper version:** _1.20.2 Build 318_
**NametagEdit version:** _4.5.23_

**Plugins:**
AdvancedBan, ArmorStandEditor, AuctionHouse, AureliumSkills, BankPlus, BetterRTP, BlockParticles, Brewery, CMILib, Chunky, ClearLag, ClientDetector, ConditionalEvents, CrazyCrates, CrazyEnchantments, CustomCrafting, CustomHeads, DeathMessages, DecentHolograms, DeluxeMenus, ESFreeze, EconomyShopGUI, Elevator, Essentials, EssentialsChat, EssentialsSpawn, FarmControl, FastAsyncWorldEdit, GSit, GriefPrevention, GrimAC, ImageOnMap, InvSeePlusPlus, InvisibleItemFrames, ItemEdit, ItemTag, Jobs, LuckPerms, Maintenance, MiniMOTD, Multiverse-Core, MythicMobs, NametagEdit, NoChatReports, Orebfuscator, PL-Hide, PlaceholderAPI, PlayerParticles, PlayerReport, PlayerWarps, ProtocolLib, Quests, QuickShop, RHSignItem, ServerSigns, ServerUtils, ServersNPC, SimpleAdvertising, SkinsRestorer, TAB, TabTPS, Towny, TradeSystem, TreeAssist, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, WolfyUtilities, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, ajLeaderboards, eGlow, spark, voicechat

**Comment by gooxa** [comment]
Use HEX format colors,  Example red: " #FF0028 " Look for it on a website that creates these formats.

I use 1.20.2 pàper version, 
Minecraft basic colors don't work.

![image](https://github.com/sgtcaze/NametagEdit/assets/160295450/5eb97941-f558-456f-ab3c-e0c846833e6f)
![image](https://github.com/sgtcaze/NametagEdit/assets/160295450/ef3751ef-240b-415a-b9a4-11a06c82a75e)

my config in tab in file "groups" is:  tagprefix: "%nte_prefix%%luckperms-prefix%"

Install nte placeholders in spigot page , look in google.
