### ISSUE TITLE
Service Unavailable - https://ci.nametagedit.com/plugin/repository/everything/

### ISSUE THREAD

**Issue by Greenfoot5** [sgtcaze/NametagEdit#896]
The CI appears to be down.

<img width="889" alt="Screenshot 2024-02-10 at 15 34 12" src="https://github.com/sgtcaze/NametagEdit/assets/16924652/6fe8a32e-3b59-460a-9a32-dc8e877ee7ca">

**Comment by xXSlideSlimeXx** [comment]
It works now, I guess

**Comment by JustOneMoreBlock** [comment]
Fixed it last night.
