### ISSUE TITLE
Tags Disappearing

### ISSUE THREAD

**Issue by quadbamber** [sgtcaze/NametagEdit#9]
I started to test MySQL database
one time when I logged in the tag has disappeared
but when I reload the plugin it comes back
this has happened to me and a mate.

Thank you
Joe
Keep up the great work!!

**Comment by sgtcaze** [comment]
Disappearing tags was an issue with 3.0 and was fixed in 4.0. Was this test recent?

**Comment by quadbamber** [comment]
Today
maybe check the code for MySQL database

And i am using Build #23 (Feb 16, 2016 4:25:58 PM)

**Comment by quadbamber** [comment]
sgtcaze could you check your Skype and my username is quadbamber (Joe)

**Comment by sgtcaze** [comment]
When you say the tag disappeared - do you mean from the database or in game?

e.g. if they join does their tag load, then they quit and it doesn't come back?
or do you mean that the data isn't saving at all - any errors?

**Comment by quadbamber** [comment]
In game and no errors
![2016-02-18_20 27 59](https://cloud.githubusercontent.com/assets/12215202/13157184/56eb5176-d67e-11e5-8a2d-a4e1d5619f5e.png)

Then i do /nte reload

![2016-02-18_20 28 30](https://cloud.githubusercontent.com/assets/12215202/13157168/42ffa5a4-d67e-11e5-98a9-a9f716a3c2e8.png)

**Comment by quadbamber** [comment]
I have set up all the groups in the database correctly all with permission
when a trainee staff member logs on it does not give them their tag
for some reason it give them a completely different one and I set up all the permissions correctly
![2016-02-18_20 34 48](https://cloud.githubusercontent.com/assets/12215202/13157414/b808fec6-d67f-11e5-983a-6351af95128e.png)

**Comment by quadbamber** [comment]
and my MySQL database sorry for replying so many times

![untitled](https://cloud.githubusercontent.com/assets/12215202/13157849/077eb368-d682-11e5-9818-e5f942cfb771.png)

**Comment by sgtcaze** [comment]
please send a screenshot of your database nte_groups structure, and your permissions.

It should look something like this (in phpMyAdmin)
![img](https://cloud.githubusercontent.com/assets/4266612/13158375/7b765f3c-d641-11e5-8fab-ecc80203c4b5.PNG)

**Comment by quadbamber** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/12215202/13158732/2c5acd8a-d686-11e5-9d8f-d035a77a84a7.png)

**Comment by sgtcaze** [comment]
Alright, to recreate I just need to know your permissions plugin and the structure of your permissions.

Or is this in the database as well?

**Comment by quadbamber** [comment]
PermissionEX

one more small question as well would you use Zpermission for a network?

**Comment by sgtcaze** [comment]
Personally, I would use zPermissions. Please send me your permissions file. I need to cross check some things.

**Comment by quadbamber** [comment]
http://paste.md-5.net/nuwutu

**Comment by quadbamber** [comment]
can you send me a link where you get zPermissions from please

**Comment by sgtcaze** [comment]
Thanks for being patient, tackling some other bugs. Will test some more soon.

**Comment by JustOneMoreBlock** [comment]
@quadbamber This still an issue you're having?

**Comment by quadbamber** [comment]
Yes

**Comment by sgtcaze** [comment]
This is connected to another issue. Update soon.
