### ISSUE TITLE
Can't use the tab option!

### ISSUE THREAD

**Issue by KeidoFX** [sgtcaze/NametagEdit#91]

**Comment by KeidoFX** [comment]
BUMP

**Comment by KeidoFX** [comment]
BUMPERINO

**Comment by sgtcaze** [comment]
I am confused what your issue is. The nametag looks like it applied. Is your issue that the entire nametag isn't shown? Or the tab isn't disabled?

**Comment by KeidoFX** [comment]
The entire nametag isn't shown.

**Comment by sgtcaze** [comment]
Please see the FAQ/Documentation for more info. Basically, your nametag is limited to 16 characters for the prefix and 16 characters for the suffix. This is why the whole nametag is not shown.

**Comment by KeidoFX** [comment]
is there any way to bypass it? I saw servers that bypassed it..

**Comment by sgtcaze** [comment]
Not possible to bypass with Scoreboards. They may be doing something incredibly hacky, such as spawning an armor stand above a player's head and hiding their nametag.

**Comment by KeidoFX** [comment]
Can you add it? :O
