### ISSUE TITLE
Permissions doesn't work with PEX but works with Gmanager

### ISSUE THREAD

**Issue by Twonox** [sgtcaze/NametagEdit#92]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

I use the latest dev build (there is same problem with latest official build)
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

I use latest spigot 1.8.8
### What plugins are you using? Type /plugins

I use permissionex for permissions
### Please explain your issue?

The permissions doesn't work with PEX but with Groupmanager they work.
### Is there an error(s) in the console? Please use: https://pastebin.com

There is no errors. Even I do /nte reload

**Comment by sgtcaze** [comment]
Please post your Groups.yml and Permissions.yml, and describe what is happening. For example, Player A has permission XYZ but is not getting the tag for Group A etc.

**Comment by Twonox** [comment]
**Groups.yml**
http://hastebin.com/ubakegeqaj.pl

**Permissions.yml**
http://hastebin.com/umuwiquhez.go

I have the PEX group `Fonda`, I have the permission `nte.fonda` but my NTE group is `Cobay`, not `Fonda`.
This is the first NTE group that is considered. If I reverse Cobay & Fonda, my NTE group is Fonda even I don't have the permission `nte.fonda`.

**Comment by Twonox** [comment]
The cause of this problem is `'*'` permission. Without this permission there is no problem with NTE permissions.

**Comment by sgtcaze** [comment]
Ah. This makes sense, and is not an issue inherent to NametagEdit. Glad you found the issue!
