### ISSUE TITLE
Not Able To Prefix from 1 rank and Suffix from Another!

### ISSUE THREAD

**Issue by Articdive** [sgtcaze/NametagEdit#94]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
- 4,1,2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

https://gyazo.com/c15cf8d4e407612ff3c2b2b806497aed
### What plugins are you using? Type /plugins

https://gyazo.com/bcbf4572a7ab77dc99afb7f8730b8041
### Please explain your issue?

I wouldn't consider it an issue (wasn't sure where to put this) but i can't do sub-groups for suffixes for example:
I have a NEWBIE rank with nte.newbie which gives a prefix of/ outputs (NEWBIE) (USERNAME)
Then i want the donor rank to change the suffix so its like (NEWBIE) (USERNAME) (VIP)
but when i give VIP the nte.vip perm (and i did set this up correctly) it just continues to display the Newbie one only
after a little research i discovered that i can't have the prefix from one rank and the suffix from another,
at least till now,
I mean i can show my configs & perms
but im too lazy too and i dont think that is the problem but if it is im more than glad to do so
### How do you reproduce the issue?

Kinda Self Explanitory if you ask me
### Is there an error(s) in the console? Please use: https://pastebin.com

No.

Sorry for using gyazo im just too lazy to actually type the stuff out

**Comment by sgtcaze** [comment]
Not possible with NametagEdit's current functionality. This is intended as some people want empty tags or nonoverlapping from lower group priorities.

**Comment by Articdive** [comment]
Well could you suggest a diffrent plugin that allows me to do this or add some sorta config option in the next update?

**Comment by Articdive** [comment]
nvm I decided to use Essentials TAB formatting and only the prefix of certain ranks on the nameplate above the player,
cheers
