### ISSUE TITLE
How do you do spaces in between the name tag and player name?

### ISSUE THREAD

**Issue by Opious** [sgtcaze/NametagEdit#95]
Version: 4.1.2

Hi, I have no idea how to do spaces in between the nametag and the player name.

Cheers, Opious

**Comment by Opious** [comment]
Nevermind found out how to in the config but you should allow to do this in a command like using _ as a space. Great plugin though

**Comment by sgtcaze** [comment]
In the documentation we specify you can do:
/nte player NAME prefix " Something " and it will replace the " with spaces.
