### ISSUE TITLE
NameTagEdit tab

### ISSUE THREAD

**Issue by mrmiijo** [sgtcaze/NametagEdit#96]

**Comment by LinuxZombie-Sys** [comment]
I discovered if you remove the # from change-playerlist: true (#change-playerlist: true) in essentials config it bugs out the tab list.

**Comment by mrmiijo** [comment]
It did not help. Still prefix disappears in Tab.

**Comment by LinuxZombie-Sys** [comment]
whats ur server ip may i take a look

**Comment by sgtcaze** [comment]
Looks like you're using LibsDisguises. Apparently we have a compatibility issue with it (see #86)

We tried to listen to the undisguise event, but it doesn't seem to have fixed it for some users.

**Comment by mrmiijo** [comment]
ComputerTechOfficial .. I am Slovak, so something on my server you did not understand. 😃 (Therefore, my English is bad)

sgtcaze .. Prefix disappears, although when I the plugin unload.

**Comment by sgtcaze** [comment]
Are you still experiencing issues?
