### ISSUE TITLE
NameTagEdit: Tab and above head prefixes 

### ISSUE THREAD

**Issue by LinuxZombie-Sys** [sgtcaze/NametagEdit#97]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

Latest Version of spigot 1.10.2
### What plugins are you using? Type /plugins

Groupmanager and Essentials & multiverse 
### Please explain your issue?

when reconnecting to the server or going to a different world, the name above the head and tab list goes away, same thing when going to any other server within the network like /server survival
### How do you reproduce the issue?

just by going to another world or server
### Is there an error(s) in the console? Please use: https://pastebin.com

no errors but i did find out why the Tab list bugs out, 

if you have #change-playerlist: true, enabled in the essentials config and you use a nickname with color codes, it bugs out the plugin in the tab list, so try to fix that

**Comment by sgtcaze** [comment]
Your nametag should persist between worlds no problem... so I'll have to look into it.

Also, NametagEdit will not work inbetween servers (/server survival). You will need to use MySQL to synchronize nametags.

**Comment by LinuxZombie-Sys** [comment]
it does work i fixed it if you install it on all the servers (Not bungee) and keep #change-playerlist: true as disabled then it will work within the network, so i fixed it

**Comment by sgtcaze** [comment]
Thank you for explaining the issue. I will add it to the documentation just in case others have this issue :D
