### ISSUE TITLE
Compatibility EssentialsX Chat

### ISSUE THREAD

**Issue by sufletzel** [sgtcaze/NametagEdit#98]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

NametagEdit version 4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

spigot 1.10.2-R0.1
### What plugins are you using? Type /plugins

MinePacks, BarAPI, PlaceholderAPI, NametagEdit, GeneralLib, CustomRecipes, StaffSound, UUID, ItemChat, Chester, AutoAntiFlood, CostlyEnchanting, CPFix, ChestMaster, CoreProtect, TTA, WorldEdit, Advanced_Item_Effects, InventoryFull, Essentials, OcelaHelp, AWD, ClearLag, AutoMessage, KillCounter, WorldBorder, AntiMobFarm, Votifier, IronElevators, CraftedBy, Multiverse-Core, ProtocolLib, LibsDisguises, eZProtector, NoAnvilBreak, IPWhitelist, SavedWorld, EssentialsChat, OpGuard, PermissionsEx, MoreVillagers, QwickTree, AntiItemDuplicate, Zenchantments, mcMMO, InsaneMobs2, GAListener, Vault, ProtocolSupport, Cannons, MCMMOXPBar, SlotMachine, ShareControl, EpicRename, Trading, HolographicDisplays, LWC, LWC-WorldEdit-Addon, WorldGuard, PermissionsEx_Gui, Spawners, ChestCommands, EssentialsProtect, ProtectionLib, CraftBay, StaffList, EssentialsSpawn, PvPManager, ActivityCoins, TitleManager, Wild, HolographicScoreboard, Orebfuscator4, iZone, AreaShop, HeadHunter, mcMMOAction, PreciousStones, McMMOExtras, CTSNC, InfoBoardReborn, Citizens, OnTime, GlobalMarket, ShopChest, PvpTitles, CombatIndicator, NoFlyZone, AuthMe, ChatGuard, MobHunting, CompatNoCheatPlus, NoCheatPlus, Magic, AuthMeBridge
### Please explain your issue?

I can't put a nickname.... Prefix don't show up!

**Comment by sgtcaze** [comment]
Noticed you're using LibsDisguises. This may be related to #86 

Do /ne debug and try to set a prefix again. And then:
1) send us the output after you change nametags
2) are you using the Groups or Players option?
3) do you have the nametag above your head but not in tab? or vice versa
