### ISSUE TITLE
Error while Converting from "file" to "db"

### ISSUE THREAD

**Issue by Muffin2Go** [sgtcaze/NametagEdit#99]
### What version/build of NametagEdit are you using? Type /ver NametagEdit

4.1.2
### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver

git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
### What plugins are you using? Type /plugins

ReportsMenu (Own one), WorldEdit, Essentials, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, PremissionsEx, NametagEdit xD, Vault, EssentialsSpawn, BanManager(Own One), Multiverse-Core, WorldGuard
### Please explain your issue?

Error when trying to convert from file to db
### How do you reproduce the issue?

Error when trying to convert from file to db
### Is there an error(s) in the console? Please use: https://pastebin.com

http://pastebin.com/Yjr52yp9

**Comment by sgtcaze** [comment]
Please post your groups.yml and players.yml files. You can find them in the plugins/NametagEdit folder.

Looks like they didn't have the necessary components. Either that, or they were null.
